http:
  routers:
    backend-api:
      rule: "PathPrefix(`/api/`)"
      service: backend-service
      middlewares:
        - strip-api-prefix
    backend-ws:
      rule: "PathPrefix(`/ws`)"
      service: backend-service
    frontend:
      rule: "PathPrefix(`/`)"
      service: frontend-service
      priority: 1

  services:
    backend-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8080"
    frontend-service:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000"

  middlewares:
    strip-api-prefix:
      stripPrefix:
        prefixes:
          - "/api"
