// Code generated by MockGen. DO NOT EDIT.
// Source: b:\gate\core\internal\domain\interfaces\pandoc.go
//
// Generated by this command:
//
//	mockgen -source=b:\gate\core\internal\domain\interfaces\pandoc.go -destination=b:\gate\core\tests\mocks\pandoc_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPandocClient is a mock of PandocClient interface.
type MockPandocClient struct {
	ctrl     *gomock.Controller
	recorder *MockPandocClientMockRecorder
	isgomock struct{}
}

// MockPandocClientMockRecorder is the mock recorder for MockPandocClient.
type MockPandocClientMockRecorder struct {
	mock *MockPandocClient
}

// NewMockPandocClient creates a new mock instance.
func NewMockPandocClient(ctrl *gomock.Controller) *MockPandocClient {
	mock := &MockPandocClient{ctrl: ctrl}
	mock.recorder = &MockPandocClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPandocClient) EXPECT() *MockPandocClientMockRecorder {
	return m.recorder
}

// BatchConvertLatexToHtml5 mocks base method.
func (m *MockPandocClient) BatchConvertLatexToHtml5(ctx context.Context, texts []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchConvertLatexToHtml5", ctx, texts)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchConvertLatexToHtml5 indicates an expected call of BatchConvertLatexToHtml5.
func (mr *MockPandocClientMockRecorder) BatchConvertLatexToHtml5(ctx, texts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchConvertLatexToHtml5", reflect.TypeOf((*MockPandocClient)(nil).BatchConvertLatexToHtml5), ctx, texts)
}
