// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: images.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createImage = `-- name: CreateImage :exec
INSERT INTO images (
        id,
        image
    )
VALUES (
        $1::uuid,
        $2
    )
`

type CreateImageParams struct {
	ID    uuid.UUID `json:"id"`
	Image string    `json:"image"`
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) error {
	_, err := q.db.Exec(ctx, createImage, arg.ID, arg.Image)
	return err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images
WHERE id = $1::uuid
`

func (q *Queries) DeleteImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteImage, id)
	return err
}

const getImageById = `-- name: GetImageById :one
SELECT id, image, created_at, updated_at
FROM images
WHERE id = $1::uuid
LIMIT 1
`

func (q *Queries) GetImageById(ctx context.Context, id uuid.UUID) (Image, error) {
	row := q.db.QueryRow(ctx, getImageById, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
