// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::int4
FROM users
WHERE (
        $1::text = ''
        OR word_similarity(username, $1) > 0.1
    )
    AND (
        $2::text = ''
        OR role::text = $2
    )
`

type CountUsersParams struct {
	Search string `json:"search"`
	Role   string `json:"role"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Search, arg.Role)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
        id,
        username,
        role,
        kratos_id,
        email,
        name,
        surname,
        bio,
        img_id
    )
VALUES (
        $1::uuid,
        $2,
        $3,
        $4::uuid,
        $5,
        $6,
        $7,
        $8,
        $9
    )
`

type CreateUserParams struct {
	ID       uuid.UUID  `json:"id"`
	Username string     `json:"username"`
	Role     UserRole   `json:"role"`
	KratosID uuid.UUID  `json:"kratos_id"`
	Email    string     `json:"email"`
	Name     string     `json:"name"`
	Surname  string     `json:"surname"`
	Bio      string     `json:"bio"`
	ImgID    *uuid.UUID `json:"img_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Role,
		arg.KratosID,
		arg.Email,
		arg.Name,
		arg.Surname,
		arg.Bio,
		arg.ImgID,
	)
	return err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, role, kratos_id, created_at, updated_at, email, name, surname, bio, img_id
FROM users
WHERE id = $1::uuid
LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.KratosID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Name,
		&i.Surname,
		&i.Bio,
		&i.ImgID,
	)
	return i, err
}

const getUserByKratosId = `-- name: GetUserByKratosId :one
SELECT id, username, role, kratos_id, created_at, updated_at, email, name, surname, bio, img_id
FROM users
WHERE kratos_id = $1::uuid
LIMIT 1
`

func (q *Queries) GetUserByKratosId(ctx context.Context, kratosID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByKratosId, kratosID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.KratosID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Name,
		&i.Surname,
		&i.Bio,
		&i.ImgID,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, role, kratos_id, created_at, updated_at, email, name, surname, bio, img_id
FROM users
WHERE (
        $1::text = ''
        OR word_similarity(username, $1) > 0.1
    )
    AND (
        $2::text = ''
        OR role::text = $2
    )
ORDER BY CASE
        WHEN $1 != '' THEN word_similarity(username, $1)
    END DESC NULLS LAST,
    created_at DESC
LIMIT $4 OFFSET $3
`

type ListUsersParams struct {
	Search string `json:"search"`
	Role   string `json:"role"`
	Offset int32  `json:"offset"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Search,
		arg.Role,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.KratosID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.Name,
			&i.Surname,
			&i.Bio,
			&i.ImgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET username = COALESCE($1, username),
    role = COALESCE($2, role),
    email = COALESCE($3, email),
    name = COALESCE($4, name),
    surname = COALESCE($5, surname),
    bio = COALESCE($6, bio),
    img_id = COALESCE($7, img_id)
WHERE id = $8::uuid
`

type UpdateUserParams struct {
	Username *string      `json:"username"`
	Role     NullUserRole `json:"role"`
	Email    *string      `json:"email"`
	Name     *string      `json:"name"`
	Surname  *string      `json:"surname"`
	Bio      *string      `json:"bio"`
	ImgID    *uuid.UUID   `json:"img_id"`
	ID       uuid.UUID    `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Username,
		arg.Role,
		arg.Email,
		arg.Name,
		arg.Surname,
		arg.Bio,
		arg.ImgID,
		arg.ID,
	)
	return err
}
