// Code generated by MockGen. DO NOT EDIT.
// Source: b:\gate\core\internal\domain\interfaces\nats.go
//
// Generated by this command:
//
//	mockgen -source=b:\gate\core\internal\domain\interfaces\nats.go -destination=b:\gate\core\tests\mocks\nats_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNatsPublisher is a mock of NatsPublisher interface.
type MockNatsPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockNatsPublisherMockRecorder
	isgomock struct{}
}

// MockNatsPublisherMockRecorder is the mock recorder for MockNatsPublisher.
type MockNatsPublisherMockRecorder struct {
	mock *MockNatsPublisher
}

// NewMockNatsPublisher creates a new mock instance.
func NewMockNatsPublisher(ctrl *gomock.Controller) *MockNatsPublisher {
	mock := &MockNatsPublisher{ctrl: ctrl}
	mock.recorder = &MockNatsPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNatsPublisher) EXPECT() *MockNatsPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockNatsPublisher) Publish(subject string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", subject, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockNatsPublisherMockRecorder) Publish(subject, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockNatsPublisher)(nil).Publish), subject, data)
}
