version: '3'

tasks:
  dev:
    desc: "Run Next.js dev server"
    cmds:
      - bun dev

  build:
    desc: "Build production bundle"
    cmds:
      - bun run build

  build:local:
    desc: "Build production bundle with local env"
    cmds:
      - bun run build:local

  build:prod:
    desc: "Build production bundle with prod env"
    cmds:
      - bun run build:prod

  typecheck:
    desc: "Run TypeScript type check"
    cmds:
      - bun run typecheck

  lint:
    desc: "Run ESLint and Stylelint"
    cmds:
      - bun run lint

  knip:
    desc: "Run Knip unused code check"
    cmds:
      - bun run knip
