version: "2"

linters:
  enable:
    - bodyclose
    - dupl
    - errorlint
    - forbidigo
    - gocritic
    - gosec
    - nilerr
    - revive
    - sqlclosecheck
    - testifylint
    - tparallel
    - unparam
    - wrapcheck
  settings:
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print.*$
          msg: Do not use fmt.Print*, use slog instead.
        - pattern: ^log\.(Print|Fatal|Panic).*$
          msg: Do not use log package, use slog instead.
    revive:
      rules:
        - name: var-naming
          disabled: true
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - errors.Join(
        - .Wrap(
        - .Wrapf(
        - HandleContextErr(
        - .Err()
        - .Write(
        - .Encode(
        - .Parse(
      ignore-package-globs:
        - github.com/brawler2011/gate/backend/*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*\.pb\.go$
      - contracts
      - tests/mocks
    rules:
      - linters:
          - gosec
        text: "G124|G122|G703|G304|G301"
      - linters:
          - staticcheck
        text: "ST1023|ST1012|QF1003|QF1011"
