// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package userssqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ContestRole string

const (
	ContestRoleOwner       ContestRole = "owner"
	ContestRoleModerator   ContestRole = "moderator"
	ContestRoleParticipant ContestRole = "participant"
)

func (e *ContestRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContestRole(s)
	case string:
		*e = ContestRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ContestRole: %T", src)
	}
	return nil
}

type NullContestRole struct {
	ContestRole ContestRole `json:"contest_role"`
	Valid       bool        `json:"valid"` // Valid is true if ContestRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContestRole) Scan(value interface{}) error {
	if value == nil {
		ns.ContestRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContestRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContestRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContestRole), nil
}

type ContestVisibility string

const (
	ContestVisibilityPrivate ContestVisibility = "private"
	ContestVisibilityPublic  ContestVisibility = "public"
)

func (e *ContestVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContestVisibility(s)
	case string:
		*e = ContestVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for ContestVisibility: %T", src)
	}
	return nil
}

type NullContestVisibility struct {
	ContestVisibility ContestVisibility `json:"contest_visibility"`
	Valid             bool              `json:"valid"` // Valid is true if ContestVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContestVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.ContestVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContestVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContestVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContestVisibility), nil
}

type OutboxEventStatus string

const (
	OutboxEventStatusPending    OutboxEventStatus = "pending"
	OutboxEventStatusProcessing OutboxEventStatus = "processing"
	OutboxEventStatusCompleted  OutboxEventStatus = "completed"
	OutboxEventStatusFailed     OutboxEventStatus = "failed"
)

func (e *OutboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxEventStatus(s)
	case string:
		*e = OutboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxEventStatus: %T", src)
	}
	return nil
}

type NullOutboxEventStatus struct {
	OutboxEventStatus OutboxEventStatus `json:"outbox_event_status"`
	Valid             bool              `json:"valid"` // Valid is true if OutboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxEventStatus), nil
}

type ProblemRole string

const (
	ProblemRoleOwner     ProblemRole = "owner"
	ProblemRoleModerator ProblemRole = "moderator"
)

func (e *ProblemRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProblemRole(s)
	case string:
		*e = ProblemRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ProblemRole: %T", src)
	}
	return nil
}

type NullProblemRole struct {
	ProblemRole ProblemRole `json:"problem_role"`
	Valid       bool        `json:"valid"` // Valid is true if ProblemRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProblemRole) Scan(value interface{}) error {
	if value == nil {
		ns.ProblemRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProblemRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProblemRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProblemRole), nil
}

type ProblemVisibility string

const (
	ProblemVisibilityPrivate ProblemVisibility = "private"
	ProblemVisibilityPublic  ProblemVisibility = "public"
)

func (e *ProblemVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProblemVisibility(s)
	case string:
		*e = ProblemVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for ProblemVisibility: %T", src)
	}
	return nil
}

type NullProblemVisibility struct {
	ProblemVisibility ProblemVisibility `json:"problem_visibility"`
	Valid             bool              `json:"valid"` // Valid is true if ProblemVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProblemVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.ProblemVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProblemVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProblemVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProblemVisibility), nil
}

type UserRole string

const (
	UserRoleUser  UserRole = "user"
	UserRoleAdmin UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Contest struct {
	ID                     uuid.UUID         `json:"id"`
	Title                  string            `json:"title"`
	Description            string            `json:"description"`
	Visibility             ContestVisibility `json:"visibility"`
	MonitorScope           ContestRole       `json:"monitor_scope"`
	SubmissionsListScope   ContestRole       `json:"submissions_list_scope"`
	SubmissionsReviewScope ContestRole       `json:"submissions_review_scope"`
	CreatedBy              pgtype.UUID       `json:"created_by"`
	CreatedAt              time.Time         `json:"created_at"`
	UpdatedAt              time.Time         `json:"updated_at"`
}

type ContestMember struct {
	UserID    uuid.UUID   `json:"user_id"`
	ContestID uuid.UUID   `json:"contest_id"`
	Role      ContestRole `json:"role"`
}

type ContestProblem struct {
	ProblemID pgtype.UUID `json:"problem_id"`
	ContestID pgtype.UUID `json:"contest_id"`
	Position  int32       `json:"position"`
}

type OutboxEvent struct {
	ID            uuid.UUID          `json:"id"`
	AggregateID   uuid.UUID          `json:"aggregate_id"`
	AggregateType string             `json:"aggregate_type"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	Status        OutboxEventStatus  `json:"status"`
	CreatedAt     time.Time          `json:"created_at"`
	ProcessedAt   pgtype.Timestamptz `json:"processed_at"`
	RetryCount    int32              `json:"retry_count"`
	ErrorMessage  *string            `json:"error_message"`
}

type Problem struct {
	ID               uuid.UUID         `json:"id"`
	CreatedBy        pgtype.UUID       `json:"created_by"`
	Visibility       ProblemVisibility `json:"visibility"`
	Title            string            `json:"title"`
	TimeLimit        int32             `json:"time_limit"`
	MemoryLimit      int32             `json:"memory_limit"`
	Legend           string            `json:"legend"`
	InputFormat      string            `json:"input_format"`
	OutputFormat     string            `json:"output_format"`
	Notes            string            `json:"notes"`
	Scoring          string            `json:"scoring"`
	LegendHtml       string            `json:"legend_html"`
	InputFormatHtml  string            `json:"input_format_html"`
	OutputFormatHtml string            `json:"output_format_html"`
	NotesHtml        string            `json:"notes_html"`
	ScoringHtml      string            `json:"scoring_html"`
	CreatedAt        time.Time         `json:"created_at"`
	UpdatedAt        time.Time         `json:"updated_at"`
}

type ProblemMember struct {
	ProblemID pgtype.UUID `json:"problem_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Role      ProblemRole `json:"role"`
}

type ProblemTest struct {
	ID        uuid.UUID `json:"id"`
	ProblemID uuid.UUID `json:"problem_id"`
	Ordinal   int32     `json:"ordinal"`
	Input     string    `json:"input"`
	Output    string    `json:"output"`
	CreatedAt time.Time `json:"created_at"`
}

type Submission struct {
	ID         uuid.UUID   `json:"id"`
	ContestID  pgtype.UUID `json:"contest_id"`
	ProblemID  pgtype.UUID `json:"problem_id"`
	CreatedBy  pgtype.UUID `json:"created_by"`
	Submission string      `json:"submission"`
	Language   int32       `json:"language"`
	State      int32       `json:"state"`
	Score      int32       `json:"score"`
	Penalty    int32       `json:"penalty"`
	TimeStat   int32       `json:"time_stat"`
	MemoryStat int32       `json:"memory_stat"`
	UpdatedAt  time.Time   `json:"updated_at"`
	CreatedAt  time.Time   `json:"created_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Username  string    `json:"username"`
	Role      UserRole  `json:"role"`
	KratosID  string    `json:"kratos_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Email     *string   `json:"email"`
	Name      *string   `json:"name"`
	Surname   *string   `json:"surname"`
	Bio       *string   `json:"bio"`
	Img       *string   `json:"img"`
}
