// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contest_teams.sql

package sqlc

import (
	"context"
	"time"

	"github.com/gate149/gate/backend/internal/domain/models"
	"github.com/google/uuid"
)

const addContestTeam = `-- name: AddContestTeam :exec

INSERT INTO contest_teams (contest_id, team_id, role)
VALUES ($1, $2, $3)
`

type AddContestTeamParams struct {
	ContestID uuid.UUID          `json:"contest_id"`
	TeamID    uuid.UUID          `json:"team_id"`
	Role      models.ContestRole `json:"role"`
}

// Contest Teams queries (team-based access control)
func (q *Queries) AddContestTeam(ctx context.Context, arg AddContestTeamParams) error {
	_, err := q.db.Exec(ctx, addContestTeam, arg.ContestID, arg.TeamID, arg.Role)
	return err
}

const getContestTeam = `-- name: GetContestTeam :one
SELECT contest_id, team_id, role, created_at, permissions_mask FROM contest_teams
WHERE contest_id = $1 AND team_id = $2
`

type GetContestTeamParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	TeamID    uuid.UUID `json:"team_id"`
}

func (q *Queries) GetContestTeam(ctx context.Context, arg GetContestTeamParams) (ContestTeam, error) {
	row := q.db.QueryRow(ctx, getContestTeam, arg.ContestID, arg.TeamID)
	var i ContestTeam
	err := row.Scan(
		&i.ContestID,
		&i.TeamID,
		&i.Role,
		&i.CreatedAt,
		&i.PermissionsMask,
	)
	return i, err
}

const getTeamContests = `-- name: GetTeamContests :many
SELECT c.id, c.organization_id, c.owner_id, c.visibility, c.title, c.short_name, c.description, c.settings, c.access_policy, c.start_time, c.end_time, c.created_at, c.updated_at FROM contests c
INNER JOIN contest_teams ct ON c.id = ct.contest_id
WHERE ct.team_id = $1
ORDER BY c.created_at DESC
`

func (q *Queries) GetTeamContests(ctx context.Context, teamID uuid.UUID) ([]Contest, error) {
	rows, err := q.db.Query(ctx, getTeamContests, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contest{}
	for rows.Next() {
		var i Contest
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OwnerID,
			&i.Visibility,
			&i.Title,
			&i.ShortName,
			&i.Description,
			&i.Settings,
			&i.AccessPolicy,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestTeams = `-- name: ListContestTeams :many
SELECT ct.contest_id, ct.team_id, ct.role, ct.created_at, ct.permissions_mask, t.name as team_name, t.slug as team_slug
FROM contest_teams ct
JOIN teams t ON ct.team_id = t.id
WHERE ct.contest_id = $1
ORDER BY ct.created_at
`

type ListContestTeamsRow struct {
	ContestID       uuid.UUID          `json:"contest_id"`
	TeamID          uuid.UUID          `json:"team_id"`
	Role            models.ContestRole `json:"role"`
	CreatedAt       time.Time          `json:"created_at"`
	PermissionsMask int64              `json:"permissions_mask"`
	TeamName        string             `json:"team_name"`
	TeamSlug        string             `json:"team_slug"`
}

func (q *Queries) ListContestTeams(ctx context.Context, contestID uuid.UUID) ([]ListContestTeamsRow, error) {
	rows, err := q.db.Query(ctx, listContestTeams, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContestTeamsRow{}
	for rows.Next() {
		var i ListContestTeamsRow
		if err := rows.Scan(
			&i.ContestID,
			&i.TeamID,
			&i.Role,
			&i.CreatedAt,
			&i.PermissionsMask,
			&i.TeamName,
			&i.TeamSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeContestTeam = `-- name: RemoveContestTeam :exec
DELETE FROM contest_teams
WHERE contest_id = $1 AND team_id = $2
`

type RemoveContestTeamParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	TeamID    uuid.UUID `json:"team_id"`
}

func (q *Queries) RemoveContestTeam(ctx context.Context, arg RemoveContestTeamParams) error {
	_, err := q.db.Exec(ctx, removeContestTeam, arg.ContestID, arg.TeamID)
	return err
}

const updateContestTeamRole = `-- name: UpdateContestTeamRole :exec
UPDATE contest_teams
SET role = $3
WHERE contest_id = $1 AND team_id = $2
`

type UpdateContestTeamRoleParams struct {
	ContestID uuid.UUID          `json:"contest_id"`
	TeamID    uuid.UUID          `json:"team_id"`
	Role      models.ContestRole `json:"role"`
}

func (q *Queries) UpdateContestTeamRole(ctx context.Context, arg UpdateContestTeamRoleParams) error {
	_, err := q.db.Exec(ctx, updateContestTeamRole, arg.ContestID, arg.TeamID, arg.Role)
	return err
}
