// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: contests.sql

package sqlc

import (
	"context"
	"time"

	"github.com/brawler2011/gate/backend/internal/domain/models"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addContestMember = `-- name: AddContestMember :exec

INSERT INTO contest_members (contest_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddContestMemberParams struct {
	ContestID uuid.UUID          `json:"contest_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      models.ContestRole `json:"role"`
}

// Contest Members (direct access control)
func (q *Queries) AddContestMember(ctx context.Context, arg AddContestMemberParams) error {
	_, err := q.db.Exec(ctx, addContestMember, arg.ContestID, arg.UserID, arg.Role)
	return err
}

const addContestProblem = `-- name: AddContestProblem :exec

INSERT INTO contest_problems (contest_id, problem_id, package_id, ordinal)
VALUES ($1, $2, $3, $4)
`

type AddContestProblemParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	ProblemID uuid.UUID `json:"problem_id"`
	PackageID uuid.UUID `json:"package_id"`
	Ordinal   int32     `json:"ordinal"`
}

// Contest Problems (linking to packages)
func (q *Queries) AddContestProblem(ctx context.Context, arg AddContestProblemParams) error {
	_, err := q.db.Exec(ctx, addContestProblem,
		arg.ContestID,
		arg.ProblemID,
		arg.PackageID,
		arg.Ordinal,
	)
	return err
}

const checkUserHasContestAccess = `-- name: CheckUserHasContestAccess :one

SELECT user_has_contest_access($1, $2) as has_access
`

type CheckUserHasContestAccessParams struct {
	PUserID    uuid.UUID `json:"p_user_id"`
	PContestID uuid.UUID `json:"p_contest_id"`
}

// Access check helpers
func (q *Queries) CheckUserHasContestAccess(ctx context.Context, arg CheckUserHasContestAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserHasContestAccess, arg.PUserID, arg.PContestID)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const checkUserIsContestModerator = `-- name: CheckUserIsContestModerator :one
SELECT user_is_contest_moderator($1, $2) as is_moderator
`

type CheckUserIsContestModeratorParams struct {
	PUserID    uuid.UUID `json:"p_user_id"`
	PContestID uuid.UUID `json:"p_contest_id"`
}

func (q *Queries) CheckUserIsContestModerator(ctx context.Context, arg CheckUserIsContestModeratorParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserIsContestModerator, arg.PUserID, arg.PContestID)
	var is_moderator bool
	err := row.Scan(&is_moderator)
	return is_moderator, err
}

const countAllContests = `-- name: CountAllContests :one
SELECT COUNT(*) FROM contests c
WHERE ($1::text = '' OR c.title ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR c.visibility = $2::contest_visibility)
`

type CountAllContestsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountAllContests(ctx context.Context, arg CountAllContestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllContests, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContests = `-- name: CountContests :one
SELECT COUNT(*) FROM contests
WHERE organization_id = $1
  AND ($2::text = '' OR title ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR visibility = $3::contest_visibility)
`

type CountContestsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Column2        string    `json:"column_2"`
	Column3        string    `json:"column_3"`
}

func (q *Queries) CountContests(ctx context.Context, arg CountContestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContests, arg.OrganizationID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContest = `-- name: CreateContest :one

INSERT INTO contests (id, organization_id, owner_id, visibility, title, login, description, settings, start_time, end_time)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, organization_id, owner_id, visibility, title, login, description, settings, start_time, end_time, created_at, updated_at
`

type CreateContestParams struct {
	ID             uuid.UUID                `json:"id"`
	OrganizationID uuid.UUID                `json:"organization_id"`
	OwnerID        pgtype.UUID              `json:"owner_id"`
	Visibility     models.ContestVisibility `json:"visibility"`
	Title          string                   `json:"title"`
	Login          string                   `json:"login"`
	Description    string                   `json:"description"`
	Settings       []byte                   `json:"settings"`
	StartTime      pgtype.Timestamptz       `json:"start_time"`
	EndTime        pgtype.Timestamptz       `json:"end_time"`
}

// Contests queries (new schema with Organizations)
func (q *Queries) CreateContest(ctx context.Context, arg CreateContestParams) (Contest, error) {
	row := q.db.QueryRow(ctx, createContest,
		arg.ID,
		arg.OrganizationID,
		arg.OwnerID,
		arg.Visibility,
		arg.Title,
		arg.Login,
		arg.Description,
		arg.Settings,
		arg.StartTime,
		arg.EndTime,
	)
	var i Contest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.Visibility,
		&i.Title,
		&i.Login,
		&i.Description,
		&i.Settings,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createContestUserProblemBlock = `-- name: CreateContestUserProblemBlock :exec
INSERT INTO contest_user_problem_blocks (contest_id, user_id, problem_id, reason, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (contest_id, user_id, problem_id)
DO UPDATE SET
    reason = EXCLUDED.reason,
    created_by = EXCLUDED.created_by,
    created_at = NOW()
`

type CreateContestUserProblemBlockParams struct {
	ContestID uuid.UUID   `json:"contest_id"`
	UserID    uuid.UUID   `json:"user_id"`
	ProblemID uuid.UUID   `json:"problem_id"`
	Reason    *string     `json:"reason"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

// Contest User Problem Blocks
func (q *Queries) CreateContestUserProblemBlock(ctx context.Context, arg CreateContestUserProblemBlockParams) error {
	_, err := q.db.Exec(ctx, createContestUserProblemBlock,
		arg.ContestID,
		arg.UserID,
		arg.ProblemID,
		arg.Reason,
		arg.CreatedBy,
	)
	return err
}

const deleteContest = `-- name: DeleteContest :exec
DELETE FROM contests WHERE id = $1
`

func (q *Queries) DeleteContest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteContest, id)
	return err
}

const deleteContestUserProblemBlock = `-- name: DeleteContestUserProblemBlock :exec
DELETE FROM contest_user_problem_blocks
WHERE contest_id = $1 AND user_id = $2 AND problem_id = $3
`

type DeleteContestUserProblemBlockParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	UserID    uuid.UUID `json:"user_id"`
	ProblemID uuid.UUID `json:"problem_id"`
}

func (q *Queries) DeleteContestUserProblemBlock(ctx context.Context, arg DeleteContestUserProblemBlockParams) error {
	_, err := q.db.Exec(ctx, deleteContestUserProblemBlock, arg.ContestID, arg.UserID, arg.ProblemID)
	return err
}

const getContestByID = `-- name: GetContestByID :one
SELECT c.id, c.organization_id, c.owner_id, c.visibility, c.title, c.login, c.description, c.settings, c.start_time, c.end_time, c.created_at, c.updated_at, o.login as org_login, o.name as org_name
FROM contests c
JOIN organizations o ON c.organization_id = o.id
WHERE c.id = $1
`

type GetContestByIDRow struct {
	ID             uuid.UUID                `json:"id"`
	OrganizationID uuid.UUID                `json:"organization_id"`
	OwnerID        pgtype.UUID              `json:"owner_id"`
	Visibility     models.ContestVisibility `json:"visibility"`
	Title          string                   `json:"title"`
	Login          string                   `json:"login"`
	Description    string                   `json:"description"`
	Settings       []byte                   `json:"settings"`
	StartTime      pgtype.Timestamptz       `json:"start_time"`
	EndTime        pgtype.Timestamptz       `json:"end_time"`
	CreatedAt      time.Time                `json:"created_at"`
	UpdatedAt      time.Time                `json:"updated_at"`
	OrgLogin       string                   `json:"org_login"`
	OrgName        string                   `json:"org_name"`
}

func (q *Queries) GetContestByID(ctx context.Context, id uuid.UUID) (GetContestByIDRow, error) {
	row := q.db.QueryRow(ctx, getContestByID, id)
	var i GetContestByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.Visibility,
		&i.Title,
		&i.Login,
		&i.Description,
		&i.Settings,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgLogin,
		&i.OrgName,
	)
	return i, err
}

const getContestByLogin = `-- name: GetContestByLogin :one
SELECT c.id, c.organization_id, c.owner_id, c.visibility, c.title, c.login, c.description, c.settings, c.start_time, c.end_time, c.created_at, c.updated_at, o.login as org_login, o.name as org_name
FROM contests c
JOIN organizations o ON c.organization_id = o.id
WHERE c.organization_id = $1 AND LOWER(c.login) = LOWER($2)
`

type GetContestByLoginParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Lower          string    `json:"lower"`
}

type GetContestByLoginRow struct {
	ID             uuid.UUID                `json:"id"`
	OrganizationID uuid.UUID                `json:"organization_id"`
	OwnerID        pgtype.UUID              `json:"owner_id"`
	Visibility     models.ContestVisibility `json:"visibility"`
	Title          string                   `json:"title"`
	Login          string                   `json:"login"`
	Description    string                   `json:"description"`
	Settings       []byte                   `json:"settings"`
	StartTime      pgtype.Timestamptz       `json:"start_time"`
	EndTime        pgtype.Timestamptz       `json:"end_time"`
	CreatedAt      time.Time                `json:"created_at"`
	UpdatedAt      time.Time                `json:"updated_at"`
	OrgLogin       string                   `json:"org_login"`
	OrgName        string                   `json:"org_name"`
}

func (q *Queries) GetContestByLogin(ctx context.Context, arg GetContestByLoginParams) (GetContestByLoginRow, error) {
	row := q.db.QueryRow(ctx, getContestByLogin, arg.OrganizationID, arg.Lower)
	var i GetContestByLoginRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.Visibility,
		&i.Title,
		&i.Login,
		&i.Description,
		&i.Settings,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgLogin,
		&i.OrgName,
	)
	return i, err
}

const getContestByOrgLoginAndContestLogin = `-- name: GetContestByOrgLoginAndContestLogin :one
SELECT c.id, c.organization_id, c.owner_id, c.visibility, c.title, c.login, c.description, c.settings, c.start_time, c.end_time, c.created_at, c.updated_at, o.login as org_login, o.name as org_name
FROM contests c
JOIN organizations o ON c.organization_id = o.id
WHERE LOWER(o.login) = LOWER($1) AND LOWER(c.login) = LOWER($2)
`

type GetContestByOrgLoginAndContestLoginParams struct {
	Lower   string `json:"lower"`
	Lower_2 string `json:"lower_2"`
}

type GetContestByOrgLoginAndContestLoginRow struct {
	ID             uuid.UUID                `json:"id"`
	OrganizationID uuid.UUID                `json:"organization_id"`
	OwnerID        pgtype.UUID              `json:"owner_id"`
	Visibility     models.ContestVisibility `json:"visibility"`
	Title          string                   `json:"title"`
	Login          string                   `json:"login"`
	Description    string                   `json:"description"`
	Settings       []byte                   `json:"settings"`
	StartTime      pgtype.Timestamptz       `json:"start_time"`
	EndTime        pgtype.Timestamptz       `json:"end_time"`
	CreatedAt      time.Time                `json:"created_at"`
	UpdatedAt      time.Time                `json:"updated_at"`
	OrgLogin       string                   `json:"org_login"`
	OrgName        string                   `json:"org_name"`
}

func (q *Queries) GetContestByOrgLoginAndContestLogin(ctx context.Context, arg GetContestByOrgLoginAndContestLoginParams) (GetContestByOrgLoginAndContestLoginRow, error) {
	row := q.db.QueryRow(ctx, getContestByOrgLoginAndContestLogin, arg.Lower, arg.Lower_2)
	var i GetContestByOrgLoginAndContestLoginRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.Visibility,
		&i.Title,
		&i.Login,
		&i.Description,
		&i.Settings,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrgLogin,
		&i.OrgName,
	)
	return i, err
}

const getContestMember = `-- name: GetContestMember :one
SELECT contest_id, user_id, role, created_at FROM contest_members
WHERE contest_id = $1 AND user_id = $2
`

type GetContestMemberParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetContestMember(ctx context.Context, arg GetContestMemberParams) (ContestMember, error) {
	row := q.db.QueryRow(ctx, getContestMember, arg.ContestID, arg.UserID)
	var i ContestMember
	err := row.Scan(
		&i.ContestID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getContestProblem = `-- name: GetContestProblem :one
SELECT cp.contest_id, cp.problem_id, cp.package_id, cp.ordinal, cp.created_at, p.title, p.short_name, p.visibility
FROM contest_problems cp
JOIN problems p ON cp.problem_id = p.id
WHERE cp.contest_id = $1 AND cp.problem_id = $2
`

type GetContestProblemParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	ProblemID uuid.UUID `json:"problem_id"`
}

type GetContestProblemRow struct {
	ContestID  uuid.UUID         `json:"contest_id"`
	ProblemID  uuid.UUID         `json:"problem_id"`
	PackageID  uuid.UUID         `json:"package_id"`
	Ordinal    int32             `json:"ordinal"`
	CreatedAt  time.Time         `json:"created_at"`
	Title      string            `json:"title"`
	ShortName  string            `json:"short_name"`
	Visibility ProblemVisibility `json:"visibility"`
}

func (q *Queries) GetContestProblem(ctx context.Context, arg GetContestProblemParams) (GetContestProblemRow, error) {
	row := q.db.QueryRow(ctx, getContestProblem, arg.ContestID, arg.ProblemID)
	var i GetContestProblemRow
	err := row.Scan(
		&i.ContestID,
		&i.ProblemID,
		&i.PackageID,
		&i.Ordinal,
		&i.CreatedAt,
		&i.Title,
		&i.ShortName,
		&i.Visibility,
	)
	return i, err
}

const getContestProblemResult = `-- name: GetContestProblemResult :one
SELECT contest_id, user_id, problem_id, solved, failed_attempts, first_ac_time, time_minutes, updated_at FROM contest_problem_results
WHERE contest_id = $1 AND user_id = $2 AND problem_id = $3
`

type GetContestProblemResultParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	UserID    uuid.UUID `json:"user_id"`
	ProblemID uuid.UUID `json:"problem_id"`
}

func (q *Queries) GetContestProblemResult(ctx context.Context, arg GetContestProblemResultParams) (ContestProblemResult, error) {
	row := q.db.QueryRow(ctx, getContestProblemResult, arg.ContestID, arg.UserID, arg.ProblemID)
	var i ContestProblemResult
	err := row.Scan(
		&i.ContestID,
		&i.UserID,
		&i.ProblemID,
		&i.Solved,
		&i.FailedAttempts,
		&i.FirstAcTime,
		&i.TimeMinutes,
		&i.UpdatedAt,
	)
	return i, err
}

const getContestScoreboardFromStandings = `-- name: GetContestScoreboardFromStandings :many
SELECT 
    cm.user_id,
    u.username,
    cpr.problem_id,
    cpr.solved,
    cpr.failed_attempts,
    cpr.first_ac_time,
    cpr.time_minutes
FROM contest_members cm
JOIN users u ON cm.user_id = u.id
LEFT JOIN contest_problem_results cpr ON cpr.contest_id = cm.contest_id AND cpr.user_id = cm.user_id
WHERE cm.contest_id = $1 AND cm.role = 'participant'
`

type GetContestScoreboardFromStandingsRow struct {
	UserID         uuid.UUID          `json:"user_id"`
	Username       string             `json:"username"`
	ProblemID      pgtype.UUID        `json:"problem_id"`
	Solved         *bool              `json:"solved"`
	FailedAttempts *int32             `json:"failed_attempts"`
	FirstAcTime    pgtype.Timestamptz `json:"first_ac_time"`
	TimeMinutes    *int32             `json:"time_minutes"`
}

func (q *Queries) GetContestScoreboardFromStandings(ctx context.Context, contestID uuid.UUID) ([]GetContestScoreboardFromStandingsRow, error) {
	rows, err := q.db.Query(ctx, getContestScoreboardFromStandings, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetContestScoreboardFromStandingsRow{}
	for rows.Next() {
		var i GetContestScoreboardFromStandingsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.ProblemID,
			&i.Solved,
			&i.FailedAttempts,
			&i.FirstAcTime,
			&i.TimeMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContestUserProblemBlock = `-- name: GetContestUserProblemBlock :one
SELECT contest_id, user_id, problem_id, reason, created_by, created_at
FROM contest_user_problem_blocks
WHERE contest_id = $1 AND user_id = $2 AND problem_id = $3
`

type GetContestUserProblemBlockParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	UserID    uuid.UUID `json:"user_id"`
	ProblemID uuid.UUID `json:"problem_id"`
}

func (q *Queries) GetContestUserProblemBlock(ctx context.Context, arg GetContestUserProblemBlockParams) (ContestUserProblemBlock, error) {
	row := q.db.QueryRow(ctx, getContestUserProblemBlock, arg.ContestID, arg.UserID, arg.ProblemID)
	var i ContestUserProblemBlock
	err := row.Scan(
		&i.ContestID,
		&i.UserID,
		&i.ProblemID,
		&i.Reason,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getSubmissionsForScoreboard = `-- name: GetSubmissionsForScoreboard :many
SELECT state, created_at
FROM submissions
WHERE contest_id = $1 AND owner_id = $2 AND problem_id = $3
ORDER BY created_at ASC
`

type GetSubmissionsForScoreboardParams struct {
	ContestID pgtype.UUID `json:"contest_id"`
	OwnerID   pgtype.UUID `json:"owner_id"`
	ProblemID pgtype.UUID `json:"problem_id"`
}

type GetSubmissionsForScoreboardRow struct {
	State     models.State `json:"state"`
	CreatedAt time.Time    `json:"created_at"`
}

func (q *Queries) GetSubmissionsForScoreboard(ctx context.Context, arg GetSubmissionsForScoreboardParams) ([]GetSubmissionsForScoreboardRow, error) {
	rows, err := q.db.Query(ctx, getSubmissionsForScoreboard, arg.ContestID, arg.OwnerID, arg.ProblemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSubmissionsForScoreboardRow{}
	for rows.Next() {
		var i GetSubmissionsForScoreboardRow
		if err := rows.Scan(&i.State, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllContests = `-- name: ListAllContests :many
SELECT c.id, c.organization_id, c.owner_id, c.visibility, c.title, c.login, c.description, c.settings, c.start_time, c.end_time, c.created_at, c.updated_at, o.login as org_login, o.name as org_name
FROM contests c
JOIN organizations o ON c.organization_id = o.id
WHERE ($1::text = '' OR c.title ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR c.visibility = $2::contest_visibility)
ORDER BY c.created_at DESC
LIMIT $3 OFFSET $4
`

type ListAllContestsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListAllContestsRow struct {
	ID             uuid.UUID                `json:"id"`
	OrganizationID uuid.UUID                `json:"organization_id"`
	OwnerID        pgtype.UUID              `json:"owner_id"`
	Visibility     models.ContestVisibility `json:"visibility"`
	Title          string                   `json:"title"`
	Login          string                   `json:"login"`
	Description    string                   `json:"description"`
	Settings       []byte                   `json:"settings"`
	StartTime      pgtype.Timestamptz       `json:"start_time"`
	EndTime        pgtype.Timestamptz       `json:"end_time"`
	CreatedAt      time.Time                `json:"created_at"`
	UpdatedAt      time.Time                `json:"updated_at"`
	OrgLogin       string                   `json:"org_login"`
	OrgName        string                   `json:"org_name"`
}

func (q *Queries) ListAllContests(ctx context.Context, arg ListAllContestsParams) ([]ListAllContestsRow, error) {
	rows, err := q.db.Query(ctx, listAllContests,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllContestsRow{}
	for rows.Next() {
		var i ListAllContestsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OwnerID,
			&i.Visibility,
			&i.Title,
			&i.Login,
			&i.Description,
			&i.Settings,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgLogin,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestMembers = `-- name: ListContestMembers :many
SELECT cm.contest_id, cm.user_id, cm.role, cm.created_at, u.username, u.email
FROM contest_members cm
JOIN users u ON cm.user_id = u.id
WHERE cm.contest_id = $1
ORDER BY cm.created_at
`

type ListContestMembersRow struct {
	ContestID uuid.UUID          `json:"contest_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      models.ContestRole `json:"role"`
	CreatedAt time.Time          `json:"created_at"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
}

func (q *Queries) ListContestMembers(ctx context.Context, contestID uuid.UUID) ([]ListContestMembersRow, error) {
	rows, err := q.db.Query(ctx, listContestMembers, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContestMembersRow{}
	for rows.Next() {
		var i ListContestMembersRow
		if err := rows.Scan(
			&i.ContestID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestProblems = `-- name: ListContestProblems :many
SELECT cp.contest_id, cp.problem_id, cp.package_id, cp.ordinal, cp.created_at, p.title, p.short_name, p.visibility, pp.url as package_url
FROM contest_problems cp
JOIN problems p ON cp.problem_id = p.id
JOIN problem_packages pp ON cp.package_id = pp.id
WHERE cp.contest_id = $1
ORDER BY cp.ordinal
`

type ListContestProblemsRow struct {
	ContestID  uuid.UUID         `json:"contest_id"`
	ProblemID  uuid.UUID         `json:"problem_id"`
	PackageID  uuid.UUID         `json:"package_id"`
	Ordinal    int32             `json:"ordinal"`
	CreatedAt  time.Time         `json:"created_at"`
	Title      string            `json:"title"`
	ShortName  string            `json:"short_name"`
	Visibility ProblemVisibility `json:"visibility"`
	PackageUrl *string           `json:"package_url"`
}

func (q *Queries) ListContestProblems(ctx context.Context, contestID uuid.UUID) ([]ListContestProblemsRow, error) {
	rows, err := q.db.Query(ctx, listContestProblems, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContestProblemsRow{}
	for rows.Next() {
		var i ListContestProblemsRow
		if err := rows.Scan(
			&i.ContestID,
			&i.ProblemID,
			&i.PackageID,
			&i.Ordinal,
			&i.CreatedAt,
			&i.Title,
			&i.ShortName,
			&i.Visibility,
			&i.PackageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestUserProblemBlocks = `-- name: ListContestUserProblemBlocks :many
SELECT contest_id, user_id, problem_id, reason, created_by, created_at
FROM contest_user_problem_blocks
WHERE contest_id = $1 AND ($2::uuid IS NULL OR user_id = $2::uuid)
`

type ListContestUserProblemBlocksParams struct {
	ContestID uuid.UUID   `json:"contest_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListContestUserProblemBlocks(ctx context.Context, arg ListContestUserProblemBlocksParams) ([]ContestUserProblemBlock, error) {
	rows, err := q.db.Query(ctx, listContestUserProblemBlocks, arg.ContestID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContestUserProblemBlock{}
	for rows.Next() {
		var i ContestUserProblemBlock
		if err := rows.Scan(
			&i.ContestID,
			&i.UserID,
			&i.ProblemID,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContests = `-- name: ListContests :many
SELECT c.id, c.organization_id, c.owner_id, c.visibility, c.title, c.login, c.description, c.settings, c.start_time, c.end_time, c.created_at, c.updated_at, o.login as org_login, o.name as org_name
FROM contests c
JOIN organizations o ON c.organization_id = o.id
WHERE c.organization_id = $1
  AND ($2::text = '' OR c.title ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR c.visibility = $3::contest_visibility)
ORDER BY c.created_at DESC
LIMIT $4 OFFSET $5
`

type ListContestsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Column2        string    `json:"column_2"`
	Column3        string    `json:"column_3"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

type ListContestsRow struct {
	ID             uuid.UUID                `json:"id"`
	OrganizationID uuid.UUID                `json:"organization_id"`
	OwnerID        pgtype.UUID              `json:"owner_id"`
	Visibility     models.ContestVisibility `json:"visibility"`
	Title          string                   `json:"title"`
	Login          string                   `json:"login"`
	Description    string                   `json:"description"`
	Settings       []byte                   `json:"settings"`
	StartTime      pgtype.Timestamptz       `json:"start_time"`
	EndTime        pgtype.Timestamptz       `json:"end_time"`
	CreatedAt      time.Time                `json:"created_at"`
	UpdatedAt      time.Time                `json:"updated_at"`
	OrgLogin       string                   `json:"org_login"`
	OrgName        string                   `json:"org_name"`
}

func (q *Queries) ListContests(ctx context.Context, arg ListContestsParams) ([]ListContestsRow, error) {
	rows, err := q.db.Query(ctx, listContests,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContestsRow{}
	for rows.Next() {
		var i ListContestsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OwnerID,
			&i.Visibility,
			&i.Title,
			&i.Login,
			&i.Description,
			&i.Settings,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgLogin,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDashboardContests = `-- name: ListDashboardContests :many
SELECT 
    c.id as contest_id,
    c.login as contest_login,
    c.title as contest_title,
    c.start_time as contest_start_time,
    c.end_time as contest_end_time,
    c.created_at as contest_created_at,
    o.id as org_id,
    o.name as org_name,
    o.login as org_login,
    COALESCE(
        (SELECT cm.role::text FROM contest_members cm WHERE cm.contest_id = c.id AND cm.user_id = $1),
        CASE WHEN EXISTS(
            SELECT 1 FROM organization_members om 
            WHERE om.organization_id = c.organization_id AND om.user_id = $1 AND om.role IN ('owner', 'admin')
        ) THEN 'moderator' ELSE 'participant' END
    )::text as user_role,
    sub.last_sub_time
FROM contests c
JOIN organizations o ON c.organization_id = o.id
LEFT JOIN (
    SELECT submissions.contest_id, MAX(submissions.created_at) as last_sub_time
    FROM submissions
    WHERE submissions.owner_id = $1
    GROUP BY submissions.contest_id
) sub ON c.id = sub.contest_id
WHERE user_has_contest_access($1, c.id)
ORDER BY COALESCE(sub.last_sub_time, '1970-01-01 00:00:00+00'::timestamptz) DESC, c.created_at DESC
LIMIT $2
`

type ListDashboardContestsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

type ListDashboardContestsRow struct {
	ContestID        uuid.UUID          `json:"contest_id"`
	ContestLogin     string             `json:"contest_login"`
	ContestTitle     string             `json:"contest_title"`
	ContestStartTime pgtype.Timestamptz `json:"contest_start_time"`
	ContestEndTime   pgtype.Timestamptz `json:"contest_end_time"`
	ContestCreatedAt time.Time          `json:"contest_created_at"`
	OrgID            uuid.UUID          `json:"org_id"`
	OrgName          string             `json:"org_name"`
	OrgLogin         string             `json:"org_login"`
	UserRole         string             `json:"user_role"`
	LastSubTime      interface{}        `json:"last_sub_time"`
}

func (q *Queries) ListDashboardContests(ctx context.Context, arg ListDashboardContestsParams) ([]ListDashboardContestsRow, error) {
	rows, err := q.db.Query(ctx, listDashboardContests, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDashboardContestsRow{}
	for rows.Next() {
		var i ListDashboardContestsRow
		if err := rows.Scan(
			&i.ContestID,
			&i.ContestLogin,
			&i.ContestTitle,
			&i.ContestStartTime,
			&i.ContestEndTime,
			&i.ContestCreatedAt,
			&i.OrgID,
			&i.OrgName,
			&i.OrgLogin,
			&i.UserRole,
			&i.LastSubTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAccessibleContests = `-- name: ListUserAccessibleContests :many
SELECT c.id, c.organization_id, c.owner_id, c.visibility, c.title, c.login, c.description, c.settings, c.start_time, c.end_time, c.created_at, c.updated_at, o.login as org_login, o.name as org_name
FROM contests c
JOIN organizations o ON c.organization_id = o.id
WHERE user_has_contest_access($1, c.id)
ORDER BY c.created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserAccessibleContestsParams struct {
	PUserID uuid.UUID `json:"p_user_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

type ListUserAccessibleContestsRow struct {
	ID             uuid.UUID                `json:"id"`
	OrganizationID uuid.UUID                `json:"organization_id"`
	OwnerID        pgtype.UUID              `json:"owner_id"`
	Visibility     models.ContestVisibility `json:"visibility"`
	Title          string                   `json:"title"`
	Login          string                   `json:"login"`
	Description    string                   `json:"description"`
	Settings       []byte                   `json:"settings"`
	StartTime      pgtype.Timestamptz       `json:"start_time"`
	EndTime        pgtype.Timestamptz       `json:"end_time"`
	CreatedAt      time.Time                `json:"created_at"`
	UpdatedAt      time.Time                `json:"updated_at"`
	OrgLogin       string                   `json:"org_login"`
	OrgName        string                   `json:"org_name"`
}

func (q *Queries) ListUserAccessibleContests(ctx context.Context, arg ListUserAccessibleContestsParams) ([]ListUserAccessibleContestsRow, error) {
	rows, err := q.db.Query(ctx, listUserAccessibleContests, arg.PUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAccessibleContestsRow{}
	for rows.Next() {
		var i ListUserAccessibleContestsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OwnerID,
			&i.Visibility,
			&i.Title,
			&i.Login,
			&i.Description,
			&i.Settings,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgLogin,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAccessibleContestsByOrg = `-- name: ListUserAccessibleContestsByOrg :many
SELECT c.id, c.organization_id, c.owner_id, c.visibility, c.title, c.login, c.description, c.settings, c.start_time, c.end_time, c.created_at, c.updated_at, o.login as org_login, o.name as org_name
FROM contests c
JOIN organizations o ON c.organization_id = o.id
WHERE user_has_contest_access($1, c.id)
  AND c.organization_id = $2
ORDER BY c.created_at DESC
LIMIT $3 OFFSET $4
`

type ListUserAccessibleContestsByOrgParams struct {
	PUserID        uuid.UUID `json:"p_user_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

type ListUserAccessibleContestsByOrgRow struct {
	ID             uuid.UUID                `json:"id"`
	OrganizationID uuid.UUID                `json:"organization_id"`
	OwnerID        pgtype.UUID              `json:"owner_id"`
	Visibility     models.ContestVisibility `json:"visibility"`
	Title          string                   `json:"title"`
	Login          string                   `json:"login"`
	Description    string                   `json:"description"`
	Settings       []byte                   `json:"settings"`
	StartTime      pgtype.Timestamptz       `json:"start_time"`
	EndTime        pgtype.Timestamptz       `json:"end_time"`
	CreatedAt      time.Time                `json:"created_at"`
	UpdatedAt      time.Time                `json:"updated_at"`
	OrgLogin       string                   `json:"org_login"`
	OrgName        string                   `json:"org_name"`
}

func (q *Queries) ListUserAccessibleContestsByOrg(ctx context.Context, arg ListUserAccessibleContestsByOrgParams) ([]ListUserAccessibleContestsByOrgRow, error) {
	rows, err := q.db.Query(ctx, listUserAccessibleContestsByOrg,
		arg.PUserID,
		arg.OrganizationID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAccessibleContestsByOrgRow{}
	for rows.Next() {
		var i ListUserAccessibleContestsByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OwnerID,
			&i.Visibility,
			&i.Title,
			&i.Login,
			&i.Description,
			&i.Settings,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrgLogin,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeContestMember = `-- name: RemoveContestMember :exec
DELETE FROM contest_members
WHERE contest_id = $1 AND user_id = $2
`

type RemoveContestMemberParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveContestMember(ctx context.Context, arg RemoveContestMemberParams) error {
	_, err := q.db.Exec(ctx, removeContestMember, arg.ContestID, arg.UserID)
	return err
}

const removeContestProblem = `-- name: RemoveContestProblem :exec
DELETE FROM contest_problems
WHERE contest_id = $1 AND problem_id = $2
`

type RemoveContestProblemParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	ProblemID uuid.UUID `json:"problem_id"`
}

func (q *Queries) RemoveContestProblem(ctx context.Context, arg RemoveContestProblemParams) error {
	_, err := q.db.Exec(ctx, removeContestProblem, arg.ContestID, arg.ProblemID)
	return err
}

const updateContest = `-- name: UpdateContest :exec
UPDATE contests
SET login = COALESCE($2, login),
    title = COALESCE($3, title),
    description = COALESCE($4, description),
    visibility = COALESCE($5, visibility),
    settings = COALESCE($6, settings),
    start_time = COALESCE($7, start_time),
    end_time = COALESCE($8, end_time),
    owner_id = COALESCE($9, owner_id)
WHERE id = $1
`

type UpdateContestParams struct {
	ID          uuid.UUID             `json:"id"`
	Login       *string               `json:"login"`
	Title       *string               `json:"title"`
	Description *string               `json:"description"`
	Visibility  NullContestVisibility `json:"visibility"`
	Settings    []byte                `json:"settings"`
	StartTime   pgtype.Timestamptz    `json:"start_time"`
	EndTime     pgtype.Timestamptz    `json:"end_time"`
	OwnerID     pgtype.UUID           `json:"owner_id"`
}

func (q *Queries) UpdateContest(ctx context.Context, arg UpdateContestParams) error {
	_, err := q.db.Exec(ctx, updateContest,
		arg.ID,
		arg.Login,
		arg.Title,
		arg.Description,
		arg.Visibility,
		arg.Settings,
		arg.StartTime,
		arg.EndTime,
		arg.OwnerID,
	)
	return err
}

const updateContestMemberRole = `-- name: UpdateContestMemberRole :exec
UPDATE contest_members
SET role = $3
WHERE contest_id = $1 AND user_id = $2
`

type UpdateContestMemberRoleParams struct {
	ContestID uuid.UUID          `json:"contest_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      models.ContestRole `json:"role"`
}

func (q *Queries) UpdateContestMemberRole(ctx context.Context, arg UpdateContestMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateContestMemberRole, arg.ContestID, arg.UserID, arg.Role)
	return err
}

const updateContestProblemOrdinal = `-- name: UpdateContestProblemOrdinal :exec
UPDATE contest_problems
SET ordinal = $3
WHERE contest_id = $1 AND problem_id = $2
`

type UpdateContestProblemOrdinalParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	ProblemID uuid.UUID `json:"problem_id"`
	Ordinal   int32     `json:"ordinal"`
}

func (q *Queries) UpdateContestProblemOrdinal(ctx context.Context, arg UpdateContestProblemOrdinalParams) error {
	_, err := q.db.Exec(ctx, updateContestProblemOrdinal, arg.ContestID, arg.ProblemID, arg.Ordinal)
	return err
}

const updateContestProblemPackage = `-- name: UpdateContestProblemPackage :exec
UPDATE contest_problems
SET package_id = $3
WHERE contest_id = $1 AND problem_id = $2
`

type UpdateContestProblemPackageParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	ProblemID uuid.UUID `json:"problem_id"`
	PackageID uuid.UUID `json:"package_id"`
}

func (q *Queries) UpdateContestProblemPackage(ctx context.Context, arg UpdateContestProblemPackageParams) error {
	_, err := q.db.Exec(ctx, updateContestProblemPackage, arg.ContestID, arg.ProblemID, arg.PackageID)
	return err
}

const upsertContestProblemResult = `-- name: UpsertContestProblemResult :exec

INSERT INTO contest_problem_results (contest_id, user_id, problem_id, solved, failed_attempts, first_ac_time, time_minutes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (contest_id, user_id, problem_id)
DO UPDATE SET
    solved = EXCLUDED.solved,
    failed_attempts = EXCLUDED.failed_attempts,
    first_ac_time = EXCLUDED.first_ac_time,
    time_minutes = EXCLUDED.time_minutes,
    updated_at = NOW()
`

type UpsertContestProblemResultParams struct {
	ContestID      uuid.UUID          `json:"contest_id"`
	UserID         uuid.UUID          `json:"user_id"`
	ProblemID      uuid.UUID          `json:"problem_id"`
	Solved         bool               `json:"solved"`
	FailedAttempts int32              `json:"failed_attempts"`
	FirstAcTime    pgtype.Timestamptz `json:"first_ac_time"`
	TimeMinutes    *int32             `json:"time_minutes"`
}

// Contest Standings (Scoreboard)
func (q *Queries) UpsertContestProblemResult(ctx context.Context, arg UpsertContestProblemResultParams) error {
	_, err := q.db.Exec(ctx, upsertContestProblemResult,
		arg.ContestID,
		arg.UserID,
		arg.ProblemID,
		arg.Solved,
		arg.FailedAttempts,
		arg.FirstAcTime,
		arg.TimeMinutes,
	)
	return err
}
