// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: contest_clarifications.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const answerContestClarification = `-- name: AnswerContestClarification :one
UPDATE contest_clarifications
SET 
    answer = $1,
    answered_by = $2,
    status = 'answered',
    answered_at = NOW(),
    updated_at = NOW()
WHERE id = $3 AND contest_id = $4
RETURNING id, contest_id, problem_id, user_id, question, answer, answered_by, status, created_at, answered_at, updated_at
`

type AnswerContestClarificationParams struct {
	Answer     *string     `json:"answer"`
	AnsweredBy pgtype.UUID `json:"answered_by"`
	ID         uuid.UUID   `json:"id"`
	ContestID  uuid.UUID   `json:"contest_id"`
}

func (q *Queries) AnswerContestClarification(ctx context.Context, arg AnswerContestClarificationParams) (ContestClarification, error) {
	row := q.db.QueryRow(ctx, answerContestClarification,
		arg.Answer,
		arg.AnsweredBy,
		arg.ID,
		arg.ContestID,
	)
	var i ContestClarification
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ProblemID,
		&i.UserID,
		&i.Question,
		&i.Answer,
		&i.AnsweredBy,
		&i.Status,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countContestClarificationsForModerator = `-- name: CountContestClarificationsForModerator :one
SELECT COUNT(*) FROM contest_clarifications
WHERE contest_id = $1
  AND ($2::uuid IS NULL OR problem_id = $2::uuid)
  AND ($3::text IS NULL OR $3::text = '' OR status = $3::text)
`

type CountContestClarificationsForModeratorParams struct {
	ContestID uuid.UUID   `json:"contest_id"`
	ProblemID pgtype.UUID `json:"problem_id"`
	Status    *string     `json:"status"`
}

func (q *Queries) CountContestClarificationsForModerator(ctx context.Context, arg CountContestClarificationsForModeratorParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContestClarificationsForModerator, arg.ContestID, arg.ProblemID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContestClarificationsForUser = `-- name: CountContestClarificationsForUser :one
SELECT COUNT(*) FROM contest_clarifications
WHERE contest_id = $1 AND user_id = $2
`

type CountContestClarificationsForUserParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) CountContestClarificationsForUser(ctx context.Context, arg CountContestClarificationsForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContestClarificationsForUser, arg.ContestID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContestClarification = `-- name: CreateContestClarification :one
INSERT INTO contest_clarifications (
    id,
    contest_id,
    problem_id,
    user_id,
    question,
    status,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    'pending',
    NOW(),
    NOW()
) RETURNING id, contest_id, problem_id, user_id, question, answer, answered_by, status, created_at, answered_at, updated_at
`

type CreateContestClarificationParams struct {
	ID        uuid.UUID   `json:"id"`
	ContestID uuid.UUID   `json:"contest_id"`
	ProblemID pgtype.UUID `json:"problem_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Question  string      `json:"question"`
}

func (q *Queries) CreateContestClarification(ctx context.Context, arg CreateContestClarificationParams) (ContestClarification, error) {
	row := q.db.QueryRow(ctx, createContestClarification,
		arg.ID,
		arg.ContestID,
		arg.ProblemID,
		arg.UserID,
		arg.Question,
	)
	var i ContestClarification
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ProblemID,
		&i.UserID,
		&i.Question,
		&i.Answer,
		&i.AnsweredBy,
		&i.Status,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContestClarificationByID = `-- name: GetContestClarificationByID :one
SELECT 
    cc.id, cc.contest_id, cc.problem_id, cc.user_id, cc.question, cc.answer, cc.answered_by, cc.status, cc.created_at, cc.answered_at, cc.updated_at,
    u.username AS username,
    au.username AS answered_by_username,
    p.title AS problem_title,
    cp.ordinal AS problem_ordinal
FROM contest_clarifications cc
JOIN users u ON cc.user_id = u.id
LEFT JOIN users au ON cc.answered_by = au.id
LEFT JOIN problems p ON cc.problem_id = p.id
LEFT JOIN contest_problems cp ON cp.contest_id = cc.contest_id AND cp.problem_id = cc.problem_id
WHERE cc.id = $1
`

type GetContestClarificationByIDRow struct {
	ID                 uuid.UUID          `json:"id"`
	ContestID          uuid.UUID          `json:"contest_id"`
	ProblemID          pgtype.UUID        `json:"problem_id"`
	UserID             uuid.UUID          `json:"user_id"`
	Question           string             `json:"question"`
	Answer             *string            `json:"answer"`
	AnsweredBy         pgtype.UUID        `json:"answered_by"`
	Status             string             `json:"status"`
	CreatedAt          time.Time          `json:"created_at"`
	AnsweredAt         pgtype.Timestamptz `json:"answered_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	Username           string             `json:"username"`
	AnsweredByUsername *string            `json:"answered_by_username"`
	ProblemTitle       *string            `json:"problem_title"`
	ProblemOrdinal     *int32             `json:"problem_ordinal"`
}

func (q *Queries) GetContestClarificationByID(ctx context.Context, id uuid.UUID) (GetContestClarificationByIDRow, error) {
	row := q.db.QueryRow(ctx, getContestClarificationByID, id)
	var i GetContestClarificationByIDRow
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.ProblemID,
		&i.UserID,
		&i.Question,
		&i.Answer,
		&i.AnsweredBy,
		&i.Status,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.UpdatedAt,
		&i.Username,
		&i.AnsweredByUsername,
		&i.ProblemTitle,
		&i.ProblemOrdinal,
	)
	return i, err
}

const listContestClarificationsForModerator = `-- name: ListContestClarificationsForModerator :many
SELECT 
    cc.id, cc.contest_id, cc.problem_id, cc.user_id, cc.question, cc.answer, cc.answered_by, cc.status, cc.created_at, cc.answered_at, cc.updated_at,
    u.username AS username,
    au.username AS answered_by_username,
    p.title AS problem_title,
    cp.ordinal AS problem_ordinal
FROM contest_clarifications cc
JOIN users u ON cc.user_id = u.id
LEFT JOIN users au ON cc.answered_by = au.id
LEFT JOIN problems p ON cc.problem_id = p.id
LEFT JOIN contest_problems cp ON cp.contest_id = cc.contest_id AND cp.problem_id = cc.problem_id
WHERE cc.contest_id = $1
  AND ($4::uuid IS NULL OR cc.problem_id = $4::uuid)
  AND ($5::text IS NULL OR $5::text = '' OR cc.status = $5::text)
ORDER BY cc.created_at DESC
LIMIT $2 OFFSET $3
`

type ListContestClarificationsForModeratorParams struct {
	ContestID uuid.UUID   `json:"contest_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
	ProblemID pgtype.UUID `json:"problem_id"`
	Status    *string     `json:"status"`
}

type ListContestClarificationsForModeratorRow struct {
	ID                 uuid.UUID          `json:"id"`
	ContestID          uuid.UUID          `json:"contest_id"`
	ProblemID          pgtype.UUID        `json:"problem_id"`
	UserID             uuid.UUID          `json:"user_id"`
	Question           string             `json:"question"`
	Answer             *string            `json:"answer"`
	AnsweredBy         pgtype.UUID        `json:"answered_by"`
	Status             string             `json:"status"`
	CreatedAt          time.Time          `json:"created_at"`
	AnsweredAt         pgtype.Timestamptz `json:"answered_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	Username           string             `json:"username"`
	AnsweredByUsername *string            `json:"answered_by_username"`
	ProblemTitle       *string            `json:"problem_title"`
	ProblemOrdinal     *int32             `json:"problem_ordinal"`
}

func (q *Queries) ListContestClarificationsForModerator(ctx context.Context, arg ListContestClarificationsForModeratorParams) ([]ListContestClarificationsForModeratorRow, error) {
	rows, err := q.db.Query(ctx, listContestClarificationsForModerator,
		arg.ContestID,
		arg.Limit,
		arg.Offset,
		arg.ProblemID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContestClarificationsForModeratorRow{}
	for rows.Next() {
		var i ListContestClarificationsForModeratorRow
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.ProblemID,
			&i.UserID,
			&i.Question,
			&i.Answer,
			&i.AnsweredBy,
			&i.Status,
			&i.CreatedAt,
			&i.AnsweredAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AnsweredByUsername,
			&i.ProblemTitle,
			&i.ProblemOrdinal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestClarificationsForUser = `-- name: ListContestClarificationsForUser :many
SELECT 
    cc.id, cc.contest_id, cc.problem_id, cc.user_id, cc.question, cc.answer, cc.answered_by, cc.status, cc.created_at, cc.answered_at, cc.updated_at,
    u.username AS username,
    au.username AS answered_by_username,
    p.title AS problem_title,
    cp.ordinal AS problem_ordinal
FROM contest_clarifications cc
JOIN users u ON cc.user_id = u.id
LEFT JOIN users au ON cc.answered_by = au.id
LEFT JOIN problems p ON cc.problem_id = p.id
LEFT JOIN contest_problems cp ON cp.contest_id = cc.contest_id AND cp.problem_id = cc.problem_id
WHERE cc.contest_id = $1 AND cc.user_id = $2
ORDER BY cc.created_at DESC
LIMIT $3 OFFSET $4
`

type ListContestClarificationsForUserParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	UserID    uuid.UUID `json:"user_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListContestClarificationsForUserRow struct {
	ID                 uuid.UUID          `json:"id"`
	ContestID          uuid.UUID          `json:"contest_id"`
	ProblemID          pgtype.UUID        `json:"problem_id"`
	UserID             uuid.UUID          `json:"user_id"`
	Question           string             `json:"question"`
	Answer             *string            `json:"answer"`
	AnsweredBy         pgtype.UUID        `json:"answered_by"`
	Status             string             `json:"status"`
	CreatedAt          time.Time          `json:"created_at"`
	AnsweredAt         pgtype.Timestamptz `json:"answered_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	Username           string             `json:"username"`
	AnsweredByUsername *string            `json:"answered_by_username"`
	ProblemTitle       *string            `json:"problem_title"`
	ProblemOrdinal     *int32             `json:"problem_ordinal"`
}

func (q *Queries) ListContestClarificationsForUser(ctx context.Context, arg ListContestClarificationsForUserParams) ([]ListContestClarificationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listContestClarificationsForUser,
		arg.ContestID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContestClarificationsForUserRow{}
	for rows.Next() {
		var i ListContestClarificationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.ProblemID,
			&i.UserID,
			&i.Question,
			&i.Answer,
			&i.AnsweredBy,
			&i.Status,
			&i.CreatedAt,
			&i.AnsweredAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AnsweredByUsername,
			&i.ProblemTitle,
			&i.ProblemOrdinal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
