// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/gate149/gate/backend/internal/domain/models"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ContestRole string

const (
	ContestRoleOwner       ContestRole = "owner"
	ContestRoleModerator   ContestRole = "moderator"
	ContestRoleParticipant ContestRole = "participant"
)

func (e *ContestRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContestRole(s)
	case string:
		*e = ContestRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ContestRole: %T", src)
	}
	return nil
}

type NullContestRole struct {
	ContestRole ContestRole `json:"contest_role"`
	Valid       bool        `json:"valid"` // Valid is true if ContestRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContestRole) Scan(value interface{}) error {
	if value == nil {
		ns.ContestRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContestRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContestRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContestRole), nil
}

type ContestVisibility string

const (
	ContestVisibilityPrivate  ContestVisibility = "private"
	ContestVisibilityPublic   ContestVisibility = "public"
	ContestVisibilityUnlisted ContestVisibility = "unlisted"
)

func (e *ContestVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContestVisibility(s)
	case string:
		*e = ContestVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for ContestVisibility: %T", src)
	}
	return nil
}

type NullContestVisibility struct {
	ContestVisibility ContestVisibility `json:"contest_visibility"`
	Valid             bool              `json:"valid"` // Valid is true if ContestVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContestVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.ContestVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContestVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContestVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContestVisibility), nil
}

type OrganizationRole string

const (
	OrganizationRoleOwner  OrganizationRole = "owner"
	OrganizationRoleAdmin  OrganizationRole = "admin"
	OrganizationRoleMember OrganizationRole = "member"
)

func (e *OrganizationRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrganizationRole(s)
	case string:
		*e = OrganizationRole(s)
	default:
		return fmt.Errorf("unsupported scan type for OrganizationRole: %T", src)
	}
	return nil
}

type NullOrganizationRole struct {
	OrganizationRole OrganizationRole `json:"organization_role"`
	Valid            bool             `json:"valid"` // Valid is true if OrganizationRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrganizationRole) Scan(value interface{}) error {
	if value == nil {
		ns.OrganizationRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrganizationRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrganizationRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrganizationRole), nil
}

type OutboxEventStatus string

const (
	OutboxEventStatusPending    OutboxEventStatus = "pending"
	OutboxEventStatusProcessing OutboxEventStatus = "processing"
	OutboxEventStatusCompleted  OutboxEventStatus = "completed"
	OutboxEventStatusFailed     OutboxEventStatus = "failed"
)

func (e *OutboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxEventStatus(s)
	case string:
		*e = OutboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxEventStatus: %T", src)
	}
	return nil
}

type NullOutboxEventStatus struct {
	OutboxEventStatus OutboxEventStatus `json:"outbox_event_status"`
	Valid             bool              `json:"valid"` // Valid is true if OutboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxEventStatus), nil
}

type PackageStatus string

const (
	PackageStatusPending  PackageStatus = "pending"
	PackageStatusBuilding PackageStatus = "building"
	PackageStatusReady    PackageStatus = "ready"
	PackageStatusFailed   PackageStatus = "failed"
)

func (e *PackageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PackageStatus(s)
	case string:
		*e = PackageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PackageStatus: %T", src)
	}
	return nil
}

type NullPackageStatus struct {
	PackageStatus PackageStatus `json:"package_status"`
	Valid         bool          `json:"valid"` // Valid is true if PackageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPackageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PackageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PackageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPackageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PackageStatus), nil
}

type ProblemPermission string

const (
	ProblemPermissionAdmin ProblemPermission = "admin"
	ProblemPermissionWrite ProblemPermission = "write"
	ProblemPermissionRead  ProblemPermission = "read"
)

func (e *ProblemPermission) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProblemPermission(s)
	case string:
		*e = ProblemPermission(s)
	default:
		return fmt.Errorf("unsupported scan type for ProblemPermission: %T", src)
	}
	return nil
}

type NullProblemPermission struct {
	ProblemPermission ProblemPermission `json:"problem_permission"`
	Valid             bool              `json:"valid"` // Valid is true if ProblemPermission is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProblemPermission) Scan(value interface{}) error {
	if value == nil {
		ns.ProblemPermission, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProblemPermission.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProblemPermission) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProblemPermission), nil
}

type ProblemRole string

const (
	ProblemRoleOwner     ProblemRole = "owner"
	ProblemRoleModerator ProblemRole = "moderator"
	ProblemRoleViewer    ProblemRole = "viewer"
)

func (e *ProblemRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProblemRole(s)
	case string:
		*e = ProblemRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ProblemRole: %T", src)
	}
	return nil
}

type NullProblemRole struct {
	ProblemRole ProblemRole `json:"problem_role"`
	Valid       bool        `json:"valid"` // Valid is true if ProblemRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProblemRole) Scan(value interface{}) error {
	if value == nil {
		ns.ProblemRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProblemRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProblemRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProblemRole), nil
}

type ProblemVisibility string

const (
	ProblemVisibilityPrivate  ProblemVisibility = "private"
	ProblemVisibilityPublic   ProblemVisibility = "public"
	ProblemVisibilityUnlisted ProblemVisibility = "unlisted"
)

func (e *ProblemVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProblemVisibility(s)
	case string:
		*e = ProblemVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for ProblemVisibility: %T", src)
	}
	return nil
}

type NullProblemVisibility struct {
	ProblemVisibility ProblemVisibility `json:"problem_visibility"`
	Valid             bool              `json:"valid"` // Valid is true if ProblemVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProblemVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.ProblemVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProblemVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProblemVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProblemVisibility), nil
}

type TeamRole string

const (
	TeamRoleMaintainer TeamRole = "maintainer"
	TeamRoleMember     TeamRole = "member"
)

func (e *TeamRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TeamRole(s)
	case string:
		*e = TeamRole(s)
	default:
		return fmt.Errorf("unsupported scan type for TeamRole: %T", src)
	}
	return nil
}

type NullTeamRole struct {
	TeamRole TeamRole `json:"team_role"`
	Valid    bool     `json:"valid"` // Valid is true if TeamRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeamRole) Scan(value interface{}) error {
	if value == nil {
		ns.TeamRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TeamRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeamRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TeamRole), nil
}

type UserRole string

const (
	UserRoleUser  UserRole = "user"
	UserRoleAdmin UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Contest struct {
	ID             uuid.UUID                `json:"id"`
	OrganizationID uuid.UUID                `json:"organization_id"`
	OwnerID        pgtype.UUID              `json:"owner_id"`
	Visibility     models.ContestVisibility `json:"visibility"`
	Titles         []byte                   `json:"titles"`
	ShortName      string                   `json:"short_name"`
	Description    string                   `json:"description"`
	Settings       []byte                   `json:"settings"`
	AccessPolicy   []byte                   `json:"access_policy"`
	StartTime      pgtype.Timestamptz       `json:"start_time"`
	EndTime        pgtype.Timestamptz       `json:"end_time"`
	CreatedAt      time.Time                `json:"created_at"`
	UpdatedAt      time.Time                `json:"updated_at"`
}

type ContestMember struct {
	ContestID uuid.UUID          `json:"contest_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      models.ContestRole `json:"role"`
	CreatedAt time.Time          `json:"created_at"`
}

type ContestProblem struct {
	ContestID uuid.UUID `json:"contest_id"`
	ProblemID uuid.UUID `json:"problem_id"`
	PackageID uuid.UUID `json:"package_id"`
	Ordinal   int32     `json:"ordinal"`
	CreatedAt time.Time `json:"created_at"`
}

type ContestTeam struct {
	ContestID uuid.UUID          `json:"contest_id"`
	TeamID    uuid.UUID          `json:"team_id"`
	Role      models.ContestRole `json:"role"`
	CreatedAt time.Time          `json:"created_at"`
}

type Organization struct {
	ID          uuid.UUID `json:"id"`
	Login       string    `json:"login"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	AvatarUrl   *string   `json:"avatar_url"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type OrganizationMember struct {
	OrganizationID uuid.UUID        `json:"organization_id"`
	UserID         uuid.UUID        `json:"user_id"`
	Role           OrganizationRole `json:"role"`
	CreatedAt      time.Time        `json:"created_at"`
}

type OutboxEvent struct {
	ID           uuid.UUID                `json:"id"`
	AggregateID  uuid.UUID                `json:"aggregate_id"`
	EventType    models.OutboxEventType   `json:"event_type"`
	Payload      []byte                   `json:"payload"`
	Status       models.OutboxEventStatus `json:"status"`
	RetryCount   int32                    `json:"retry_count"`
	ErrorMessage *string                  `json:"error_message"`
	CreatedAt    time.Time                `json:"created_at"`
	ProcessedAt  *time.Time               `json:"processed_at"`
	LockedAt     *time.Time               `json:"locked_at"`
	DeadlineAt   *time.Time               `json:"deadline_at"`
}

type Problem struct {
	ID             uuid.UUID         `json:"id"`
	OrganizationID uuid.UUID         `json:"organization_id"`
	OwnerID        pgtype.UUID       `json:"owner_id"`
	Visibility     ProblemVisibility `json:"visibility"`
	Titles         []byte            `json:"titles"`
	ShortName      string            `json:"short_name"`
	GitCommitHash  *string           `json:"git_commit_hash"`
	CreatedAt      time.Time         `json:"created_at"`
	UpdatedAt      time.Time         `json:"updated_at"`
}

type ProblemMember struct {
	ProblemID uuid.UUID   `json:"problem_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Role      ProblemRole `json:"role"`
	CreatedAt time.Time   `json:"created_at"`
}

type ProblemPackage struct {
	ID             uuid.UUID          `json:"id"`
	ProblemID      uuid.UUID          `json:"problem_id"`
	OrganizationID uuid.UUID          `json:"organization_id"`
	GitCommitHash  string             `json:"git_commit_hash"`
	PackageHash    string             `json:"package_hash"`
	Url            *string            `json:"url"`
	Status         PackageStatus      `json:"status"`
	BuildLog       *string            `json:"build_log"`
	CreatedAt      time.Time          `json:"created_at"`
	CompiledAt     pgtype.Timestamptz `json:"compiled_at"`
}

type ProblemTeam struct {
	ProblemID  uuid.UUID         `json:"problem_id"`
	TeamID     uuid.UUID         `json:"team_id"`
	Permission ProblemPermission `json:"permission"`
	CreatedAt  time.Time         `json:"created_at"`
}

type Submission struct {
	ID         uuid.UUID           `json:"id"`
	ContestID  pgtype.UUID         `json:"contest_id"`
	ProblemID  pgtype.UUID         `json:"problem_id"`
	OwnerID    pgtype.UUID         `json:"owner_id"`
	Source     string              `json:"source"`
	Language   models.LanguageName `json:"language"`
	State      models.State        `json:"state"`
	Score      int32               `json:"score"`
	Penalty    int32               `json:"penalty"`
	TimeStat   int32               `json:"time_stat"`
	MemoryStat int32               `json:"memory_stat"`
	CreatedAt  time.Time           `json:"created_at"`
	UpdatedAt  time.Time           `json:"updated_at"`
}

type Team struct {
	ID             uuid.UUID   `json:"id"`
	OrganizationID uuid.UUID   `json:"organization_id"`
	Name           string      `json:"name"`
	Slug           string      `json:"slug"`
	Description    string      `json:"description"`
	Privacy        string      `json:"privacy"`
	ParentTeamID   pgtype.UUID `json:"parent_team_id"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type TeamMember struct {
	TeamID    uuid.UUID `json:"team_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      TeamRole  `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Username  string    `json:"username"`
	Role      UserRole  `json:"role"`
	KratosID  uuid.UUID `json:"kratos_id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	Surname   string    `json:"surname"`
	Bio       string    `json:"bio"`
	AvatarUrl *string   `json:"avatar_url"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
