// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: problems.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProblemMember = `-- name: AddProblemMember :exec

INSERT INTO problem_members (problem_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddProblemMemberParams struct {
	ProblemID uuid.UUID   `json:"problem_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Role      ProblemRole `json:"role"`
}

// Problem Members (direct access control)
func (q *Queries) AddProblemMember(ctx context.Context, arg AddProblemMemberParams) error {
	_, err := q.db.Exec(ctx, addProblemMember, arg.ProblemID, arg.UserID, arg.Role)
	return err
}

const checkUserHasProblemAccess = `-- name: CheckUserHasProblemAccess :one

SELECT user_has_problem_access($1, $2) as has_access
`

type CheckUserHasProblemAccessParams struct {
	PUserID    uuid.UUID `json:"p_user_id"`
	PProblemID uuid.UUID `json:"p_problem_id"`
}

// Access check helpers
func (q *Queries) CheckUserHasProblemAccess(ctx context.Context, arg CheckUserHasProblemAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserHasProblemAccess, arg.PUserID, arg.PProblemID)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}

const countAllProblems = `-- name: CountAllProblems :one
SELECT COUNT(*) FROM problems p
WHERE ($1::text = '' OR p.title ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR p.visibility = $2::problem_visibility)
`

type CountAllProblemsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

func (q *Queries) CountAllProblems(ctx context.Context, arg CountAllProblemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllProblems, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProblems = `-- name: CountProblems :one
SELECT COUNT(*) FROM problems
WHERE organization_id = $1
  AND ($2::text = '' OR title ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR visibility = $3::problem_visibility)
`

type CountProblemsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Column2        string    `json:"column_2"`
	Column3        string    `json:"column_3"`
}

func (q *Queries) CountProblems(ctx context.Context, arg CountProblemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProblems, arg.OrganizationID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProblem = `-- name: CreateProblem :one

INSERT INTO problems (id, organization_id, owner_id, visibility, title, short_name)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, owner_id, visibility, title, short_name, time_limit_ms, memory_limit_mb, manifest, created_at, updated_at
`

type CreateProblemParams struct {
	ID             uuid.UUID         `json:"id"`
	OrganizationID uuid.UUID         `json:"organization_id"`
	OwnerID        pgtype.UUID       `json:"owner_id"`
	Visibility     ProblemVisibility `json:"visibility"`
	Title          string            `json:"title"`
	ShortName      string            `json:"short_name"`
}

// Problems queries (new schema with Organizations)
func (q *Queries) CreateProblem(ctx context.Context, arg CreateProblemParams) (Problem, error) {
	row := q.db.QueryRow(ctx, createProblem,
		arg.ID,
		arg.OrganizationID,
		arg.OwnerID,
		arg.Visibility,
		arg.Title,
		arg.ShortName,
	)
	var i Problem
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.Visibility,
		&i.Title,
		&i.ShortName,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
		&i.Manifest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProblem = `-- name: DeleteProblem :exec
DELETE FROM problems WHERE id = $1
`

func (q *Queries) DeleteProblem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProblem, id)
	return err
}

const getProblemByID = `-- name: GetProblemByID :one
SELECT id, organization_id, owner_id, visibility, title, short_name, created_at, updated_at, time_limit_ms, memory_limit_mb FROM problems WHERE id = $1
`

type GetProblemByIDRow struct {
	ID             uuid.UUID         `json:"id"`
	OrganizationID uuid.UUID         `json:"organization_id"`
	OwnerID        pgtype.UUID       `json:"owner_id"`
	Visibility     ProblemVisibility `json:"visibility"`
	Title          string            `json:"title"`
	ShortName      string            `json:"short_name"`
	CreatedAt      time.Time         `json:"created_at"`
	UpdatedAt      time.Time         `json:"updated_at"`
	TimeLimitMs    int32             `json:"time_limit_ms"`
	MemoryLimitMb  int32             `json:"memory_limit_mb"`
}

func (q *Queries) GetProblemByID(ctx context.Context, id uuid.UUID) (GetProblemByIDRow, error) {
	row := q.db.QueryRow(ctx, getProblemByID, id)
	var i GetProblemByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.Visibility,
		&i.Title,
		&i.ShortName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
	)
	return i, err
}

const getProblemByShortName = `-- name: GetProblemByShortName :one
SELECT id, organization_id, owner_id, visibility, title, short_name, created_at, updated_at, time_limit_ms, memory_limit_mb FROM problems
WHERE organization_id = $1 AND short_name = $2
`

type GetProblemByShortNameParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ShortName      string    `json:"short_name"`
}

type GetProblemByShortNameRow struct {
	ID             uuid.UUID         `json:"id"`
	OrganizationID uuid.UUID         `json:"organization_id"`
	OwnerID        pgtype.UUID       `json:"owner_id"`
	Visibility     ProblemVisibility `json:"visibility"`
	Title          string            `json:"title"`
	ShortName      string            `json:"short_name"`
	CreatedAt      time.Time         `json:"created_at"`
	UpdatedAt      time.Time         `json:"updated_at"`
	TimeLimitMs    int32             `json:"time_limit_ms"`
	MemoryLimitMb  int32             `json:"memory_limit_mb"`
}

func (q *Queries) GetProblemByShortName(ctx context.Context, arg GetProblemByShortNameParams) (GetProblemByShortNameRow, error) {
	row := q.db.QueryRow(ctx, getProblemByShortName, arg.OrganizationID, arg.ShortName)
	var i GetProblemByShortNameRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerID,
		&i.Visibility,
		&i.Title,
		&i.ShortName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
	)
	return i, err
}

const getProblemManifest = `-- name: GetProblemManifest :one
SELECT manifest FROM problems WHERE id = $1
`

func (q *Queries) GetProblemManifest(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getProblemManifest, id)
	var manifest []byte
	err := row.Scan(&manifest)
	return manifest, err
}

const getProblemMember = `-- name: GetProblemMember :one
SELECT problem_id, user_id, role, created_at FROM problem_members
WHERE problem_id = $1 AND user_id = $2
`

type GetProblemMemberParams struct {
	ProblemID uuid.UUID `json:"problem_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetProblemMember(ctx context.Context, arg GetProblemMemberParams) (ProblemMember, error) {
	row := q.db.QueryRow(ctx, getProblemMember, arg.ProblemID, arg.UserID)
	var i ProblemMember
	err := row.Scan(
		&i.ProblemID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listAllProblems = `-- name: ListAllProblems :many
SELECT p.id, p.organization_id, p.owner_id, p.visibility, p.title, p.short_name, p.created_at, p.updated_at, p.time_limit_ms, p.memory_limit_mb FROM problems p
WHERE ($1::text = '' OR p.title ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR p.visibility = $2::problem_visibility)
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $4
`

type ListAllProblemsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListAllProblemsRow struct {
	ID             uuid.UUID         `json:"id"`
	OrganizationID uuid.UUID         `json:"organization_id"`
	OwnerID        pgtype.UUID       `json:"owner_id"`
	Visibility     ProblemVisibility `json:"visibility"`
	Title          string            `json:"title"`
	ShortName      string            `json:"short_name"`
	CreatedAt      time.Time         `json:"created_at"`
	UpdatedAt      time.Time         `json:"updated_at"`
	TimeLimitMs    int32             `json:"time_limit_ms"`
	MemoryLimitMb  int32             `json:"memory_limit_mb"`
}

func (q *Queries) ListAllProblems(ctx context.Context, arg ListAllProblemsParams) ([]ListAllProblemsRow, error) {
	rows, err := q.db.Query(ctx, listAllProblems,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllProblemsRow{}
	for rows.Next() {
		var i ListAllProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OwnerID,
			&i.Visibility,
			&i.Title,
			&i.ShortName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TimeLimitMs,
			&i.MemoryLimitMb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblemMembers = `-- name: ListProblemMembers :many
SELECT pm.problem_id, pm.user_id, pm.role, pm.created_at, u.username, u.email
FROM problem_members pm
JOIN users u ON pm.user_id = u.id
WHERE pm.problem_id = $1
ORDER BY pm.created_at
`

type ListProblemMembersRow struct {
	ProblemID uuid.UUID   `json:"problem_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Role      ProblemRole `json:"role"`
	CreatedAt time.Time   `json:"created_at"`
	Username  string      `json:"username"`
	Email     string      `json:"email"`
}

func (q *Queries) ListProblemMembers(ctx context.Context, problemID uuid.UUID) ([]ListProblemMembersRow, error) {
	rows, err := q.db.Query(ctx, listProblemMembers, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProblemMembersRow{}
	for rows.Next() {
		var i ListProblemMembersRow
		if err := rows.Scan(
			&i.ProblemID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProblems = `-- name: ListProblems :many
SELECT id, organization_id, owner_id, visibility, title, short_name, created_at, updated_at, time_limit_ms, memory_limit_mb FROM problems
WHERE organization_id = $1
  AND ($2::text = '' OR title ILIKE '%' || $2 || '%')
  AND ($3::text = '' OR visibility = $3::problem_visibility)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListProblemsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Column2        string    `json:"column_2"`
	Column3        string    `json:"column_3"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

type ListProblemsRow struct {
	ID             uuid.UUID         `json:"id"`
	OrganizationID uuid.UUID         `json:"organization_id"`
	OwnerID        pgtype.UUID       `json:"owner_id"`
	Visibility     ProblemVisibility `json:"visibility"`
	Title          string            `json:"title"`
	ShortName      string            `json:"short_name"`
	CreatedAt      time.Time         `json:"created_at"`
	UpdatedAt      time.Time         `json:"updated_at"`
	TimeLimitMs    int32             `json:"time_limit_ms"`
	MemoryLimitMb  int32             `json:"memory_limit_mb"`
}

func (q *Queries) ListProblems(ctx context.Context, arg ListProblemsParams) ([]ListProblemsRow, error) {
	rows, err := q.db.Query(ctx, listProblems,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProblemsRow{}
	for rows.Next() {
		var i ListProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OwnerID,
			&i.Visibility,
			&i.Title,
			&i.ShortName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TimeLimitMs,
			&i.MemoryLimitMb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAccessibleProblems = `-- name: ListUserAccessibleProblems :many
SELECT p.id, p.organization_id, p.owner_id, p.visibility, p.title, p.short_name, p.created_at, p.updated_at, p.time_limit_ms, p.memory_limit_mb FROM problems p
WHERE user_has_problem_access($1, p.id)
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserAccessibleProblemsParams struct {
	PUserID uuid.UUID `json:"p_user_id"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

type ListUserAccessibleProblemsRow struct {
	ID             uuid.UUID         `json:"id"`
	OrganizationID uuid.UUID         `json:"organization_id"`
	OwnerID        pgtype.UUID       `json:"owner_id"`
	Visibility     ProblemVisibility `json:"visibility"`
	Title          string            `json:"title"`
	ShortName      string            `json:"short_name"`
	CreatedAt      time.Time         `json:"created_at"`
	UpdatedAt      time.Time         `json:"updated_at"`
	TimeLimitMs    int32             `json:"time_limit_ms"`
	MemoryLimitMb  int32             `json:"memory_limit_mb"`
}

func (q *Queries) ListUserAccessibleProblems(ctx context.Context, arg ListUserAccessibleProblemsParams) ([]ListUserAccessibleProblemsRow, error) {
	rows, err := q.db.Query(ctx, listUserAccessibleProblems, arg.PUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAccessibleProblemsRow{}
	for rows.Next() {
		var i ListUserAccessibleProblemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OwnerID,
			&i.Visibility,
			&i.Title,
			&i.ShortName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TimeLimitMs,
			&i.MemoryLimitMb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProblemMember = `-- name: RemoveProblemMember :exec
DELETE FROM problem_members
WHERE problem_id = $1 AND user_id = $2
`

type RemoveProblemMemberParams struct {
	ProblemID uuid.UUID `json:"problem_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveProblemMember(ctx context.Context, arg RemoveProblemMemberParams) error {
	_, err := q.db.Exec(ctx, removeProblemMember, arg.ProblemID, arg.UserID)
	return err
}

const updateProblem = `-- name: UpdateProblem :exec
UPDATE problems
SET title = COALESCE($2, title),
    visibility = COALESCE($3, visibility),
    owner_id = COALESCE($4, owner_id)
WHERE id = $1
`

type UpdateProblemParams struct {
	ID         uuid.UUID             `json:"id"`
	Title      *string               `json:"title"`
	Visibility NullProblemVisibility `json:"visibility"`
	OwnerID    pgtype.UUID           `json:"owner_id"`
}

func (q *Queries) UpdateProblem(ctx context.Context, arg UpdateProblemParams) error {
	_, err := q.db.Exec(ctx, updateProblem,
		arg.ID,
		arg.Title,
		arg.Visibility,
		arg.OwnerID,
	)
	return err
}

const updateProblemLimits = `-- name: UpdateProblemLimits :exec

UPDATE problems
SET time_limit_ms = $2, memory_limit_mb = $3
WHERE id = $1
`

type UpdateProblemLimitsParams struct {
	ID            uuid.UUID `json:"id"`
	TimeLimitMs   int32     `json:"time_limit_ms"`
	MemoryLimitMb int32     `json:"memory_limit_mb"`
}

// Workshop integration queries
func (q *Queries) UpdateProblemLimits(ctx context.Context, arg UpdateProblemLimitsParams) error {
	_, err := q.db.Exec(ctx, updateProblemLimits, arg.ID, arg.TimeLimitMs, arg.MemoryLimitMb)
	return err
}

const updateProblemManifest = `-- name: UpdateProblemManifest :exec
UPDATE problems SET manifest = $2 WHERE id = $1
`

type UpdateProblemManifestParams struct {
	ID       uuid.UUID `json:"id"`
	Manifest []byte    `json:"manifest"`
}

func (q *Queries) UpdateProblemManifest(ctx context.Context, arg UpdateProblemManifestParams) error {
	_, err := q.db.Exec(ctx, updateProblemManifest, arg.ID, arg.Manifest)
	return err
}

const updateProblemMemberRole = `-- name: UpdateProblemMemberRole :exec
UPDATE problem_members
SET role = $3
WHERE problem_id = $1 AND user_id = $2
`

type UpdateProblemMemberRoleParams struct {
	ProblemID uuid.UUID   `json:"problem_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Role      ProblemRole `json:"role"`
}

func (q *Queries) UpdateProblemMemberRole(ctx context.Context, arg UpdateProblemMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateProblemMemberRole, arg.ProblemID, arg.UserID, arg.Role)
	return err
}
