// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: problem_packages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createProblemPackage = `-- name: CreateProblemPackage :one

INSERT INTO problem_packages (id, problem_id, organization_id, package_hash, status, version)
VALUES ($1, $2, $3, $4, $5, (SELECT COALESCE(MAX(version), 0) + 1 FROM problem_packages WHERE problem_id = $2))
RETURNING id, problem_id, organization_id, version, package_hash, url, status, build_log, created_at, compiled_at
`

type CreateProblemPackageParams struct {
	ID             uuid.UUID     `json:"id"`
	ProblemID      uuid.UUID     `json:"problem_id"`
	OrganizationID uuid.UUID     `json:"organization_id"`
	PackageHash    string        `json:"package_hash"`
	Status         PackageStatus `json:"status"`
}

// Problem Packages queries
func (q *Queries) CreateProblemPackage(ctx context.Context, arg CreateProblemPackageParams) (ProblemPackage, error) {
	row := q.db.QueryRow(ctx, createProblemPackage,
		arg.ID,
		arg.ProblemID,
		arg.OrganizationID,
		arg.PackageHash,
		arg.Status,
	)
	var i ProblemPackage
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.OrganizationID,
		&i.Version,
		&i.PackageHash,
		&i.Url,
		&i.Status,
		&i.BuildLog,
		&i.CreatedAt,
		&i.CompiledAt,
	)
	return i, err
}

const deleteProblemPackage = `-- name: DeleteProblemPackage :exec
DELETE FROM problem_packages WHERE id = $1
`

func (q *Queries) DeleteProblemPackage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProblemPackage, id)
	return err
}

const getProblemPackageByHash = `-- name: GetProblemPackageByHash :one
SELECT id, problem_id, organization_id, version, package_hash, url, status, build_log, created_at, compiled_at FROM problem_packages WHERE package_hash = $1
`

func (q *Queries) GetProblemPackageByHash(ctx context.Context, packageHash string) (ProblemPackage, error) {
	row := q.db.QueryRow(ctx, getProblemPackageByHash, packageHash)
	var i ProblemPackage
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.OrganizationID,
		&i.Version,
		&i.PackageHash,
		&i.Url,
		&i.Status,
		&i.BuildLog,
		&i.CreatedAt,
		&i.CompiledAt,
	)
	return i, err
}

const getProblemPackageByID = `-- name: GetProblemPackageByID :one
SELECT id, problem_id, organization_id, version, package_hash, url, status, build_log, created_at, compiled_at FROM problem_packages WHERE id = $1
`

func (q *Queries) GetProblemPackageByID(ctx context.Context, id uuid.UUID) (ProblemPackage, error) {
	row := q.db.QueryRow(ctx, getProblemPackageByID, id)
	var i ProblemPackage
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.OrganizationID,
		&i.Version,
		&i.PackageHash,
		&i.Url,
		&i.Status,
		&i.BuildLog,
		&i.CreatedAt,
		&i.CompiledAt,
	)
	return i, err
}

const getProblemPackageByVersion = `-- name: GetProblemPackageByVersion :one
SELECT id, problem_id, organization_id, version, package_hash, url, status, build_log, created_at, compiled_at FROM problem_packages WHERE problem_id = $1 AND version = $2
`

type GetProblemPackageByVersionParams struct {
	ProblemID uuid.UUID `json:"problem_id"`
	Version   int32     `json:"version"`
}

func (q *Queries) GetProblemPackageByVersion(ctx context.Context, arg GetProblemPackageByVersionParams) (ProblemPackage, error) {
	row := q.db.QueryRow(ctx, getProblemPackageByVersion, arg.ProblemID, arg.Version)
	var i ProblemPackage
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.OrganizationID,
		&i.Version,
		&i.PackageHash,
		&i.Url,
		&i.Status,
		&i.BuildLog,
		&i.CreatedAt,
		&i.CompiledAt,
	)
	return i, err
}

const getReadyPackage = `-- name: GetReadyPackage :one
SELECT id, problem_id, organization_id, version, package_hash, url, status, build_log, created_at, compiled_at FROM problem_packages
WHERE problem_id = $1 AND status = 'ready'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetReadyPackage(ctx context.Context, problemID uuid.UUID) (ProblemPackage, error) {
	row := q.db.QueryRow(ctx, getReadyPackage, problemID)
	var i ProblemPackage
	err := row.Scan(
		&i.ID,
		&i.ProblemID,
		&i.OrganizationID,
		&i.Version,
		&i.PackageHash,
		&i.Url,
		&i.Status,
		&i.BuildLog,
		&i.CreatedAt,
		&i.CompiledAt,
	)
	return i, err
}

const listProblemPackages = `-- name: ListProblemPackages :many
SELECT id, problem_id, organization_id, version, package_hash, url, status, build_log, created_at, compiled_at FROM problem_packages
WHERE problem_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProblemPackagesParams struct {
	ProblemID uuid.UUID `json:"problem_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListProblemPackages(ctx context.Context, arg ListProblemPackagesParams) ([]ProblemPackage, error) {
	rows, err := q.db.Query(ctx, listProblemPackages, arg.ProblemID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProblemPackage{}
	for rows.Next() {
		var i ProblemPackage
		if err := rows.Scan(
			&i.ID,
			&i.ProblemID,
			&i.OrganizationID,
			&i.Version,
			&i.PackageHash,
			&i.Url,
			&i.Status,
			&i.BuildLog,
			&i.CreatedAt,
			&i.CompiledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePackageStatus = `-- name: UpdatePackageStatus :exec
UPDATE problem_packages
SET status = $2,
    url = COALESCE($3, url),
    build_log = COALESCE($4, build_log),
    compiled_at = CASE WHEN $2 = 'ready'::package_status THEN NOW() ELSE compiled_at END
WHERE id = $1
`

type UpdatePackageStatusParams struct {
	ID       uuid.UUID     `json:"id"`
	Status   PackageStatus `json:"status"`
	Url      *string       `json:"url"`
	BuildLog *string       `json:"build_log"`
}

func (q *Queries) UpdatePackageStatus(ctx context.Context, arg UpdatePackageStatusParams) error {
	_, err := q.db.Exec(ctx, updatePackageStatus,
		arg.ID,
		arg.Status,
		arg.Url,
		arg.BuildLog,
	)
	return err
}
