// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: requests.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createContestJoinRequest = `-- name: CreateContestJoinRequest :one

INSERT INTO contest_join_requests (
    id,
    contest_id,
    user_id,
    message,
    status,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    'pending',
    NOW(),
    NOW()
) RETURNING id, contest_id, user_id, message, status, reviewed_by, created_at, updated_at
`

type CreateContestJoinRequestParams struct {
	ID        uuid.UUID `json:"id"`
	ContestID uuid.UUID `json:"contest_id"`
	UserID    uuid.UUID `json:"user_id"`
	Message   *string   `json:"message"`
}

// ============================================================================
// Contest Join Requests
// ============================================================================
func (q *Queries) CreateContestJoinRequest(ctx context.Context, arg CreateContestJoinRequestParams) (ContestJoinRequest, error) {
	row := q.db.QueryRow(ctx, createContestJoinRequest,
		arg.ID,
		arg.ContestID,
		arg.UserID,
		arg.Message,
	)
	var i ContestJoinRequest
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.Message,
		&i.Status,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganizationInvitation = `-- name: CreateOrganizationInvitation :one


INSERT INTO organization_invitations (
    id,
    organization_id,
    user_id,
    inviter_id,
    role,
    status,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    'pending',
    NOW(),
    NOW()
) RETURNING id, organization_id, user_id, inviter_id, role, status, created_at, updated_at
`

type CreateOrganizationInvitationParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	InviterID      uuid.UUID `json:"inviter_id"`
	Role           string    `json:"role"`
}

// Invitations & Join Requests queries
// ============================================================================
// Organization Invitations
// ============================================================================
func (q *Queries) CreateOrganizationInvitation(ctx context.Context, arg CreateOrganizationInvitationParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, createOrganizationInvitation,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.InviterID,
		arg.Role,
	)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.InviterID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrganizationJoinRequest = `-- name: CreateOrganizationJoinRequest :one

INSERT INTO organization_join_requests (
    id,
    organization_id,
    user_id,
    message,
    status,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    'pending',
    NOW(),
    NOW()
) RETURNING id, organization_id, user_id, message, status, reviewed_by, created_at, updated_at
`

type CreateOrganizationJoinRequestParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
	Message        *string   `json:"message"`
}

// ============================================================================
// Organization Join Requests
// ============================================================================
func (q *Queries) CreateOrganizationJoinRequest(ctx context.Context, arg CreateOrganizationJoinRequestParams) (OrganizationJoinRequest, error) {
	row := q.db.QueryRow(ctx, createOrganizationJoinRequest,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.Message,
	)
	var i OrganizationJoinRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Message,
		&i.Status,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContestJoinRequestByID = `-- name: GetContestJoinRequestByID :one
SELECT cjr.id, cjr.contest_id, cjr.user_id, cjr.message, cjr.status, cjr.reviewed_by, cjr.created_at, cjr.updated_at, c.title as contest_title, c.login as contest_login, o.login as organization_login, u.username, u.email, rev.username as reviewer_username
FROM contest_join_requests cjr
JOIN contests c ON cjr.contest_id = c.id
JOIN organizations o ON c.organization_id = o.id
JOIN users u ON cjr.user_id = u.id
LEFT JOIN users rev ON cjr.reviewed_by = rev.id
WHERE cjr.id = $1
`

type GetContestJoinRequestByIDRow struct {
	ID                uuid.UUID   `json:"id"`
	ContestID         uuid.UUID   `json:"contest_id"`
	UserID            uuid.UUID   `json:"user_id"`
	Message           *string     `json:"message"`
	Status            string      `json:"status"`
	ReviewedBy        pgtype.UUID `json:"reviewed_by"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
	ContestTitle      string      `json:"contest_title"`
	ContestLogin      string      `json:"contest_login"`
	OrganizationLogin string      `json:"organization_login"`
	Username          string      `json:"username"`
	Email             *string     `json:"email"`
	ReviewerUsername  *string     `json:"reviewer_username"`
}

func (q *Queries) GetContestJoinRequestByID(ctx context.Context, id uuid.UUID) (GetContestJoinRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getContestJoinRequestByID, id)
	var i GetContestJoinRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.Message,
		&i.Status,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContestTitle,
		&i.ContestLogin,
		&i.OrganizationLogin,
		&i.Username,
		&i.Email,
		&i.ReviewerUsername,
	)
	return i, err
}

const getOrganizationInvitationByID = `-- name: GetOrganizationInvitationByID :one
SELECT oi.id, oi.organization_id, oi.user_id, oi.inviter_id, oi.role, oi.status, oi.created_at, oi.updated_at, o.name as organization_name, o.login as organization_login, u.username, u.email, inv.username as inviter_username
FROM organization_invitations oi
JOIN organizations o ON oi.organization_id = o.id
JOIN users u ON oi.user_id = u.id
JOIN users inv ON oi.inviter_id = inv.id
WHERE oi.id = $1
`

type GetOrganizationInvitationByIDRow struct {
	ID                uuid.UUID `json:"id"`
	OrganizationID    uuid.UUID `json:"organization_id"`
	UserID            uuid.UUID `json:"user_id"`
	InviterID         uuid.UUID `json:"inviter_id"`
	Role              string    `json:"role"`
	Status            string    `json:"status"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	OrganizationName  string    `json:"organization_name"`
	OrganizationLogin string    `json:"organization_login"`
	Username          string    `json:"username"`
	Email             *string   `json:"email"`
	InviterUsername   string    `json:"inviter_username"`
}

func (q *Queries) GetOrganizationInvitationByID(ctx context.Context, id uuid.UUID) (GetOrganizationInvitationByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationInvitationByID, id)
	var i GetOrganizationInvitationByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.InviterID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationName,
		&i.OrganizationLogin,
		&i.Username,
		&i.Email,
		&i.InviterUsername,
	)
	return i, err
}

const getOrganizationJoinRequestByID = `-- name: GetOrganizationJoinRequestByID :one
SELECT ojr.id, ojr.organization_id, ojr.user_id, ojr.message, ojr.status, ojr.reviewed_by, ojr.created_at, ojr.updated_at, o.name as organization_name, o.login as organization_login, u.username, u.email, rev.username as reviewer_username
FROM organization_join_requests ojr
JOIN organizations o ON ojr.organization_id = o.id
JOIN users u ON ojr.user_id = u.id
LEFT JOIN users rev ON ojr.reviewed_by = rev.id
WHERE ojr.id = $1
`

type GetOrganizationJoinRequestByIDRow struct {
	ID                uuid.UUID   `json:"id"`
	OrganizationID    uuid.UUID   `json:"organization_id"`
	UserID            uuid.UUID   `json:"user_id"`
	Message           *string     `json:"message"`
	Status            string      `json:"status"`
	ReviewedBy        pgtype.UUID `json:"reviewed_by"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
	OrganizationName  string      `json:"organization_name"`
	OrganizationLogin string      `json:"organization_login"`
	Username          string      `json:"username"`
	Email             *string     `json:"email"`
	ReviewerUsername  *string     `json:"reviewer_username"`
}

func (q *Queries) GetOrganizationJoinRequestByID(ctx context.Context, id uuid.UUID) (GetOrganizationJoinRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationJoinRequestByID, id)
	var i GetOrganizationJoinRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Message,
		&i.Status,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationName,
		&i.OrganizationLogin,
		&i.Username,
		&i.Email,
		&i.ReviewerUsername,
	)
	return i, err
}

const getPendingContestJoinRequest = `-- name: GetPendingContestJoinRequest :one
SELECT id, contest_id, user_id, message, status, reviewed_by, created_at, updated_at FROM contest_join_requests
WHERE contest_id = $1 AND user_id = $2 AND status = 'pending'
LIMIT 1
`

type GetPendingContestJoinRequestParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPendingContestJoinRequest(ctx context.Context, arg GetPendingContestJoinRequestParams) (ContestJoinRequest, error) {
	row := q.db.QueryRow(ctx, getPendingContestJoinRequest, arg.ContestID, arg.UserID)
	var i ContestJoinRequest
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.Message,
		&i.Status,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingOrganizationInvitation = `-- name: GetPendingOrganizationInvitation :one
SELECT id, organization_id, user_id, inviter_id, role, status, created_at, updated_at FROM organization_invitations
WHERE organization_id = $1 AND user_id = $2 AND status = 'pending'
LIMIT 1
`

type GetPendingOrganizationInvitationParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPendingOrganizationInvitation(ctx context.Context, arg GetPendingOrganizationInvitationParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, getPendingOrganizationInvitation, arg.OrganizationID, arg.UserID)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.InviterID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingOrganizationJoinRequest = `-- name: GetPendingOrganizationJoinRequest :one
SELECT id, organization_id, user_id, message, status, reviewed_by, created_at, updated_at FROM organization_join_requests
WHERE organization_id = $1 AND user_id = $2 AND status = 'pending'
LIMIT 1
`

type GetPendingOrganizationJoinRequestParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) GetPendingOrganizationJoinRequest(ctx context.Context, arg GetPendingOrganizationJoinRequestParams) (OrganizationJoinRequest, error) {
	row := q.db.QueryRow(ctx, getPendingOrganizationJoinRequest, arg.OrganizationID, arg.UserID)
	var i OrganizationJoinRequest
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Message,
		&i.Status,
		&i.ReviewedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContestJoinRequests = `-- name: ListContestJoinRequests :many
SELECT cjr.id, cjr.contest_id, cjr.user_id, cjr.message, cjr.status, cjr.reviewed_by, cjr.created_at, cjr.updated_at, u.username, u.email, rev.username as reviewer_username
FROM contest_join_requests cjr
JOIN users u ON cjr.user_id = u.id
LEFT JOIN users rev ON cjr.reviewed_by = rev.id
WHERE cjr.contest_id = $1
  AND ($2::text IS NULL OR cjr.status = $2)
ORDER BY cjr.created_at DESC
`

type ListContestJoinRequestsParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	Status    *string   `json:"status"`
}

type ListContestJoinRequestsRow struct {
	ID               uuid.UUID   `json:"id"`
	ContestID        uuid.UUID   `json:"contest_id"`
	UserID           uuid.UUID   `json:"user_id"`
	Message          *string     `json:"message"`
	Status           string      `json:"status"`
	ReviewedBy       pgtype.UUID `json:"reviewed_by"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	Username         string      `json:"username"`
	Email            *string     `json:"email"`
	ReviewerUsername *string     `json:"reviewer_username"`
}

func (q *Queries) ListContestJoinRequests(ctx context.Context, arg ListContestJoinRequestsParams) ([]ListContestJoinRequestsRow, error) {
	rows, err := q.db.Query(ctx, listContestJoinRequests, arg.ContestID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContestJoinRequestsRow{}
	for rows.Next() {
		var i ListContestJoinRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.UserID,
			&i.Message,
			&i.Status,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Email,
			&i.ReviewerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationInvitations = `-- name: ListOrganizationInvitations :many
SELECT oi.id, oi.organization_id, oi.user_id, oi.inviter_id, oi.role, oi.status, oi.created_at, oi.updated_at, u.username, u.email, inv.username as inviter_username
FROM organization_invitations oi
JOIN users u ON oi.user_id = u.id
JOIN users inv ON oi.inviter_id = inv.id
WHERE oi.organization_id = $1
  AND ($2::text IS NULL OR oi.status = $2)
ORDER BY oi.created_at DESC
`

type ListOrganizationInvitationsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Status         *string   `json:"status"`
}

type ListOrganizationInvitationsRow struct {
	ID              uuid.UUID `json:"id"`
	OrganizationID  uuid.UUID `json:"organization_id"`
	UserID          uuid.UUID `json:"user_id"`
	InviterID       uuid.UUID `json:"inviter_id"`
	Role            string    `json:"role"`
	Status          string    `json:"status"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	Username        string    `json:"username"`
	Email           *string   `json:"email"`
	InviterUsername string    `json:"inviter_username"`
}

func (q *Queries) ListOrganizationInvitations(ctx context.Context, arg ListOrganizationInvitationsParams) ([]ListOrganizationInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationInvitations, arg.OrganizationID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationInvitationsRow{}
	for rows.Next() {
		var i ListOrganizationInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.InviterID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Email,
			&i.InviterUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationJoinRequests = `-- name: ListOrganizationJoinRequests :many
SELECT ojr.id, ojr.organization_id, ojr.user_id, ojr.message, ojr.status, ojr.reviewed_by, ojr.created_at, ojr.updated_at, u.username, u.email, rev.username as reviewer_username
FROM organization_join_requests ojr
JOIN users u ON ojr.user_id = u.id
LEFT JOIN users rev ON ojr.reviewed_by = rev.id
WHERE ojr.organization_id = $1
  AND ($2::text IS NULL OR ojr.status = $2)
ORDER BY ojr.created_at DESC
`

type ListOrganizationJoinRequestsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Status         *string   `json:"status"`
}

type ListOrganizationJoinRequestsRow struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   uuid.UUID   `json:"organization_id"`
	UserID           uuid.UUID   `json:"user_id"`
	Message          *string     `json:"message"`
	Status           string      `json:"status"`
	ReviewedBy       pgtype.UUID `json:"reviewed_by"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	Username         string      `json:"username"`
	Email            *string     `json:"email"`
	ReviewerUsername *string     `json:"reviewer_username"`
}

func (q *Queries) ListOrganizationJoinRequests(ctx context.Context, arg ListOrganizationJoinRequestsParams) ([]ListOrganizationJoinRequestsRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationJoinRequests, arg.OrganizationID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationJoinRequestsRow{}
	for rows.Next() {
		var i ListOrganizationJoinRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Message,
			&i.Status,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Email,
			&i.ReviewerUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserContestJoinRequests = `-- name: ListUserContestJoinRequests :many
SELECT cjr.id, cjr.contest_id, cjr.user_id, cjr.message, cjr.status, cjr.reviewed_by, cjr.created_at, cjr.updated_at, c.title as contest_title, c.login as contest_login, o.login as organization_login
FROM contest_join_requests cjr
JOIN contests c ON cjr.contest_id = c.id
JOIN organizations o ON c.organization_id = o.id
WHERE cjr.user_id = $1
ORDER BY cjr.created_at DESC
`

type ListUserContestJoinRequestsRow struct {
	ID                uuid.UUID   `json:"id"`
	ContestID         uuid.UUID   `json:"contest_id"`
	UserID            uuid.UUID   `json:"user_id"`
	Message           *string     `json:"message"`
	Status            string      `json:"status"`
	ReviewedBy        pgtype.UUID `json:"reviewed_by"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
	ContestTitle      string      `json:"contest_title"`
	ContestLogin      string      `json:"contest_login"`
	OrganizationLogin string      `json:"organization_login"`
}

func (q *Queries) ListUserContestJoinRequests(ctx context.Context, userID uuid.UUID) ([]ListUserContestJoinRequestsRow, error) {
	rows, err := q.db.Query(ctx, listUserContestJoinRequests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserContestJoinRequestsRow{}
	for rows.Next() {
		var i ListUserContestJoinRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.UserID,
			&i.Message,
			&i.Status,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContestTitle,
			&i.ContestLogin,
			&i.OrganizationLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrganizationInvitations = `-- name: ListUserOrganizationInvitations :many
SELECT oi.id, oi.organization_id, oi.user_id, oi.inviter_id, oi.role, oi.status, oi.created_at, oi.updated_at, o.name as organization_name, o.login as organization_login, o.avatar_url as organization_avatar_url, inv.username as inviter_username
FROM organization_invitations oi
JOIN organizations o ON oi.organization_id = o.id
JOIN users inv ON oi.inviter_id = inv.id
WHERE oi.user_id = $1
  AND ($2::text IS NULL OR oi.status = $2)
ORDER BY oi.created_at DESC
`

type ListUserOrganizationInvitationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Status *string   `json:"status"`
}

type ListUserOrganizationInvitationsRow struct {
	ID                    uuid.UUID `json:"id"`
	OrganizationID        uuid.UUID `json:"organization_id"`
	UserID                uuid.UUID `json:"user_id"`
	InviterID             uuid.UUID `json:"inviter_id"`
	Role                  string    `json:"role"`
	Status                string    `json:"status"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
	OrganizationName      string    `json:"organization_name"`
	OrganizationLogin     string    `json:"organization_login"`
	OrganizationAvatarUrl *string   `json:"organization_avatar_url"`
	InviterUsername       string    `json:"inviter_username"`
}

func (q *Queries) ListUserOrganizationInvitations(ctx context.Context, arg ListUserOrganizationInvitationsParams) ([]ListUserOrganizationInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listUserOrganizationInvitations, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserOrganizationInvitationsRow{}
	for rows.Next() {
		var i ListUserOrganizationInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.InviterID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationName,
			&i.OrganizationLogin,
			&i.OrganizationAvatarUrl,
			&i.InviterUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserOrganizationJoinRequests = `-- name: ListUserOrganizationJoinRequests :many
SELECT ojr.id, ojr.organization_id, ojr.user_id, ojr.message, ojr.status, ojr.reviewed_by, ojr.created_at, ojr.updated_at, o.name as organization_name, o.login as organization_login
FROM organization_join_requests ojr
JOIN organizations o ON ojr.organization_id = o.id
WHERE ojr.user_id = $1
ORDER BY ojr.created_at DESC
`

type ListUserOrganizationJoinRequestsRow struct {
	ID                uuid.UUID   `json:"id"`
	OrganizationID    uuid.UUID   `json:"organization_id"`
	UserID            uuid.UUID   `json:"user_id"`
	Message           *string     `json:"message"`
	Status            string      `json:"status"`
	ReviewedBy        pgtype.UUID `json:"reviewed_by"`
	CreatedAt         time.Time   `json:"created_at"`
	UpdatedAt         time.Time   `json:"updated_at"`
	OrganizationName  string      `json:"organization_name"`
	OrganizationLogin string      `json:"organization_login"`
}

func (q *Queries) ListUserOrganizationJoinRequests(ctx context.Context, userID uuid.UUID) ([]ListUserOrganizationJoinRequestsRow, error) {
	rows, err := q.db.Query(ctx, listUserOrganizationJoinRequests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserOrganizationJoinRequestsRow{}
	for rows.Next() {
		var i ListUserOrganizationJoinRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Message,
			&i.Status,
			&i.ReviewedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationName,
			&i.OrganizationLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContestJoinRequestStatus = `-- name: UpdateContestJoinRequestStatus :exec
UPDATE contest_join_requests
SET status = $2, reviewed_by = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateContestJoinRequestStatusParams struct {
	ID         uuid.UUID   `json:"id"`
	Status     string      `json:"status"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) UpdateContestJoinRequestStatus(ctx context.Context, arg UpdateContestJoinRequestStatusParams) error {
	_, err := q.db.Exec(ctx, updateContestJoinRequestStatus, arg.ID, arg.Status, arg.ReviewedBy)
	return err
}

const updateOrganizationInvitationStatus = `-- name: UpdateOrganizationInvitationStatus :exec
UPDATE organization_invitations
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateOrganizationInvitationStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateOrganizationInvitationStatus(ctx context.Context, arg UpdateOrganizationInvitationStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationInvitationStatus, arg.ID, arg.Status)
	return err
}

const updateOrganizationJoinRequestStatus = `-- name: UpdateOrganizationJoinRequestStatus :exec
UPDATE organization_join_requests
SET status = $2, reviewed_by = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateOrganizationJoinRequestStatusParams struct {
	ID         uuid.UUID   `json:"id"`
	Status     string      `json:"status"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) UpdateOrganizationJoinRequestStatus(ctx context.Context, arg UpdateOrganizationJoinRequestStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrganizationJoinRequestStatus, arg.ID, arg.Status, arg.ReviewedBy)
	return err
}
