// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: submissions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/gate149/gate/backend/internal/domain/models"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSubmissions = `-- name: CountSubmissions :one
SELECT COUNT(*)
FROM submissions s
WHERE (
    $1::uuid IS NULL
    OR s.contest_id = $1::uuid
  )
  AND (
    $2::uuid IS NULL
    OR s.owner_id = $2::uuid
  )
  AND (
    $3::uuid IS NULL
    OR s.problem_id = $3::uuid
  )
  AND (
    $4::integer IS NULL
    OR s.language = $4::integer
  )
  AND (
    $5::integer IS NULL
    OR s.state = $5::integer
  )
`

type CountSubmissionsParams struct {
	ContestID pgtype.UUID `json:"contest_id"`
	OwnerID   pgtype.UUID `json:"owner_id"`
	ProblemID pgtype.UUID `json:"problem_id"`
	Language  *int32      `json:"language"`
	State     *int32      `json:"state"`
}

func (q *Queries) CountSubmissions(ctx context.Context, arg CountSubmissionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubmissions,
		arg.ContestID,
		arg.OwnerID,
		arg.ProblemID,
		arg.Language,
		arg.State,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (
    contest_id,
    problem_id,
    owner_id,
    source,
    language,
    penalty
  )
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4,
    $5,
    $6
  )
RETURNING id
`

type CreateSubmissionParams struct {
	ContestID uuid.UUID           `json:"contest_id"`
	ProblemID uuid.UUID           `json:"problem_id"`
	OwnerID   uuid.UUID           `json:"owner_id"`
	Source    string              `json:"source"`
	Language  models.LanguageName `json:"language"`
	Penalty   int32               `json:"penalty"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.ContestID,
		arg.ProblemID,
		arg.OwnerID,
		arg.Source,
		arg.Language,
		arg.Penalty,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSubmission = `-- name: GetSubmission :one
SELECT s.id,
  s.owner_id,
  u.username,
  s.source,
  s.state,
  s.score,
  s.penalty,
  s.time_stat,
  s.memory_stat,
  s.language,
  s.problem_id,
  p.title AS problem_title,
  p.short_name AS problem_short_name,
  cp.ordinal AS problem_ordinal,
  s.contest_id,
  c.title AS contest_title,
  c.short_name AS contest_short_name,
  c.visibility AS contest_visibility,
  s.updated_at,
  s.created_at
FROM submissions s
  LEFT JOIN users u ON s.owner_id = u.id
  LEFT JOIN problems p ON s.problem_id = p.id
  LEFT JOIN contest_problems cp ON p.id = cp.problem_id
  AND cp.contest_id = s.contest_id
  LEFT JOIN contests c ON s.contest_id = c.id
WHERE s.id = $1::uuid
`

type GetSubmissionRow struct {
	ID                uuid.UUID             `json:"id"`
	OwnerID           pgtype.UUID           `json:"owner_id"`
	Username          *string               `json:"username"`
	Source            string                `json:"source"`
	State             models.State          `json:"state"`
	Score             int32                 `json:"score"`
	Penalty           int32                 `json:"penalty"`
	TimeStat          int32                 `json:"time_stat"`
	MemoryStat        int32                 `json:"memory_stat"`
	Language          models.LanguageName   `json:"language"`
	ProblemID         pgtype.UUID           `json:"problem_id"`
	ProblemTitle      *string               `json:"problem_title"`
	ProblemShortName  *string               `json:"problem_short_name"`
	ProblemOrdinal    *int32                `json:"problem_ordinal"`
	ContestID         pgtype.UUID           `json:"contest_id"`
	ContestTitle      *string               `json:"contest_title"`
	ContestShortName  *string               `json:"contest_short_name"`
	ContestVisibility NullContestVisibility `json:"contest_visibility"`
	UpdatedAt         time.Time             `json:"updated_at"`
	CreatedAt         time.Time             `json:"created_at"`
}

func (q *Queries) GetSubmission(ctx context.Context, id uuid.UUID) (GetSubmissionRow, error) {
	row := q.db.QueryRow(ctx, getSubmission, id)
	var i GetSubmissionRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Username,
		&i.Source,
		&i.State,
		&i.Score,
		&i.Penalty,
		&i.TimeStat,
		&i.MemoryStat,
		&i.Language,
		&i.ProblemID,
		&i.ProblemTitle,
		&i.ProblemShortName,
		&i.ProblemOrdinal,
		&i.ContestID,
		&i.ContestTitle,
		&i.ContestShortName,
		&i.ContestVisibility,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listSubmissions = `-- name: ListSubmissions :many
SELECT s.id,
  s.owner_id,
  u.username,
  s.state,
  s.score,
  s.penalty,
  s.time_stat,
  s.memory_stat,
  s.language,
  s.problem_id,
  p.title AS problem_title,
  p.short_name AS problem_short_name,
  cp.ordinal AS problem_ordinal,
  s.contest_id,
  c.title AS contest_title,
  c.short_name AS contest_short_name,
  s.updated_at,
  s.created_at
FROM submissions s
  LEFT JOIN users u ON s.owner_id = u.id
  LEFT JOIN problems p ON s.problem_id = p.id
  LEFT JOIN contest_problems cp ON p.id = cp.problem_id
  AND cp.contest_id = s.contest_id
  LEFT JOIN contests c ON s.contest_id = c.id
WHERE (
    $1::uuid IS NULL
    OR s.contest_id = $1::uuid
  )
  AND (
    $2::uuid IS NULL
    OR s.owner_id = $2::uuid
  )
  AND (
    $3::uuid IS NULL
    OR s.problem_id = $3::uuid
  )
  AND (
    $4::integer IS NULL
    OR s.language = $4::integer
  )
  AND (
    $5::integer IS NULL
    OR s.state = $5::integer
  )
ORDER BY CASE
    WHEN $6::int < 0 THEN s.created_at
  END DESC,
  CASE
    WHEN $6::int >= 0 THEN s.created_at
  END ASC
LIMIT $8 OFFSET $7
`

type ListSubmissionsParams struct {
	ContestID pgtype.UUID `json:"contest_id"`
	OwnerID   pgtype.UUID `json:"owner_id"`
	ProblemID pgtype.UUID `json:"problem_id"`
	Language  *int32      `json:"language"`
	State     *int32      `json:"state"`
	SortOrder *int32      `json:"sort_order"`
	Offset    int32       `json:"offset"`
	Limit     int32       `json:"limit"`
}

type ListSubmissionsRow struct {
	ID               uuid.UUID           `json:"id"`
	OwnerID          pgtype.UUID         `json:"owner_id"`
	Username         *string             `json:"username"`
	State            models.State        `json:"state"`
	Score            int32               `json:"score"`
	Penalty          int32               `json:"penalty"`
	TimeStat         int32               `json:"time_stat"`
	MemoryStat       int32               `json:"memory_stat"`
	Language         models.LanguageName `json:"language"`
	ProblemID        pgtype.UUID         `json:"problem_id"`
	ProblemTitle     *string             `json:"problem_title"`
	ProblemShortName *string             `json:"problem_short_name"`
	ProblemOrdinal   *int32              `json:"problem_ordinal"`
	ContestID        pgtype.UUID         `json:"contest_id"`
	ContestTitle     *string             `json:"contest_title"`
	ContestShortName *string             `json:"contest_short_name"`
	UpdatedAt        time.Time           `json:"updated_at"`
	CreatedAt        time.Time           `json:"created_at"`
}

// Submission listing
func (q *Queries) ListSubmissions(ctx context.Context, arg ListSubmissionsParams) ([]ListSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, listSubmissions,
		arg.ContestID,
		arg.OwnerID,
		arg.ProblemID,
		arg.Language,
		arg.State,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubmissionsRow{}
	for rows.Next() {
		var i ListSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Username,
			&i.State,
			&i.Score,
			&i.Penalty,
			&i.TimeStat,
			&i.MemoryStat,
			&i.Language,
			&i.ProblemID,
			&i.ProblemTitle,
			&i.ProblemShortName,
			&i.ProblemOrdinal,
			&i.ContestID,
			&i.ContestTitle,
			&i.ContestShortName,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubmission = `-- name: UpdateSubmission :exec
UPDATE submissions
SET state = $1,
  score = $2,
  time_stat = $3,
  memory_stat = $4
WHERE id = $5::uuid
`

type UpdateSubmissionParams struct {
	State      models.State `json:"state"`
	Score      int32        `json:"score"`
	TimeStat   int32        `json:"time_stat"`
	MemoryStat int32        `json:"memory_stat"`
	ID         uuid.UUID    `json:"id"`
}

func (q *Queries) UpdateSubmission(ctx context.Context, arg UpdateSubmissionParams) error {
	_, err := q.db.Exec(ctx, updateSubmission,
		arg.State,
		arg.Score,
		arg.TimeStat,
		arg.MemoryStat,
		arg.ID,
	)
	return err
}
