// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: submissions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/brawler2011/gate/backend/internal/domain/models"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const blockSubmission = `-- name: BlockSubmission :exec
UPDATE submissions
SET state = 300,
  score = 0,
  ban_reason = $1,
  updated_at = NOW()
WHERE id = $2::uuid
`

type BlockSubmissionParams struct {
	BanReason *string   `json:"ban_reason"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) BlockSubmission(ctx context.Context, arg BlockSubmissionParams) error {
	_, err := q.db.Exec(ctx, blockSubmission, arg.BanReason, arg.ID)
	return err
}

const blockUserProblemSubmissions = `-- name: BlockUserProblemSubmissions :exec
UPDATE submissions
SET state = 300,
  score = 0,
  ban_reason = $1,
  updated_at = NOW()
WHERE contest_id = $2::uuid
  AND owner_id = $3::uuid
  AND problem_id = $4::uuid
`

type BlockUserProblemSubmissionsParams struct {
	BanReason *string   `json:"ban_reason"`
	ContestID uuid.UUID `json:"contest_id"`
	OwnerID   uuid.UUID `json:"owner_id"`
	ProblemID uuid.UUID `json:"problem_id"`
}

func (q *Queries) BlockUserProblemSubmissions(ctx context.Context, arg BlockUserProblemSubmissionsParams) error {
	_, err := q.db.Exec(ctx, blockUserProblemSubmissions,
		arg.BanReason,
		arg.ContestID,
		arg.OwnerID,
		arg.ProblemID,
	)
	return err
}

const countSubmissions = `-- name: CountSubmissions :one
SELECT COUNT(*)
FROM submissions s
WHERE (
    $1::uuid IS NULL
    OR s.contest_id = $1::uuid
  )
  AND (
    $2::uuid IS NULL
    OR s.owner_id = $2::uuid
  )
  AND (
    $3::uuid IS NULL
    OR s.problem_id = $3::uuid
  )
  AND (
    $4::integer IS NULL
    OR s.language = $4::integer
  )
  AND (
    $5::integer IS NULL
    OR s.state = $5::integer
  )
`

type CountSubmissionsParams struct {
	ContestID pgtype.UUID `json:"contest_id"`
	OwnerID   pgtype.UUID `json:"owner_id"`
	ProblemID pgtype.UUID `json:"problem_id"`
	Language  *int32      `json:"language"`
	State     *int32      `json:"state"`
}

func (q *Queries) CountSubmissions(ctx context.Context, arg CountSubmissionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubmissions,
		arg.ContestID,
		arg.OwnerID,
		arg.ProblemID,
		arg.Language,
		arg.State,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (
    contest_id,
    problem_id,
    owner_id,
    source,
    language,
    penalty,
    state,
    ban_reason
  )
VALUES (
    $1::uuid,
    $2::uuid,
    $3::uuid,
    $4,
    $5,
    $6,
    COALESCE($7::integer, 1),
    $8
  )
RETURNING id
`

type CreateSubmissionParams struct {
	ContestID uuid.UUID           `json:"contest_id"`
	ProblemID uuid.UUID           `json:"problem_id"`
	OwnerID   uuid.UUID           `json:"owner_id"`
	Source    string              `json:"source"`
	Language  models.LanguageName `json:"language"`
	Penalty   int32               `json:"penalty"`
	State     *int32              `json:"state"`
	BanReason *string             `json:"ban_reason"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.ContestID,
		arg.ProblemID,
		arg.OwnerID,
		arg.Source,
		arg.Language,
		arg.Penalty,
		arg.State,
		arg.BanReason,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getSubmission = `-- name: GetSubmission :one
SELECT s.id,
  s.owner_id,
  u.username,
  s.source,
  s.state,
  s.score,
  s.penalty,
  COALESCE((s.test_details->>'time_stat')::integer, 0)::integer AS time_stat,
  COALESCE((s.test_details->>'memory_stat')::integer, 0)::integer AS memory_stat,
  s.language,
  (s.test_details->>'failed_test')::integer AS failed_test,
  s.test_details,
  s.ban_reason,
  s.problem_id,
  p.title AS problem_title,
  p.short_name AS problem_short_name,
  cp.ordinal AS problem_ordinal,
  s.contest_id,
  c.title AS contest_title,
  c.login AS contest_login,
  c.visibility AS contest_visibility,
  COALESCE(oc.login, op.login, '')::text AS organization_login,
  s.updated_at,
  s.created_at
FROM submissions s
  LEFT JOIN users u ON s.owner_id = u.id
  LEFT JOIN problems p ON s.problem_id = p.id
  LEFT JOIN organizations op ON p.organization_id = op.id
  LEFT JOIN contest_problems cp ON p.id = cp.problem_id
  AND cp.contest_id = s.contest_id
  LEFT JOIN contests c ON s.contest_id = c.id
  LEFT JOIN organizations oc ON c.organization_id = oc.id
WHERE s.id = $1::uuid
`

type GetSubmissionRow struct {
	ID                uuid.UUID             `json:"id"`
	OwnerID           pgtype.UUID           `json:"owner_id"`
	Username          *string               `json:"username"`
	Source            string                `json:"source"`
	State             models.State          `json:"state"`
	Score             int32                 `json:"score"`
	Penalty           int32                 `json:"penalty"`
	TimeStat          int32                 `json:"time_stat"`
	MemoryStat        int32                 `json:"memory_stat"`
	Language          models.LanguageName   `json:"language"`
	FailedTest        int32                 `json:"failed_test"`
	TestDetails       []byte                `json:"test_details"`
	BanReason         *string               `json:"ban_reason"`
	ProblemID         pgtype.UUID           `json:"problem_id"`
	ProblemTitle      *string               `json:"problem_title"`
	ProblemShortName  *string               `json:"problem_short_name"`
	ProblemOrdinal    *int32                `json:"problem_ordinal"`
	ContestID         pgtype.UUID           `json:"contest_id"`
	ContestTitle      *string               `json:"contest_title"`
	ContestLogin      *string               `json:"contest_login"`
	ContestVisibility NullContestVisibility `json:"contest_visibility"`
	OrganizationLogin string                `json:"organization_login"`
	UpdatedAt         time.Time             `json:"updated_at"`
	CreatedAt         time.Time             `json:"created_at"`
}

func (q *Queries) GetSubmission(ctx context.Context, id uuid.UUID) (GetSubmissionRow, error) {
	row := q.db.QueryRow(ctx, getSubmission, id)
	var i GetSubmissionRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Username,
		&i.Source,
		&i.State,
		&i.Score,
		&i.Penalty,
		&i.TimeStat,
		&i.MemoryStat,
		&i.Language,
		&i.FailedTest,
		&i.TestDetails,
		&i.BanReason,
		&i.ProblemID,
		&i.ProblemTitle,
		&i.ProblemShortName,
		&i.ProblemOrdinal,
		&i.ContestID,
		&i.ContestTitle,
		&i.ContestLogin,
		&i.ContestVisibility,
		&i.OrganizationLogin,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listSubmissions = `-- name: ListSubmissions :many
SELECT s.id,
  s.owner_id,
  u.username,
  s.state,
  s.score,
  s.penalty,
  COALESCE((s.test_details->>'time_stat')::integer, 0)::integer AS time_stat,
  COALESCE((s.test_details->>'memory_stat')::integer, 0)::integer AS memory_stat,
  s.language,
  (s.test_details->>'failed_test')::integer AS failed_test,
  s.ban_reason,
  s.problem_id,
  p.title AS problem_title,
  p.short_name AS problem_short_name,
  cp.ordinal AS problem_ordinal,
  s.contest_id,
  c.title AS contest_title,
  c.login AS contest_login,
  COALESCE(oc.login, op.login, '')::text AS organization_login,
  s.updated_at,
  s.created_at
FROM submissions s
  LEFT JOIN users u ON s.owner_id = u.id
  LEFT JOIN problems p ON s.problem_id = p.id
  LEFT JOIN organizations op ON p.organization_id = op.id
  LEFT JOIN contest_problems cp ON p.id = cp.problem_id
  AND cp.contest_id = s.contest_id
  LEFT JOIN contests c ON s.contest_id = c.id
  LEFT JOIN organizations oc ON c.organization_id = oc.id
WHERE (
    $1::uuid IS NULL
    OR s.contest_id = $1::uuid
  )
  AND (
    $2::uuid IS NULL
    OR s.owner_id = $2::uuid
  )
  AND (
    $3::uuid IS NULL
    OR s.problem_id = $3::uuid
  )
  AND (
    $4::integer IS NULL
    OR s.language = $4::integer
  )
  AND (
    $5::integer IS NULL
    OR s.state = $5::integer
  )
ORDER BY CASE
    WHEN $6::int < 0 THEN s.created_at
  END DESC,
  CASE
    WHEN $6::int >= 0 THEN s.created_at
  END ASC
LIMIT $8 OFFSET $7
`

type ListSubmissionsParams struct {
	ContestID pgtype.UUID `json:"contest_id"`
	OwnerID   pgtype.UUID `json:"owner_id"`
	ProblemID pgtype.UUID `json:"problem_id"`
	Language  *int32      `json:"language"`
	State     *int32      `json:"state"`
	SortOrder *int32      `json:"sort_order"`
	Offset    int32       `json:"offset"`
	Limit     int32       `json:"limit"`
}

type ListSubmissionsRow struct {
	ID                uuid.UUID           `json:"id"`
	OwnerID           pgtype.UUID         `json:"owner_id"`
	Username          *string             `json:"username"`
	State             models.State        `json:"state"`
	Score             int32               `json:"score"`
	Penalty           int32               `json:"penalty"`
	TimeStat          int32               `json:"time_stat"`
	MemoryStat        int32               `json:"memory_stat"`
	Language          models.LanguageName `json:"language"`
	FailedTest        int32               `json:"failed_test"`
	BanReason         *string             `json:"ban_reason"`
	ProblemID         pgtype.UUID         `json:"problem_id"`
	ProblemTitle      *string             `json:"problem_title"`
	ProblemShortName  *string             `json:"problem_short_name"`
	ProblemOrdinal    *int32              `json:"problem_ordinal"`
	ContestID         pgtype.UUID         `json:"contest_id"`
	ContestTitle      *string             `json:"contest_title"`
	ContestLogin      *string             `json:"contest_login"`
	OrganizationLogin string              `json:"organization_login"`
	UpdatedAt         time.Time           `json:"updated_at"`
	CreatedAt         time.Time           `json:"created_at"`
}

// Submission listing
func (q *Queries) ListSubmissions(ctx context.Context, arg ListSubmissionsParams) ([]ListSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, listSubmissions,
		arg.ContestID,
		arg.OwnerID,
		arg.ProblemID,
		arg.Language,
		arg.State,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubmissionsRow{}
	for rows.Next() {
		var i ListSubmissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Username,
			&i.State,
			&i.Score,
			&i.Penalty,
			&i.TimeStat,
			&i.MemoryStat,
			&i.Language,
			&i.FailedTest,
			&i.BanReason,
			&i.ProblemID,
			&i.ProblemTitle,
			&i.ProblemShortName,
			&i.ProblemOrdinal,
			&i.ContestID,
			&i.ContestTitle,
			&i.ContestLogin,
			&i.OrganizationLogin,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetSubmissionsState = `-- name: ResetSubmissionsState :many
UPDATE submissions
SET state = 1,
  score = 0,
  test_details = NULL,
  ban_reason = NULL,
  updated_at = NOW()
WHERE contest_id = $1::uuid
  AND (
    $2::uuid IS NULL
    OR problem_id = $2::uuid
  )
  AND (
    $3::uuid IS NULL
    OR id = $3::uuid
  )
  AND (
    $4::uuid IS NULL
    OR owner_id = $4::uuid
  )
RETURNING id
`

type ResetSubmissionsStateParams struct {
	ContestID    uuid.UUID   `json:"contest_id"`
	ProblemID    pgtype.UUID `json:"problem_id"`
	SubmissionID pgtype.UUID `json:"submission_id"`
	OwnerID      pgtype.UUID `json:"owner_id"`
}

func (q *Queries) ResetSubmissionsState(ctx context.Context, arg ResetSubmissionsStateParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, resetSubmissionsState,
		arg.ContestID,
		arg.ProblemID,
		arg.SubmissionID,
		arg.OwnerID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubmission = `-- name: UpdateSubmission :exec
UPDATE submissions
SET state = $1,
  score = $2,
  test_details = $3
WHERE id = $4::uuid
`

type UpdateSubmissionParams struct {
	State       models.State `json:"state"`
	Score       int32        `json:"score"`
	TestDetails []byte       `json:"test_details"`
	ID          uuid.UUID    `json:"id"`
}

func (q *Queries) UpdateSubmission(ctx context.Context, arg UpdateSubmissionParams) error {
	_, err := q.db.Exec(ctx, updateSubmission,
		arg.State,
		arg.Score,
		arg.TestDetails,
		arg.ID,
	)
	return err
}
