// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)::int4
FROM users
WHERE (
        $1::text = ''
        OR word_similarity(username, $1) > 0.1
    )
    AND (
        $2::text = ''
        OR role::text = $2
    )
`

type CountUsersParams struct {
	Search string `json:"search"`
	Role   string `json:"role"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Search, arg.Role)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
        id,
        username,
        role,
        password_hash,
        email,
        avatar_url
    )
VALUES (
        $1::uuid,
        $2,
        $3,
        $4,
        $5,
        $6
    )
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	Role         UserRole  `json:"role"`
	PasswordHash string    `json:"password_hash"`
	Email        string    `json:"email"`
	AvatarUrl    *string   `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Role,
		arg.PasswordHash,
		arg.Email,
		arg.AvatarUrl,
	)
	return err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, role, email, avatar_url, created_at, updated_at, password_hash
FROM users
WHERE id = $1::uuid
LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, role, email, avatar_url, created_at, updated_at, password_hash
FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByUsernameOrEmail = `-- name: GetUserByUsernameOrEmail :one
SELECT id, username, role, email, avatar_url, created_at, updated_at, password_hash
FROM users
WHERE username = $1 OR email = $1
LIMIT 1
`

func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, identifier string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsernameOrEmail, identifier)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Role,
		&i.Email,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, role, email, avatar_url, created_at, updated_at, password_hash
FROM users
WHERE (
        $1::text = ''
        OR word_similarity(username, $1) > 0.1
    )
    AND (
        $2::text = ''
        OR role::text = $2
    )
ORDER BY CASE
        WHEN $1 != '' THEN word_similarity(username, $1)
    END DESC NULLS LAST,
    created_at DESC
LIMIT $4 OFFSET $3
`

type ListUsersParams struct {
	Search string `json:"search"`
	Role   string `json:"role"`
	Offset int32  `json:"offset"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Search,
		arg.Role,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Role,
			&i.Email,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET username = COALESCE($1, username),
    role = COALESCE($2, role),
    email = COALESCE($3, email),
    avatar_url = COALESCE($4, avatar_url)
WHERE id = $5::uuid
`

type UpdateUserParams struct {
	Username  *string   `json:"username"`
	Role      *UserRole `json:"role"`
	Email     *string   `json:"email"`
	AvatarUrl *string   `json:"avatar_url"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Username,
		arg.Role,
		arg.Email,
		arg.AvatarUrl,
		arg.ID,
	)
	return err
}
