// Package corev1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package corev1

import (
	"fmt"
	"net/url"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ContestModel defines model for ContestModel.
type ContestModel struct {
	CreatedAt              time.Time          `json:"created_at"`
	CreatedBy              openapi_types.UUID `json:"created_by"`
	Description            string             `json:"description"`
	Id                     openapi_types.UUID `json:"id"`
	MonitorScope           string             `json:"monitor_scope"`
	SubmissionsListScope   string             `json:"submissions_list_scope"`
	SubmissionsReviewScope string             `json:"submissions_review_scope"`
	Title                  string             `json:"title"`
	UpdatedAt              time.Time          `json:"updated_at"`
	Visibility             string             `json:"visibility"`
}

// ContestProblemListItemModel defines model for ContestProblemListItemModel.
type ContestProblemListItemModel struct {
	CreatedAt   time.Time          `json:"created_at"`
	MemoryLimit int64              `json:"memory_limit"`
	Position    int64              `json:"position"`
	ProblemId   openapi_types.UUID `json:"problem_id"`
	TimeLimit   int64              `json:"time_limit"`
	Title       string             `json:"title"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// ContestProblemModel defines model for ContestProblemModel.
type ContestProblemModel struct {
	CreatedAt        time.Time          `json:"created_at"`
	InputFormatHtml  string             `json:"input_format_html"`
	LegendHtml       string             `json:"legend_html"`
	MemoryLimit      int64              `json:"memory_limit"`
	NotesHtml        string             `json:"notes_html"`
	OutputFormatHtml string             `json:"output_format_html"`
	Position         int64              `json:"position"`
	ProblemId        openapi_types.UUID `json:"problem_id"`
	ScoringHtml      string             `json:"scoring_html"`
	TimeLimit        int64              `json:"time_limit"`
	Title            string             `json:"title"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

// CreateSubmissionRequestModel defines model for CreateSubmissionRequestModel.
type CreateSubmissionRequestModel struct {
	Submission string `json:"submission"`
}

// CreationResponseModel defines model for CreationResponseModel.
type CreationResponseModel struct {
	Id openapi_types.UUID `json:"id"`
}

// GetContestProblemResponseModel defines model for GetContestProblemResponseModel.
type GetContestProblemResponseModel struct {
	Problem ContestProblemModel `json:"problem"`
}

// GetContestResponseModel defines model for GetContestResponseModel.
type GetContestResponseModel struct {
	Contest  ContestModel                  `json:"contest"`
	Problems []ContestProblemListItemModel `json:"problems"`
}

// GetHealthResponseModel defines model for GetHealthResponseModel.
type GetHealthResponseModel struct {
	Message string `json:"message"`
	Status  string `json:"status"`
}

// GetMyContestRoleResponseModel defines model for GetMyContestRoleResponseModel.
type GetMyContestRoleResponseModel struct {
	Role string `json:"role"`
}

// GetProblemResponseModel defines model for GetProblemResponseModel.
type GetProblemResponseModel struct {
	Problem ProblemModel `json:"problem"`
}

// GetSubmissionResponseModel defines model for GetSubmissionResponseModel.
type GetSubmissionResponseModel struct {
	Submission SubmissionModel `json:"submission"`
}

// GetUserResponseModel defines model for GetUserResponseModel.
type GetUserResponseModel struct {
	User UserModel `json:"user"`
}

// ListContestsResponseModel defines model for ListContestsResponseModel.
type ListContestsResponseModel struct {
	Contests   []ContestModel  `json:"contests"`
	Pagination PaginationModel `json:"pagination"`
}

// ListProblemsResponseModel defines model for ListProblemsResponseModel.
type ListProblemsResponseModel struct {
	Pagination PaginationModel         `json:"pagination"`
	Problems   []ProblemsListItemModel `json:"problems"`
}

// ListSubmissionsResponseModel defines model for ListSubmissionsResponseModel.
type ListSubmissionsResponseModel struct {
	AccessToken *string                    `json:"access-token,omitempty"`
	Pagination  PaginationModel            `json:"pagination"`
	Submissions []SubmissionsListItemModel `json:"submissions"`
}

// ListUsersResponseModel defines model for ListUsersResponseModel.
type ListUsersResponseModel struct {
	Pagination PaginationModel `json:"pagination"`
	Users      []UserModel     `json:"users"`
}

// PaginationModel defines model for PaginationModel.
type PaginationModel struct {
	Page  int64 `json:"page"`
	Total int64 `json:"total"`
}

// ProblemModel defines model for ProblemModel.
type ProblemModel struct {
	CreatedAt        time.Time          `json:"created_at"`
	CreatedBy        openapi_types.UUID `json:"created_by"`
	Id               openapi_types.UUID `json:"id"`
	InputFormat      string             `json:"input_format"`
	InputFormatHtml  string             `json:"input_format_html"`
	IsPrivate        *bool              `json:"is_private,omitempty"`
	Legend           string             `json:"legend"`
	LegendHtml       string             `json:"legend_html"`
	MemoryLimit      int64              `json:"memory_limit"`
	Notes            string             `json:"notes"`
	NotesHtml        string             `json:"notes_html"`
	OutputFormat     string             `json:"output_format"`
	OutputFormatHtml string             `json:"output_format_html"`
	Scoring          string             `json:"scoring"`
	ScoringHtml      string             `json:"scoring_html"`
	TimeLimit        int64              `json:"time_limit"`
	Title            string             `json:"title"`
	UpdatedAt        time.Time          `json:"updated_at"`
	Visibility       string             `json:"visibility"`
}

// ProblemsListItemModel defines model for ProblemsListItemModel.
type ProblemsListItemModel struct {
	CreatedAt   time.Time          `json:"created_at"`
	Id          openapi_types.UUID `json:"id"`
	MemoryLimit int64              `json:"memory_limit"`
	TimeLimit   int64              `json:"time_limit"`
	Title       string             `json:"title"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

// SubmissionModel defines model for SubmissionModel.
type SubmissionModel struct {
	ContestId    openapi_types.UUID `json:"contest_id"`
	ContestTitle string             `json:"contest_title"`
	CreatedAt    time.Time          `json:"created_at"`
	Id           openapi_types.UUID `json:"id"`
	Language     int64              `json:"language"`
	MemoryStat   int64              `json:"memory_stat"`
	Penalty      int64              `json:"penalty"`
	Position     int64              `json:"position"`
	ProblemId    openapi_types.UUID `json:"problem_id"`
	ProblemTitle string             `json:"problem_title"`
	Score        int64              `json:"score"`
	State        int64              `json:"state"`
	Submission   string             `json:"submission"`
	TimeStat     int64              `json:"time_stat"`
	UpdatedAt    time.Time          `json:"updated_at"`
	UserId       openapi_types.UUID `json:"user_id"`
	Username     string             `json:"username"`
}

// SubmissionsListItemModel defines model for SubmissionsListItemModel.
type SubmissionsListItemModel struct {
	ContestId    openapi_types.UUID `json:"contest_id"`
	ContestTitle string             `json:"contest_title"`
	CreatedAt    time.Time          `json:"created_at"`
	Id           openapi_types.UUID `json:"id"`
	Language     int64              `json:"language"`
	MemoryStat   int64              `json:"memory_stat"`
	Penalty      int64              `json:"penalty"`
	Position     int64              `json:"position"`
	ProblemId    openapi_types.UUID `json:"problem_id"`
	ProblemTitle string             `json:"problem_title"`
	Score        int64              `json:"score"`
	State        int64              `json:"state"`
	TimeStat     int64              `json:"time_stat"`
	UpdatedAt    time.Time          `json:"updated_at"`
	UserId       openapi_types.UUID `json:"user_id"`
	Username     string             `json:"username"`
}

// UpdateContestRequestModel defines model for UpdateContestRequestModel.
type UpdateContestRequestModel struct {
	Description            *string `json:"description,omitempty"`
	MonitorScope           *string `json:"monitor_scope,omitempty"`
	SubmissionsListScope   *string `json:"submissions_list_scope,omitempty"`
	SubmissionsReviewScope *string `json:"submissions_review_scope,omitempty"`
	Title                  *string `json:"title,omitempty"`
	Visibility             *string `json:"visibility,omitempty"`
}

// UpdateProblemRequestModel defines model for UpdateProblemRequestModel.
type UpdateProblemRequestModel struct {
	InputFormat  *string `json:"input_format,omitempty"`
	Legend       *string `json:"legend,omitempty"`
	MemoryLimit  *int64  `json:"memory_limit,omitempty"`
	Notes        *string `json:"notes,omitempty"`
	OutputFormat *string `json:"output_format,omitempty"`
	Scoring      *string `json:"scoring,omitempty"`
	TimeLimit    *int64  `json:"time_limit,omitempty"`
	Title        *string `json:"title,omitempty"`
	Visibility   *string `json:"visibility,omitempty"`
}

// UserModel defines model for UserModel.
type UserModel struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Role      string             `json:"role"`
	UpdatedAt time.Time          `json:"updatedAt"`
	Username  string             `json:"username"`
}

// ListContestsParams defines parameters for ListContests.
type ListContestsParams struct {
	Page       int64   `form:"page" json:"page"`
	PageSize   int64   `form:"pageSize" json:"pageSize"`
	Search     *string `form:"search,omitempty" json:"search,omitempty"`
	Owner      *bool   `form:"owner,omitempty" json:"owner,omitempty"`
	Descending *bool   `form:"descending,omitempty" json:"descending,omitempty"`
}

// CreateContestParams defines parameters for CreateContest.
type CreateContestParams struct {
	Title string `form:"title" json:"title"`
}

// DeleteContestMemberParams defines parameters for DeleteContestMember.
type DeleteContestMemberParams struct {
	UserId openapi_types.UUID `form:"user_id" json:"user_id"`
}

// ListContestMembersParams defines parameters for ListContestMembers.
type ListContestMembersParams struct {
	Page     int64 `form:"page" json:"page"`
	PageSize int64 `form:"pageSize" json:"pageSize"`
}

// CreateContestMemberParams defines parameters for CreateContestMember.
type CreateContestMemberParams struct {
	UserId openapi_types.UUID `form:"user_id" json:"user_id"`
}

// CreateContestProblemParams defines parameters for CreateContestProblem.
type CreateContestProblemParams struct {
	ProblemId openapi_types.UUID `form:"problem_id" json:"problem_id"`
}

// ListProblemsParams defines parameters for ListProblems.
type ListProblemsParams struct {
	Page       int64   `form:"page" json:"page"`
	PageSize   int64   `form:"pageSize" json:"pageSize"`
	Search     *string `form:"search,omitempty" json:"search,omitempty"`
	Descending *bool   `form:"descending,omitempty" json:"descending,omitempty"`
	Owner      *bool   `form:"owner,omitempty" json:"owner,omitempty"`
}

// CreateProblemParams defines parameters for CreateProblem.
type CreateProblemParams struct {
	Title string `form:"title" json:"title"`
}

// ListSubmissionsParams defines parameters for ListSubmissions.
type ListSubmissionsParams struct {
	Page      int64               `form:"page" json:"page"`
	PageSize  int64               `form:"pageSize" json:"pageSize"`
	ContestId *openapi_types.UUID `form:"contestId,omitempty" json:"contestId,omitempty"`
	UserId    *openapi_types.UUID `form:"userId,omitempty" json:"userId,omitempty"`
	ProblemId *openapi_types.UUID `form:"problemId,omitempty" json:"problemId,omitempty"`
	State     *int64              `form:"state,omitempty" json:"state,omitempty"`
	Order     *int64              `form:"order,omitempty" json:"order,omitempty"`
	Language  *int64              `form:"language,omitempty" json:"language,omitempty"`
}

// CreateSubmissionParams defines parameters for CreateSubmission.
type CreateSubmissionParams struct {
	ProblemId openapi_types.UUID `form:"problem_id" json:"problem_id"`
	ContestId openapi_types.UUID `form:"contest_id" json:"contest_id"`
	Language  int64              `form:"language" json:"language"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	Page     int64   `form:"page" json:"page"`
	PageSize int64   `form:"pageSize" json:"pageSize"`
	Search   *string `form:"search,omitempty" json:"search,omitempty"`
	Role     *string `form:"role,omitempty" json:"role,omitempty"`
}

// UpdateContestJSONRequestBody defines body for UpdateContest for application/json ContentType.
type UpdateContestJSONRequestBody = UpdateContestRequestModel

// UpdateProblemJSONRequestBody defines body for UpdateProblem for application/json ContentType.
type UpdateProblemJSONRequestBody = UpdateProblemRequestModel

// CreateSubmissionJSONRequestBody defines body for CreateSubmission for application/json ContentType.
type CreateSubmissionJSONRequestBody = CreateSubmissionRequestModel

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /contests)
	ListContests(c *fiber.Ctx, params ListContestsParams) error

	// (POST /contests)
	CreateContest(c *fiber.Ctx, params CreateContestParams) error

	// (DELETE /contests/{contest_id})
	DeleteContest(c *fiber.Ctx, contestId openapi_types.UUID) error

	// (GET /contests/{contest_id})
	GetContest(c *fiber.Ctx, contestId openapi_types.UUID) error

	// (PATCH /contests/{contest_id})
	UpdateContest(c *fiber.Ctx, contestId openapi_types.UUID) error

	// (DELETE /contests/{contest_id}/members)
	DeleteContestMember(c *fiber.Ctx, contestId openapi_types.UUID, params DeleteContestMemberParams) error

	// (GET /contests/{contest_id}/members)
	ListContestMembers(c *fiber.Ctx, contestId openapi_types.UUID, params ListContestMembersParams) error

	// (POST /contests/{contest_id}/members)
	CreateContestMember(c *fiber.Ctx, contestId openapi_types.UUID, params CreateContestMemberParams) error

	// (GET /contests/{contest_id}/my-role)
	GetMyContestRole(c *fiber.Ctx, contestId openapi_types.UUID) error

	// (POST /contests/{contest_id}/problems)
	CreateContestProblem(c *fiber.Ctx, contestId openapi_types.UUID, params CreateContestProblemParams) error

	// (DELETE /contests/{contest_id}/problems/{problem_id})
	DeleteContestProblem(c *fiber.Ctx, contestId openapi_types.UUID, problemId openapi_types.UUID) error

	// (GET /contests/{contest_id}/problems/{problem_id})
	GetContestProblem(c *fiber.Ctx, contestId openapi_types.UUID, problemId openapi_types.UUID) error

	// (GET /health)
	GetHealth(c *fiber.Ctx) error

	// (GET /problems)
	ListProblems(c *fiber.Ctx, params ListProblemsParams) error

	// (POST /problems)
	CreateProblem(c *fiber.Ctx, params CreateProblemParams) error

	// (DELETE /problems/{id})
	DeleteProblem(c *fiber.Ctx, id openapi_types.UUID) error

	// (GET /problems/{id})
	GetProblem(c *fiber.Ctx, id openapi_types.UUID) error

	// (PATCH /problems/{id})
	UpdateProblem(c *fiber.Ctx, id openapi_types.UUID) error

	// (GET /submissions)
	ListSubmissions(c *fiber.Ctx, params ListSubmissionsParams) error

	// (POST /submissions)
	CreateSubmission(c *fiber.Ctx, params CreateSubmissionParams) error

	// (GET /submissions/{submission_id})
	GetSubmission(c *fiber.Ctx, submissionId openapi_types.UUID) error

	// (GET /users)
	ListUsers(c *fiber.Ctx, params ListUsersParams) error

	// (GET /users/{id})
	GetUser(c *fiber.Ctx, id openapi_types.UUID) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// ListContests operation middleware
func (siw *ServerInterfaceWrapper) ListContests(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListContestsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "page" -------------

	if paramValue := c.Query("page"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument page is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Required query parameter "pageSize" -------------

	if paramValue := c.Query("pageSize"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument pageSize is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "pageSize", query, &params.PageSize)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter pageSize: %w", err).Error())
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", query, &params.Search)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter search: %w", err).Error())
	}

	// ------------- Optional query parameter "owner" -------------

	err = runtime.BindQueryParameter("form", true, false, "owner", query, &params.Owner)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter owner: %w", err).Error())
	}

	// ------------- Optional query parameter "descending" -------------

	err = runtime.BindQueryParameter("form", true, false, "descending", query, &params.Descending)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter descending: %w", err).Error())
	}

	return siw.Handler.ListContests(c, params)
}

// CreateContest operation middleware
func (siw *ServerInterfaceWrapper) CreateContest(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateContestParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "title" -------------

	if paramValue := c.Query("title"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument title is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "title", query, &params.Title)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter title: %w", err).Error())
	}

	return siw.Handler.CreateContest(c, params)
}

// DeleteContest operation middleware
func (siw *ServerInterfaceWrapper) DeleteContest(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "contest_id" -------------
	var contestId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "contest_id", c.Params("contest_id"), &contestId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter contest_id: %w", err).Error())
	}

	return siw.Handler.DeleteContest(c, contestId)
}

// GetContest operation middleware
func (siw *ServerInterfaceWrapper) GetContest(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "contest_id" -------------
	var contestId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "contest_id", c.Params("contest_id"), &contestId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter contest_id: %w", err).Error())
	}

	return siw.Handler.GetContest(c, contestId)
}

// UpdateContest operation middleware
func (siw *ServerInterfaceWrapper) UpdateContest(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "contest_id" -------------
	var contestId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "contest_id", c.Params("contest_id"), &contestId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter contest_id: %w", err).Error())
	}

	return siw.Handler.UpdateContest(c, contestId)
}

// DeleteContestMember operation middleware
func (siw *ServerInterfaceWrapper) DeleteContestMember(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "contest_id" -------------
	var contestId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "contest_id", c.Params("contest_id"), &contestId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter contest_id: %w", err).Error())
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteContestMemberParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "user_id" -------------

	if paramValue := c.Query("user_id"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument user_id is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "user_id", query, &params.UserId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter user_id: %w", err).Error())
	}

	return siw.Handler.DeleteContestMember(c, contestId, params)
}

// ListContestMembers operation middleware
func (siw *ServerInterfaceWrapper) ListContestMembers(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "contest_id" -------------
	var contestId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "contest_id", c.Params("contest_id"), &contestId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter contest_id: %w", err).Error())
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListContestMembersParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "page" -------------

	if paramValue := c.Query("page"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument page is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Required query parameter "pageSize" -------------

	if paramValue := c.Query("pageSize"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument pageSize is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "pageSize", query, &params.PageSize)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter pageSize: %w", err).Error())
	}

	return siw.Handler.ListContestMembers(c, contestId, params)
}

// CreateContestMember operation middleware
func (siw *ServerInterfaceWrapper) CreateContestMember(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "contest_id" -------------
	var contestId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "contest_id", c.Params("contest_id"), &contestId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter contest_id: %w", err).Error())
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateContestMemberParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "user_id" -------------

	if paramValue := c.Query("user_id"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument user_id is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "user_id", query, &params.UserId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter user_id: %w", err).Error())
	}

	return siw.Handler.CreateContestMember(c, contestId, params)
}

// GetMyContestRole operation middleware
func (siw *ServerInterfaceWrapper) GetMyContestRole(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "contest_id" -------------
	var contestId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "contest_id", c.Params("contest_id"), &contestId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter contest_id: %w", err).Error())
	}

	return siw.Handler.GetMyContestRole(c, contestId)
}

// CreateContestProblem operation middleware
func (siw *ServerInterfaceWrapper) CreateContestProblem(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "contest_id" -------------
	var contestId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "contest_id", c.Params("contest_id"), &contestId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter contest_id: %w", err).Error())
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateContestProblemParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "problem_id" -------------

	if paramValue := c.Query("problem_id"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument problem_id is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "problem_id", query, &params.ProblemId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter problem_id: %w", err).Error())
	}

	return siw.Handler.CreateContestProblem(c, contestId, params)
}

// DeleteContestProblem operation middleware
func (siw *ServerInterfaceWrapper) DeleteContestProblem(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "contest_id" -------------
	var contestId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "contest_id", c.Params("contest_id"), &contestId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter contest_id: %w", err).Error())
	}

	// ------------- Path parameter "problem_id" -------------
	var problemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "problem_id", c.Params("problem_id"), &problemId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter problem_id: %w", err).Error())
	}

	return siw.Handler.DeleteContestProblem(c, contestId, problemId)
}

// GetContestProblem operation middleware
func (siw *ServerInterfaceWrapper) GetContestProblem(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "contest_id" -------------
	var contestId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "contest_id", c.Params("contest_id"), &contestId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter contest_id: %w", err).Error())
	}

	// ------------- Path parameter "problem_id" -------------
	var problemId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "problem_id", c.Params("problem_id"), &problemId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter problem_id: %w", err).Error())
	}

	return siw.Handler.GetContestProblem(c, contestId, problemId)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *fiber.Ctx) error {

	return siw.Handler.GetHealth(c)
}

// ListProblems operation middleware
func (siw *ServerInterfaceWrapper) ListProblems(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProblemsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "page" -------------

	if paramValue := c.Query("page"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument page is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Required query parameter "pageSize" -------------

	if paramValue := c.Query("pageSize"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument pageSize is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "pageSize", query, &params.PageSize)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter pageSize: %w", err).Error())
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", query, &params.Search)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter search: %w", err).Error())
	}

	// ------------- Optional query parameter "descending" -------------

	err = runtime.BindQueryParameter("form", true, false, "descending", query, &params.Descending)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter descending: %w", err).Error())
	}

	// ------------- Optional query parameter "owner" -------------

	err = runtime.BindQueryParameter("form", true, false, "owner", query, &params.Owner)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter owner: %w", err).Error())
	}

	return siw.Handler.ListProblems(c, params)
}

// CreateProblem operation middleware
func (siw *ServerInterfaceWrapper) CreateProblem(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateProblemParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "title" -------------

	if paramValue := c.Query("title"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument title is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "title", query, &params.Title)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter title: %w", err).Error())
	}

	return siw.Handler.CreateProblem(c, params)
}

// DeleteProblem operation middleware
func (siw *ServerInterfaceWrapper) DeleteProblem(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.DeleteProblem(c, id)
}

// GetProblem operation middleware
func (siw *ServerInterfaceWrapper) GetProblem(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.GetProblem(c, id)
}

// UpdateProblem operation middleware
func (siw *ServerInterfaceWrapper) UpdateProblem(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.UpdateProblem(c, id)
}

// ListSubmissions operation middleware
func (siw *ServerInterfaceWrapper) ListSubmissions(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSubmissionsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "page" -------------

	if paramValue := c.Query("page"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument page is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Required query parameter "pageSize" -------------

	if paramValue := c.Query("pageSize"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument pageSize is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "pageSize", query, &params.PageSize)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter pageSize: %w", err).Error())
	}

	// ------------- Optional query parameter "contestId" -------------

	err = runtime.BindQueryParameter("form", true, false, "contestId", query, &params.ContestId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter contestId: %w", err).Error())
	}

	// ------------- Optional query parameter "userId" -------------

	err = runtime.BindQueryParameter("form", true, false, "userId", query, &params.UserId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter userId: %w", err).Error())
	}

	// ------------- Optional query parameter "problemId" -------------

	err = runtime.BindQueryParameter("form", true, false, "problemId", query, &params.ProblemId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter problemId: %w", err).Error())
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", query, &params.State)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter state: %w", err).Error())
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", query, &params.Order)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter order: %w", err).Error())
	}

	// ------------- Optional query parameter "language" -------------

	err = runtime.BindQueryParameter("form", true, false, "language", query, &params.Language)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter language: %w", err).Error())
	}

	return siw.Handler.ListSubmissions(c, params)
}

// CreateSubmission operation middleware
func (siw *ServerInterfaceWrapper) CreateSubmission(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateSubmissionParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "problem_id" -------------

	if paramValue := c.Query("problem_id"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument problem_id is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "problem_id", query, &params.ProblemId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter problem_id: %w", err).Error())
	}

	// ------------- Required query parameter "contest_id" -------------

	if paramValue := c.Query("contest_id"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument contest_id is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "contest_id", query, &params.ContestId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter contest_id: %w", err).Error())
	}

	// ------------- Required query parameter "language" -------------

	if paramValue := c.Query("language"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument language is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "language", query, &params.Language)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter language: %w", err).Error())
	}

	return siw.Handler.CreateSubmission(c, params)
}

// GetSubmission operation middleware
func (siw *ServerInterfaceWrapper) GetSubmission(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "submission_id" -------------
	var submissionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "submission_id", c.Params("submission_id"), &submissionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter submission_id: %w", err).Error())
	}

	return siw.Handler.GetSubmission(c, submissionId)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "page" -------------

	if paramValue := c.Query("page"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument page is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "page", query, &params.Page)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter page: %w", err).Error())
	}

	// ------------- Required query parameter "pageSize" -------------

	if paramValue := c.Query("pageSize"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument pageSize is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "pageSize", query, &params.PageSize)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter pageSize: %w", err).Error())
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", query, &params.Search)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter search: %w", err).Error())
	}

	// ------------- Optional query parameter "role" -------------

	err = runtime.BindQueryParameter("form", true, false, "role", query, &params.Role)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter role: %w", err).Error())
	}

	return siw.Handler.ListUsers(c, params)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.GetUser(c, id)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/contests", wrapper.ListContests)

	router.Post(options.BaseURL+"/contests", wrapper.CreateContest)

	router.Delete(options.BaseURL+"/contests/:contest_id", wrapper.DeleteContest)

	router.Get(options.BaseURL+"/contests/:contest_id", wrapper.GetContest)

	router.Patch(options.BaseURL+"/contests/:contest_id", wrapper.UpdateContest)

	router.Delete(options.BaseURL+"/contests/:contest_id/members", wrapper.DeleteContestMember)

	router.Get(options.BaseURL+"/contests/:contest_id/members", wrapper.ListContestMembers)

	router.Post(options.BaseURL+"/contests/:contest_id/members", wrapper.CreateContestMember)

	router.Get(options.BaseURL+"/contests/:contest_id/my-role", wrapper.GetMyContestRole)

	router.Post(options.BaseURL+"/contests/:contest_id/problems", wrapper.CreateContestProblem)

	router.Delete(options.BaseURL+"/contests/:contest_id/problems/:problem_id", wrapper.DeleteContestProblem)

	router.Get(options.BaseURL+"/contests/:contest_id/problems/:problem_id", wrapper.GetContestProblem)

	router.Get(options.BaseURL+"/health", wrapper.GetHealth)

	router.Get(options.BaseURL+"/problems", wrapper.ListProblems)

	router.Post(options.BaseURL+"/problems", wrapper.CreateProblem)

	router.Delete(options.BaseURL+"/problems/:id", wrapper.DeleteProblem)

	router.Get(options.BaseURL+"/problems/:id", wrapper.GetProblem)

	router.Patch(options.BaseURL+"/problems/:id", wrapper.UpdateProblem)

	router.Get(options.BaseURL+"/submissions", wrapper.ListSubmissions)

	router.Post(options.BaseURL+"/submissions", wrapper.CreateSubmission)

	router.Get(options.BaseURL+"/submissions/:submission_id", wrapper.GetSubmission)

	router.Get(options.BaseURL+"/users", wrapper.ListUsers)

	router.Get(options.BaseURL+"/users/:id", wrapper.GetUser)

}
