// Code generated by ogen, DO NOT EDIT.
package corev1

type CreatePostRes interface {
	createPostRes()
}

type DeletePostByIdRes interface {
	deletePostByIdRes()
}

type GetPostByIdRes interface {
	getPostByIdRes()
}

type GetPostImageRes interface {
	getPostImageRes()
}

type GetUserAvatarRes interface {
	getUserAvatarRes()
}

type PatchPostByIdRes interface {
	patchPostByIdRes()
}
