version: v1.3.1

log:
  level: debug
  format: json
  leak_sensitive_values: true

serve:
  public:
    base_url: https://dev.gate149.ru/
    cors:
      enabled: true
      allowed_origins:
        - https://dev.gate149.ru
        - http://localhost:3000
        - http://localhost:3001
        - http://localhost:3002
      allowed_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
      allowed_headers:
        - Authorization
        - Content-Type
        - Cookie
        - Origin
        - Credentials
      exposed_headers:
        - Set-Cookie
        - Content-Type
      allow_credentials: true
      debug: true
  admin:
    base_url: https://dev.gate149.ru/kratos/admin/

session:
  cookie:
    same_site: Lax
    domain: dev.gate149.ru
    path: /
    secure: true

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

selfservice:
  default_browser_return_url: https://dev.gate149.ru/
  allowed_return_urls:
    - https://dev.gate149.ru/
    - http://localhost:3000/
    - http://localhost:3001/
    - http://localhost:3002/
    - /
    - /auth/login
  flows:
    error:
      ui_url: /error
    login:
      ui_url: /auth/login
    registration:
      ui_url: /auth/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: web_hook
              config:
                url: http://backend:8081/webhook/kratos
                method: POST
                body: file:///etc/config/kratos/webhook_body.jsonnet
                response:
                  ignore: true
                headers:
                  Content-Type: application/json
    verification:
      ui_url: /auth/verification
    recovery:
      ui_url: /auth/recovery
    settings:
      ui_url: /settings
    logout:
      after:
        default_browser_return_url: /auth/login

  methods:
    password:
      enabled: true
