apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: VictoriaMetrics
    access: proxy
    url: http://victoriametrics:8428/prometheus
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      timeInterval: 15s

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-2m"
        spanEndTimeShift: "2m"
        tags:
          - "service.name"
          - "job"
          - "instance"
        filterBySpanID: false
        filterByTraceID: true
      serviceMap:
        datasourceUid: VictoriaMetrics
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: loki

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: TraceID
          matcherRegex: '(?:trace_id|traceId|traceparent)[=:\s"]+(?:00-)?([0-9a-f]{32})'
          url: "$${__value.raw}"
          datasourceUid: tempo
          internal: true
