openapi: 3.0.3
info:
  title: ObserverService API
  version: 0.0.1
paths:
  /submissions:
    get:
      operationId: ObserveSubmissions
      parameters:
        - name: since
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: contestId
          in: query
          required: false
          schema:
            type: string
            format: uuid
        - name: userId
          in: query
          required: false
          schema:
            type: string
            format: uuid
        - name: problemId
          in: query
          required: false
          schema:
            type: string
            format: uuid
        - name: language
          in: query
          required: false
          schema:
            type: integer
            format: int32
      responses:
        "101":
          description: Switching protocols
components:
  schemas:
    SubmissionsWsCloseCode:
      type: integer
      format: int32
      enum:
        - 4408
        - 4409
        - 4410
      x-enum-varnames:
        - buffer_empty
        - history_lost
        - invalid_range
    SubmissionsWsCloseReason:
      type: string
      enum:
        - buffer_empty
        - history_lost
        - invalid_range
    SubmissionEventMeta:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
        username:
          type: string
        contest_id:
          type: string
          format: uuid
        contest_title:
          type: string
        problem_id:
          type: string
          format: uuid
        problem_title:
          type: string
        position:
          type: integer
          format: int32
        language:
          type: integer
          format: int32
        created_at:
          type: string
          format: date-time
    SubmissionsEventType:
      type: string
      enum:
        - submissions.created
        - submissions.queued
        - submissions.compiling_started
        - submissions.testing_started
        - submissions.test_started
        - submissions.completed
    SubmissionsMessage:
      type: object
      required:
        - event_type
        - payload
      properties:
        event_type:
          $ref: "#/components/schemas/SubmissionsEventType"
        payload:
          oneOf:
            - $ref: "#/components/schemas/MessageSubmissionCreated"
            - $ref: "#/components/schemas/MessageSubmissionQueued"
            - $ref: "#/components/schemas/MessageSubmissionCompilingStarted"
            - $ref: "#/components/schemas/MessageSubmissionTestingStarted"
            - $ref: "#/components/schemas/MessageSubmissionTestStarted"
            - $ref: "#/components/schemas/MessageSubmissionCompleted"
    MessageSubmissionCreated:
      allOf:
        - $ref: "#/components/schemas/SubmissionEventMeta"
        - type: object
          required:
            - id
            - state
            - source
          properties:
            id:
              type: string
              format: uuid
            state:
              type: integer
              format: int32
            source:
              type: string
    MessageSubmissionQueued:
      allOf:
        - $ref: "#/components/schemas/SubmissionEventMeta"
        - type: object
          required:
            - id
          properties:
            id:
              type: string
              format: uuid
    MessageSubmissionCompilingStarted:
      allOf:
        - $ref: "#/components/schemas/SubmissionEventMeta"
        - type: object
          required:
            - id
          properties:
            id:
              type: string
              format: uuid
    MessageSubmissionTestingStarted:
      allOf:
        - $ref: "#/components/schemas/SubmissionEventMeta"
        - type: object
          required:
            - id
          properties:
            id:
              type: string
              format: uuid
    MessageSubmissionTestStarted:
      allOf:
        - $ref: "#/components/schemas/SubmissionEventMeta"
        - type: object
          required:
            - id
            - number
          properties:
            id:
              type: string
              format: uuid
            number:
              type: integer
              format: int32
    MessageSubmissionCompleted:
      allOf:
        - $ref: "#/components/schemas/SubmissionEventMeta"
        - type: object
          required:
            - id
            - state
            - score
            - penalty
            - time_stat
            - memory_stat
          properties:
            id:
              type: string
              format: uuid
            state:
              type: integer
              format: int32
            score:
              type: integer
              format: int32
            penalty:
              type: integer
              format: int32
            time_stat:
              type: integer
              format: int32
            memory_stat:
              type: integer
              format: int32
