// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package contestssqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAccessRequests = `-- name: CountAccessRequests :one
SELECT COUNT(*)
FROM contest_access_requests
WHERE contest_id = $1::uuid
  AND ($2::text IS NULL OR status = $2::contest_access_request_status)
`

type CountAccessRequestsParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	Status    *string   `json:"status"`
}

func (q *Queries) CountAccessRequests(ctx context.Context, arg CountAccessRequestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccessRequests, arg.ContestID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminContests = `-- name: CountAdminContests :one
SELECT COUNT(*)
FROM contests c
WHERE (
    $1::text IS NULL
        OR $1 = ''
        OR (
        CASE
            WHEN LENGTH($1) < 3 THEN c.title ILIKE '%' || $1 || '%'
            ELSE word_similarity(c.title, $1) > 0.1
            END
        )
    )
  AND (
    $2::text IS NULL
        OR c.visibility = $2::contest_visibility
    )
`

type CountAdminContestsParams struct {
	Search     *string `json:"search"`
	Visibility *string `json:"visibility"`
}

func (q *Queries) CountAdminContests(ctx context.Context, arg CountAdminContestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminContests, arg.Search, arg.Visibility)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContestMembers = `-- name: CountContestMembers :one
SELECT COUNT(*)
FROM contest_members
WHERE contest_id = $1::uuid
`

func (q *Queries) CountContestMembers(ctx context.Context, contestID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countContestMembers, contestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContestMonitorRows = `-- name: CountContestMonitorRows :one
SELECT COUNT(DISTINCT cm.user_id)
FROM contest_members cm
WHERE cm.contest_id = $1::uuid
  AND cm.role = 'participant'
`

func (q *Queries) CountContestMonitorRows(ctx context.Context, contestID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countContestMonitorRows, contestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInvitations = `-- name: CountInvitations :one
SELECT COUNT(*)
FROM contest_invitations
WHERE contest_id = $1::uuid
  AND ($2::text IS NULL OR status = $2::contest_invitation_status)
`

type CountInvitationsParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	Status    *string   `json:"status"`
}

func (q *Queries) CountInvitations(ctx context.Context, arg CountInvitationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInvitations, arg.ContestID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicContests = `-- name: CountPublicContests :one
SELECT COUNT(*)
FROM contests c
WHERE c.visibility = 'public'
  AND (
    $1::text IS NULL
        OR $1 = ''
        OR (
        CASE
            WHEN LENGTH($1) < 3 THEN c.title ILIKE '%' || $1 || '%'
            ELSE word_similarity(c.title, $1) > 0.1
            END
        )
    )
`

func (q *Queries) CountPublicContests(ctx context.Context, search *string) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicContests, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserContests = `-- name: CountUserContests :one
SELECT COUNT(DISTINCT c.id)
FROM contests c
WHERE (
    -- Private contests where user is member
    (c.visibility = 'private' AND EXISTS(SELECT 1 FROM contest_members cm WHERE cm.contest_id = c.id AND cm.user_id = $1::uuid))
    OR
    -- Public contests where user is member OR has submissions
    (c.visibility = 'public' AND (
        EXISTS(SELECT 1 FROM contest_members cm WHERE cm.contest_id = c.id AND cm.user_id = $1::uuid)
        OR EXISTS(SELECT 1 FROM submissions sub WHERE sub.contest_id = c.id AND sub.created_by = $1::uuid)
    ))
)
  AND (
    $2::text IS NULL
        OR $2 = ''
        OR (
        CASE
            WHEN LENGTH($2) < 3 THEN c.title ILIKE '%' || $2 || '%'
            ELSE word_similarity(c.title, $2) > 0.1
            END
        )
    )
`

type CountUserContestsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Search *string   `json:"search"`
}

func (q *Queries) CountUserContests(ctx context.Context, arg CountUserContestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserContests, arg.UserID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkshopContests = `-- name: CountWorkshopContests :one
SELECT COUNT(DISTINCT c.id)
FROM contests c
INNER JOIN contest_members cm ON cm.contest_id = c.id
WHERE cm.user_id = $1::uuid
  AND cm.role IN ('owner', 'moderator')
  AND (
    $2::text IS NULL
        OR $2 = ''
        OR (
        CASE
            WHEN LENGTH($2) < 3 THEN c.title ILIKE '%' || $2 || '%'
            ELSE word_similarity(c.title, $2) > 0.1
            END
        )
    )
`

type CountWorkshopContestsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Search *string   `json:"search"`
}

func (q *Queries) CountWorkshopContests(ctx context.Context, arg CountWorkshopContestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkshopContests, arg.UserID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccessRequest = `-- name: CreateAccessRequest :one

INSERT INTO contest_access_requests (id, contest_id, user_id, status)
VALUES ($1::uuid, $2::uuid, $3::uuid, $4)
RETURNING id
`

type CreateAccessRequestParams struct {
	ID        uuid.UUID                  `json:"id"`
	ContestID uuid.UUID                  `json:"contest_id"`
	UserID    uuid.UUID                  `json:"user_id"`
	Status    ContestAccessRequestStatus `json:"status"`
}

// Contest Access Requests operations
func (q *Queries) CreateAccessRequest(ctx context.Context, arg CreateAccessRequestParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAccessRequest,
		arg.ID,
		arg.ContestID,
		arg.UserID,
		arg.Status,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createContest = `-- name: CreateContest :one

INSERT INTO contests (id, title, created_by)
VALUES ($1::uuid, $2, $3::uuid)
RETURNING id
`

type CreateContestParams struct {
	ID        uuid.UUID `json:"id"`
	Title     string    `json:"title"`
	CreatedBy uuid.UUID `json:"created_by"`
}

// Contest CRUD operations
func (q *Queries) CreateContest(ctx context.Context, arg CreateContestParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createContest, arg.ID, arg.Title, arg.CreatedBy)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createContestMember = `-- name: CreateContestMember :exec

INSERT INTO contest_members (contest_id, user_id, role)
VALUES ($1::uuid, $2::uuid, $3)
`

type CreateContestMemberParams struct {
	ContestID uuid.UUID   `json:"contest_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Role      ContestRole `json:"role"`
}

// Contest member operations
func (q *Queries) CreateContestMember(ctx context.Context, arg CreateContestMemberParams) error {
	_, err := q.db.Exec(ctx, createContestMember, arg.ContestID, arg.UserID, arg.Role)
	return err
}

const createContestProblem = `-- name: CreateContestProblem :exec

INSERT INTO contest_problem (problem_id, contest_id, position)
VALUES ($1::uuid,
        $2::uuid,
        COALESCE(
                (SELECT MAX(position)
                 FROM contest_problem
                 WHERE contest_id = $2::uuid),
                0
        ) + 1)
`

type CreateContestProblemParams struct {
	ProblemID uuid.UUID `json:"problem_id"`
	ContestID uuid.UUID `json:"contest_id"`
}

// Contest problem operations
func (q *Queries) CreateContestProblem(ctx context.Context, arg CreateContestProblemParams) error {
	_, err := q.db.Exec(ctx, createContestProblem, arg.ProblemID, arg.ContestID)
	return err
}

const createInvitation = `-- name: CreateInvitation :one

INSERT INTO contest_invitations (id, contest_id, user_id, invited_by, status)
VALUES ($1::uuid, $2::uuid, $3::uuid, $4::uuid, $5)
RETURNING id
`

type CreateInvitationParams struct {
	ID        uuid.UUID               `json:"id"`
	ContestID uuid.UUID               `json:"contest_id"`
	UserID    uuid.UUID               `json:"user_id"`
	InvitedBy uuid.UUID               `json:"invited_by"`
	Status    ContestInvitationStatus `json:"status"`
}

// Contest Invitations operations
func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ID,
		arg.ContestID,
		arg.UserID,
		arg.InvitedBy,
		arg.Status,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAccessRequest = `-- name: DeleteAccessRequest :exec
DELETE FROM contest_access_requests
WHERE id = $1::uuid
`

func (q *Queries) DeleteAccessRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccessRequest, id)
	return err
}

const deleteContest = `-- name: DeleteContest :exec
DELETE FROM contests
WHERE id = $1::uuid
`

func (q *Queries) DeleteContest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteContest, id)
	return err
}

const deleteContestMember = `-- name: DeleteContestMember :exec
DELETE FROM contest_members
WHERE user_id = $1::uuid AND contest_id = $2::uuid
`

type DeleteContestMemberParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ContestID uuid.UUID `json:"contest_id"`
}

func (q *Queries) DeleteContestMember(ctx context.Context, arg DeleteContestMemberParams) error {
	_, err := q.db.Exec(ctx, deleteContestMember, arg.UserID, arg.ContestID)
	return err
}

const deleteContestProblem = `-- name: DeleteContestProblem :exec
DELETE
FROM contest_problem
WHERE contest_id = $1::uuid
  AND problem_id = $2::uuid
`

type DeleteContestProblemParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	ProblemID uuid.UUID `json:"problem_id"`
}

func (q *Queries) DeleteContestProblem(ctx context.Context, arg DeleteContestProblemParams) error {
	_, err := q.db.Exec(ctx, deleteContestProblem, arg.ContestID, arg.ProblemID)
	return err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM contest_invitations
WHERE id = $1::uuid
`

func (q *Queries) DeleteInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvitation, id)
	return err
}

const getAccessRequest = `-- name: GetAccessRequest :one
SELECT id, contest_id, user_id, status, created_at, updated_at
FROM contest_access_requests
WHERE contest_id = $1::uuid
  AND user_id = $2::uuid
`

type GetAccessRequestParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetAccessRequest(ctx context.Context, arg GetAccessRequestParams) (ContestAccessRequest, error) {
	row := q.db.QueryRow(ctx, getAccessRequest, arg.ContestID, arg.UserID)
	var i ContestAccessRequest
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccessRequestById = `-- name: GetAccessRequestById :one
SELECT id, contest_id, user_id, status, created_at, updated_at
FROM contest_access_requests
WHERE id = $1::uuid
`

func (q *Queries) GetAccessRequestById(ctx context.Context, id uuid.UUID) (ContestAccessRequest, error) {
	row := q.db.QueryRow(ctx, getAccessRequestById, id)
	var i ContestAccessRequest
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContest = `-- name: GetContest :one
SELECT
    id,
    title,
    description,
    visibility,
    monitor_scope,
    submissions_list_scope,
    submissions_review_scope,
    created_by,
    start_time,
    end_time,
    scoring_mode,
    created_at,
    updated_at
FROM contests
WHERE id = $1::uuid
`

type GetContestRow struct {
	ID                     uuid.UUID          `json:"id"`
	Title                  string             `json:"title"`
	Description            string             `json:"description"`
	Visibility             ContestVisibility  `json:"visibility"`
	MonitorScope           ContestRole        `json:"monitor_scope"`
	SubmissionsListScope   ContestRole        `json:"submissions_list_scope"`
	SubmissionsReviewScope ContestRole        `json:"submissions_review_scope"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
	StartTime              pgtype.Timestamptz `json:"start_time"`
	EndTime                pgtype.Timestamptz `json:"end_time"`
	ScoringMode            ContestScoringMode `json:"scoring_mode"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
}

func (q *Queries) GetContest(ctx context.Context, id uuid.UUID) (GetContestRow, error) {
	row := q.db.QueryRow(ctx, getContest, id)
	var i GetContestRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Visibility,
		&i.MonitorScope,
		&i.SubmissionsListScope,
		&i.SubmissionsReviewScope,
		&i.CreatedBy,
		&i.StartTime,
		&i.EndTime,
		&i.ScoringMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContestMember = `-- name: GetContestMember :one
SELECT contest_id,
       user_id,
       role
FROM contest_members
WHERE contest_id = $1::uuid
  AND user_id = $2::uuid
`

type GetContestMemberParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type GetContestMemberRow struct {
	ContestID uuid.UUID   `json:"contest_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Role      ContestRole `json:"role"`
}

func (q *Queries) GetContestMember(ctx context.Context, arg GetContestMemberParams) (GetContestMemberRow, error) {
	row := q.db.QueryRow(ctx, getContestMember, arg.ContestID, arg.UserID)
	var i GetContestMemberRow
	err := row.Scan(&i.ContestID, &i.UserID, &i.Role)
	return i, err
}

const getContestMonitor = `-- name: GetContestMonitor :many

SELECT 
    u.id AS user_id,
    u.username,
    COALESCE(SUM(CASE 
        WHEN s.state = 200 THEN 
            CASE 
                WHEN c.scoring_mode = 'points' THEN s.score 
                ELSE 100  -- binary mode: full points for AC
            END
        ELSE 0 
    END), 0) AS total_score,
    COALESCE(SUM(CASE WHEN s.state = 200 THEN s.penalty ELSE 0 END), 0) AS total_penalty,
    COUNT(DISTINCT CASE WHEN s.state = 200 THEN cp.problem_id END) AS solved_count
FROM contest_members cm
LEFT JOIN users u ON cm.user_id = u.id
LEFT JOIN contests c ON cm.contest_id = c.id
LEFT JOIN contest_problem cp ON cp.contest_id = cm.contest_id
LEFT JOIN LATERAL (
    SELECT 
        s.problem_id,
        s.state,
        s.score,
        s.penalty
    FROM submissions s
    WHERE s.contest_id = cm.contest_id
      AND s.created_by = cm.user_id
      AND s.problem_id = cp.problem_id
    ORDER BY 
        CASE WHEN s.state = 200 THEN 0 ELSE 1 END,  -- AC submissions first
        s.score DESC,  -- Then by score
        s.created_at ASC  -- Then by time
    LIMIT 1
) s ON true
WHERE cm.contest_id = $1::uuid
  AND cm.role = 'participant'
GROUP BY u.id, u.username
ORDER BY total_score DESC, total_penalty ASC, u.username ASC
LIMIT $3 OFFSET $2
`

type GetContestMonitorParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	Offset    int32     `json:"offset"`
	Limit     int32     `json:"limit"`
}

type GetContestMonitorRow struct {
	UserID       pgtype.UUID `json:"user_id"`
	Username     *string     `json:"username"`
	TotalScore   interface{} `json:"total_score"`
	TotalPenalty interface{} `json:"total_penalty"`
	SolvedCount  int64       `json:"solved_count"`
}

// Monitor Query - Calculate standings
func (q *Queries) GetContestMonitor(ctx context.Context, arg GetContestMonitorParams) ([]GetContestMonitorRow, error) {
	rows, err := q.db.Query(ctx, getContestMonitor, arg.ContestID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetContestMonitorRow{}
	for rows.Next() {
		var i GetContestMonitorRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.TotalScore,
			&i.TotalPenalty,
			&i.SolvedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContestProblem = `-- name: GetContestProblem :one
SELECT cp.problem_id,
       p.title,
       p.time_limit,
       p.memory_limit,
       cp.position,
       p.legend_html,
       p.input_format_html,
       p.output_format_html,
       p.notes_html,
       p.scoring_html,
       p.created_at,
       p.updated_at
FROM contest_problem cp
         LEFT JOIN problems p ON cp.problem_id = p.id
WHERE cp.contest_id = $1::uuid
  AND cp.problem_id = $2::uuid
`

type GetContestProblemParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	ProblemID uuid.UUID `json:"problem_id"`
}

type GetContestProblemRow struct {
	ProblemID        pgtype.UUID        `json:"problem_id"`
	Title            *string            `json:"title"`
	TimeLimit        *int32             `json:"time_limit"`
	MemoryLimit      *int32             `json:"memory_limit"`
	Position         int32              `json:"position"`
	LegendHtml       *string            `json:"legend_html"`
	InputFormatHtml  *string            `json:"input_format_html"`
	OutputFormatHtml *string            `json:"output_format_html"`
	NotesHtml        *string            `json:"notes_html"`
	ScoringHtml      *string            `json:"scoring_html"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetContestProblem(ctx context.Context, arg GetContestProblemParams) (GetContestProblemRow, error) {
	row := q.db.QueryRow(ctx, getContestProblem, arg.ContestID, arg.ProblemID)
	var i GetContestProblemRow
	err := row.Scan(
		&i.ProblemID,
		&i.Title,
		&i.TimeLimit,
		&i.MemoryLimit,
		&i.Position,
		&i.LegendHtml,
		&i.InputFormatHtml,
		&i.OutputFormatHtml,
		&i.NotesHtml,
		&i.ScoringHtml,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContestProblems = `-- name: GetContestProblems :many
SELECT cp.problem_id,
       p.title,
       p.time_limit,
       p.memory_limit,
       cp.position,
       p.created_at,
       p.updated_at
FROM contest_problem cp
         LEFT JOIN problems p ON cp.problem_id = p.id
WHERE cp.contest_id = $1::uuid
ORDER BY cp.position
`

type GetContestProblemsRow struct {
	ProblemID   pgtype.UUID        `json:"problem_id"`
	Title       *string            `json:"title"`
	TimeLimit   *int32             `json:"time_limit"`
	MemoryLimit *int32             `json:"memory_limit"`
	Position    int32              `json:"position"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetContestProblems(ctx context.Context, contestID uuid.UUID) ([]GetContestProblemsRow, error) {
	rows, err := q.db.Query(ctx, getContestProblems, contestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetContestProblemsRow{}
	for rows.Next() {
		var i GetContestProblemsRow
		if err := rows.Scan(
			&i.ProblemID,
			&i.Title,
			&i.TimeLimit,
			&i.MemoryLimit,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvitation = `-- name: GetInvitation :one
SELECT id, contest_id, user_id, invited_by, status, created_at, updated_at
FROM contest_invitations
WHERE id = $1::uuid
`

func (q *Queries) GetInvitation(ctx context.Context, id uuid.UUID) (ContestInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitation, id)
	var i ContestInvitation
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.InvitedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationByUser = `-- name: GetInvitationByUser :one
SELECT id, contest_id, user_id, invited_by, status, created_at, updated_at
FROM contest_invitations
WHERE contest_id = $1::uuid
  AND user_id = $2::uuid
  AND status != 'revoked'
ORDER BY created_at DESC
LIMIT 1
`

type GetInvitationByUserParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetInvitationByUser(ctx context.Context, arg GetInvitationByUserParams) (ContestInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByUser, arg.ContestID, arg.UserID)
	var i ContestInvitation
	err := row.Scan(
		&i.ID,
		&i.ContestID,
		&i.UserID,
		&i.InvitedBy,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaxProblemPosition = `-- name: GetMaxProblemPosition :one
SELECT COALESCE(MAX(position), -1) AS max_position
FROM contest_problem
WHERE contest_id = $1::uuid
`

func (q *Queries) GetMaxProblemPosition(ctx context.Context, contestID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getMaxProblemPosition, contestID)
	var max_position interface{}
	err := row.Scan(&max_position)
	return max_position, err
}

const getMonitorProblemDetails = `-- name: GetMonitorProblemDetails :many
SELECT 
    cp.problem_id,
    cp.position,
    COALESCE(s.score, 0) AS score,
    COALESCE(s.attempts, 0) AS attempts,
    COALESCE(s.solved, false) AS solved,
    COALESCE(s.penalty, 0) AS penalty
FROM contest_problem cp
LEFT JOIN LATERAL (
    SELECT 
        MAX(CASE WHEN sub.state = 200 THEN sub.score ELSE 0 END) AS score,
        COUNT(*) AS attempts,
        bool_or(sub.state = 200) AS solved,
        MAX(CASE WHEN sub.state = 200 THEN sub.penalty ELSE 0 END) AS penalty
    FROM submissions sub
    WHERE sub.contest_id = $1::uuid
      AND sub.problem_id = cp.problem_id
      AND sub.created_by = $2::uuid
) s ON true
WHERE cp.contest_id = $1::uuid
ORDER BY cp.position ASC
`

type GetMonitorProblemDetailsParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type GetMonitorProblemDetailsRow struct {
	ProblemID pgtype.UUID `json:"problem_id"`
	Position  int32       `json:"position"`
	Score     interface{} `json:"score"`
	Attempts  int64       `json:"attempts"`
	Solved    bool        `json:"solved"`
	Penalty   interface{} `json:"penalty"`
}

func (q *Queries) GetMonitorProblemDetails(ctx context.Context, arg GetMonitorProblemDetailsParams) ([]GetMonitorProblemDetailsRow, error) {
	rows, err := q.db.Query(ctx, getMonitorProblemDetails, arg.ContestID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonitorProblemDetailsRow{}
	for rows.Next() {
		var i GetMonitorProblemDetailsRow
		if err := rows.Scan(
			&i.ProblemID,
			&i.Position,
			&i.Score,
			&i.Attempts,
			&i.Solved,
			&i.Penalty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessRequests = `-- name: ListAccessRequests :many
SELECT car.id, car.contest_id, car.user_id, car.status, car.created_at, car.updated_at,
       u.username, u.role AS user_role
FROM contest_access_requests car
LEFT JOIN users u ON car.user_id = u.id
WHERE car.contest_id = $1::uuid
  AND ($2::text IS NULL OR car.status = $2::contest_access_request_status)
ORDER BY car.created_at DESC
LIMIT $4 OFFSET $3
`

type ListAccessRequestsParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	Status    *string   `json:"status"`
	Offset    int32     `json:"offset"`
	Limit     int32     `json:"limit"`
}

type ListAccessRequestsRow struct {
	ID        uuid.UUID                  `json:"id"`
	ContestID uuid.UUID                  `json:"contest_id"`
	UserID    uuid.UUID                  `json:"user_id"`
	Status    ContestAccessRequestStatus `json:"status"`
	CreatedAt time.Time                  `json:"created_at"`
	UpdatedAt time.Time                  `json:"updated_at"`
	Username  *string                    `json:"username"`
	UserRole  NullUserRole               `json:"user_role"`
}

func (q *Queries) ListAccessRequests(ctx context.Context, arg ListAccessRequestsParams) ([]ListAccessRequestsRow, error) {
	rows, err := q.db.Query(ctx, listAccessRequests,
		arg.ContestID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccessRequestsRow{}
	for rows.Next() {
		var i ListAccessRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.UserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.UserRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminContests = `-- name: ListAdminContests :many

SELECT c.id,
       c.title,
       c.description,
       c.visibility,
       c.monitor_scope,
       c.submissions_list_scope,
       c.submissions_review_scope,
       c.created_by,
       c.start_time,
       c.end_time,
       c.scoring_mode,
       c.created_at,
       c.updated_at
FROM contests c
WHERE (
    $1::text IS NULL
        OR $1 = ''
        OR (
        CASE
            WHEN LENGTH($1) < 3 THEN c.title ILIKE '%' || $1 || '%'
            ELSE word_similarity(c.title, $1) > 0.1
            END
        )
    )
  AND (
    $2::text IS NULL
        OR c.visibility = $2::contest_visibility
    )
ORDER BY CASE
             WHEN $1::text IS NOT NULL
                 AND $1 != ''
                 AND LENGTH($1) >= 3 THEN word_similarity(c.title, $1)
             END DESC NULLS LAST,
         CASE
             WHEN $3::text = 'created_at' AND $4::text = 'desc' THEN c.created_at
             END DESC,
         CASE
             WHEN $3::text = 'created_at' AND $4::text = 'asc' THEN c.created_at
             END,
         CASE
             WHEN $3::text = 'updated_at' AND $4::text = 'desc' THEN c.updated_at
             END DESC,
         CASE
             WHEN $3::text = 'updated_at' AND $4::text = 'asc' THEN c.updated_at
             END,
         CASE
             WHEN $3::text = 'title' AND $4::text = 'desc' THEN c.title
             END DESC,
         CASE
             WHEN $3::text = 'title' AND $4::text = 'asc' THEN c.title
             END,
         CASE
             WHEN $3::text IS NULL OR $3 = '' THEN c.created_at
             END DESC
LIMIT $6 OFFSET $5
`

type ListAdminContestsParams struct {
	Search     *string `json:"search"`
	Visibility *string `json:"visibility"`
	SortBy     *string `json:"sort_by"`
	SortOrder  *string `json:"sort_order"`
	Offset     int32   `json:"offset"`
	Limit      int32   `json:"limit"`
}

type ListAdminContestsRow struct {
	ID                     uuid.UUID          `json:"id"`
	Title                  string             `json:"title"`
	Description            string             `json:"description"`
	Visibility             ContestVisibility  `json:"visibility"`
	MonitorScope           ContestRole        `json:"monitor_scope"`
	SubmissionsListScope   ContestRole        `json:"submissions_list_scope"`
	SubmissionsReviewScope ContestRole        `json:"submissions_review_scope"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
	StartTime              pgtype.Timestamptz `json:"start_time"`
	EndTime                pgtype.Timestamptz `json:"end_time"`
	ScoringMode            ContestScoringMode `json:"scoring_mode"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
}

// Admin contests listing
func (q *Queries) ListAdminContests(ctx context.Context, arg ListAdminContestsParams) ([]ListAdminContestsRow, error) {
	rows, err := q.db.Query(ctx, listAdminContests,
		arg.Search,
		arg.Visibility,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminContestsRow{}
	for rows.Next() {
		var i ListAdminContestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Visibility,
			&i.MonitorScope,
			&i.SubmissionsListScope,
			&i.SubmissionsReviewScope,
			&i.CreatedBy,
			&i.StartTime,
			&i.EndTime,
			&i.ScoringMode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContestMembers = `-- name: ListContestMembers :many
SELECT u.id AS user_id,
    cm.contest_id,
    u.username,
    u.role AS role,
    cm.role AS contest_role,
    u.kratos_id,
    u.created_at,
    u.updated_at
FROM contest_members cm
    LEFT JOIN users u ON cm.user_id = u.id
WHERE contest_id = $1::uuid
LIMIT $3 OFFSET $2
`

type ListContestMembersParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	Offset    int32     `json:"offset"`
	Limit     int32     `json:"limit"`
}

type ListContestMembersRow struct {
	UserID      pgtype.UUID        `json:"user_id"`
	ContestID   uuid.UUID          `json:"contest_id"`
	Username    *string            `json:"username"`
	Role        NullUserRole       `json:"role"`
	ContestRole ContestRole        `json:"contest_role"`
	KratosID    *string            `json:"kratos_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListContestMembers(ctx context.Context, arg ListContestMembersParams) ([]ListContestMembersRow, error) {
	rows, err := q.db.Query(ctx, listContestMembers, arg.ContestID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContestMembersRow{}
	for rows.Next() {
		var i ListContestMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.ContestID,
			&i.Username,
			&i.Role,
			&i.ContestRole,
			&i.KratosID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitations = `-- name: ListInvitations :many
SELECT ci.id, ci.contest_id, ci.user_id, ci.invited_by, ci.status, ci.created_at, ci.updated_at,
       u.username, u.role AS user_role,
       inv.username AS invited_by_username
FROM contest_invitations ci
LEFT JOIN users u ON ci.user_id = u.id
LEFT JOIN users inv ON ci.invited_by = inv.id
WHERE ci.contest_id = $1::uuid
  AND ($2::text IS NULL OR ci.status = $2::contest_invitation_status)
ORDER BY ci.created_at DESC
LIMIT $4 OFFSET $3
`

type ListInvitationsParams struct {
	ContestID uuid.UUID `json:"contest_id"`
	Status    *string   `json:"status"`
	Offset    int32     `json:"offset"`
	Limit     int32     `json:"limit"`
}

type ListInvitationsRow struct {
	ID                uuid.UUID               `json:"id"`
	ContestID         uuid.UUID               `json:"contest_id"`
	UserID            uuid.UUID               `json:"user_id"`
	InvitedBy         uuid.UUID               `json:"invited_by"`
	Status            ContestInvitationStatus `json:"status"`
	CreatedAt         time.Time               `json:"created_at"`
	UpdatedAt         time.Time               `json:"updated_at"`
	Username          *string                 `json:"username"`
	UserRole          NullUserRole            `json:"user_role"`
	InvitedByUsername *string                 `json:"invited_by_username"`
}

func (q *Queries) ListInvitations(ctx context.Context, arg ListInvitationsParams) ([]ListInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listInvitations,
		arg.ContestID,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitationsRow{}
	for rows.Next() {
		var i ListInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.UserID,
			&i.InvitedBy,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.UserRole,
			&i.InvitedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicContests = `-- name: ListPublicContests :many

SELECT c.id,
       c.title,
       c.description,
       c.visibility,
       c.monitor_scope,
       c.submissions_list_scope,
       c.submissions_review_scope,
       c.created_by,
       c.start_time,
       c.end_time,
       c.scoring_mode,
       c.created_at,
       c.updated_at
FROM contests c
WHERE c.visibility = 'public'
  AND (
    $1::text IS NULL
        OR $1 = ''
        OR (
        CASE
            WHEN LENGTH($1) < 3 THEN c.title ILIKE '%' || $1 || '%'
            ELSE word_similarity(c.title, $1) > 0.1
            END
        )
    )
ORDER BY CASE
             WHEN $1::text IS NOT NULL
                 AND $1 != ''
                 AND LENGTH($1) >= 3 THEN word_similarity(c.title, $1)
             END DESC NULLS LAST,
         CASE
             WHEN $2::text = 'created_at' AND $3::text = 'desc' THEN c.created_at
             END DESC,
         CASE
             WHEN $2::text = 'created_at' AND $3::text = 'asc' THEN c.created_at
             END,
         CASE
             WHEN $2::text = 'updated_at' AND $3::text = 'desc' THEN c.updated_at
             END DESC,
         CASE
             WHEN $2::text = 'updated_at' AND $3::text = 'asc' THEN c.updated_at
             END,
         CASE
             WHEN $2::text = 'title' AND $3::text = 'desc' THEN c.title
             END DESC,
         CASE
             WHEN $2::text = 'title' AND $3::text = 'asc' THEN c.title
             END,
         CASE
             WHEN $2::text IS NULL OR $2 = '' THEN c.created_at
             END DESC
LIMIT $5 OFFSET $4
`

type ListPublicContestsParams struct {
	Search    *string `json:"search"`
	SortBy    *string `json:"sort_by"`
	SortOrder *string `json:"sort_order"`
	Offset    int32   `json:"offset"`
	Limit     int32   `json:"limit"`
}

type ListPublicContestsRow struct {
	ID                     uuid.UUID          `json:"id"`
	Title                  string             `json:"title"`
	Description            string             `json:"description"`
	Visibility             ContestVisibility  `json:"visibility"`
	MonitorScope           ContestRole        `json:"monitor_scope"`
	SubmissionsListScope   ContestRole        `json:"submissions_list_scope"`
	SubmissionsReviewScope ContestRole        `json:"submissions_review_scope"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
	StartTime              pgtype.Timestamptz `json:"start_time"`
	EndTime                pgtype.Timestamptz `json:"end_time"`
	ScoringMode            ContestScoringMode `json:"scoring_mode"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
}

// Public contests listing
func (q *Queries) ListPublicContests(ctx context.Context, arg ListPublicContestsParams) ([]ListPublicContestsRow, error) {
	rows, err := q.db.Query(ctx, listPublicContests,
		arg.Search,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicContestsRow{}
	for rows.Next() {
		var i ListPublicContestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Visibility,
			&i.MonitorScope,
			&i.SubmissionsListScope,
			&i.SubmissionsReviewScope,
			&i.CreatedBy,
			&i.StartTime,
			&i.EndTime,
			&i.ScoringMode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserContests = `-- name: ListUserContests :many

SELECT c.id,
       c.title,
       c.description,
       c.visibility,
       c.monitor_scope,
       c.submissions_list_scope,
       c.submissions_review_scope,
       c.created_by,
       c.start_time,
       c.end_time,
       c.scoring_mode,
       c.created_at,
       c.updated_at
FROM contests c
LEFT JOIN submissions s ON s.contest_id = c.id AND s.created_by = $1::uuid
WHERE (
    -- Private contests where user is member
    (c.visibility = 'private' AND EXISTS(SELECT 1 FROM contest_members cm WHERE cm.contest_id = c.id AND cm.user_id = $1::uuid))
    OR
    -- Public contests where user is member OR has submissions
    (c.visibility = 'public' AND (
        EXISTS(SELECT 1 FROM contest_members cm WHERE cm.contest_id = c.id AND cm.user_id = $1::uuid)
        OR EXISTS(SELECT 1 FROM submissions sub WHERE sub.contest_id = c.id AND sub.created_by = $1::uuid)
    ))
)
  AND (
    $2::text IS NULL
        OR $2 = ''
        OR (
        CASE
            WHEN LENGTH($2) < 3 THEN c.title ILIKE '%' || $2 || '%'
            ELSE word_similarity(c.title, $2) > 0.1
            END
        )
    )
GROUP BY c.id
ORDER BY CASE
             WHEN $2::text IS NOT NULL
                 AND $2 != ''
                 AND LENGTH($2) >= 3 THEN word_similarity(c.title, $2)
             END DESC NULLS LAST,
         CASE
             WHEN $3::text = 'last_submission_time' AND $4::text = 'desc' THEN MAX(s.created_at)
             END DESC NULLS LAST,
         CASE
             WHEN $3::text = 'last_submission_time' AND $4::text = 'asc' THEN MAX(s.created_at)
             END NULLS LAST,
         CASE
             WHEN $3::text = 'created_at' AND $4::text = 'desc' THEN c.created_at
             END DESC,
         CASE
             WHEN $3::text = 'created_at' AND $4::text = 'asc' THEN c.created_at
             END,
         CASE
             WHEN $3::text = 'updated_at' AND $4::text = 'desc' THEN c.updated_at
             END DESC,
         CASE
             WHEN $3::text = 'updated_at' AND $4::text = 'asc' THEN c.updated_at
             END,
         CASE
             WHEN $3::text = 'title' AND $4::text = 'desc' THEN c.title
             END DESC,
         CASE
             WHEN $3::text = 'title' AND $4::text = 'asc' THEN c.title
             END,
         CASE
             WHEN $3::text IS NULL OR $3 = '' THEN MAX(s.created_at)
             END DESC NULLS LAST
LIMIT $6 OFFSET $5
`

type ListUserContestsParams struct {
	CreatedBy uuid.UUID `json:"created_by"`
	Search    *string   `json:"search"`
	SortBy    *string   `json:"sort_by"`
	SortOrder *string   `json:"sort_order"`
	Offset    int32     `json:"offset"`
	Limit     int32     `json:"limit"`
}

type ListUserContestsRow struct {
	ID                     uuid.UUID          `json:"id"`
	Title                  string             `json:"title"`
	Description            string             `json:"description"`
	Visibility             ContestVisibility  `json:"visibility"`
	MonitorScope           ContestRole        `json:"monitor_scope"`
	SubmissionsListScope   ContestRole        `json:"submissions_list_scope"`
	SubmissionsReviewScope ContestRole        `json:"submissions_review_scope"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
	StartTime              pgtype.Timestamptz `json:"start_time"`
	EndTime                pgtype.Timestamptz `json:"end_time"`
	ScoringMode            ContestScoringMode `json:"scoring_mode"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
}

// User contests listing
func (q *Queries) ListUserContests(ctx context.Context, arg ListUserContestsParams) ([]ListUserContestsRow, error) {
	rows, err := q.db.Query(ctx, listUserContests,
		arg.CreatedBy,
		arg.Search,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserContestsRow{}
	for rows.Next() {
		var i ListUserContestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Visibility,
			&i.MonitorScope,
			&i.SubmissionsListScope,
			&i.SubmissionsReviewScope,
			&i.CreatedBy,
			&i.StartTime,
			&i.EndTime,
			&i.ScoringMode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserInvitations = `-- name: ListUserInvitations :many
SELECT ci.id, ci.contest_id, ci.user_id, ci.invited_by, ci.status, ci.created_at, ci.updated_at,
       c.title AS contest_title,
       inv.username AS invited_by_username
FROM contest_invitations ci
LEFT JOIN contests c ON ci.contest_id = c.id
LEFT JOIN users inv ON ci.invited_by = inv.id
WHERE ci.user_id = $1::uuid
  AND ci.status = 'pending'
ORDER BY ci.created_at DESC
LIMIT $3 OFFSET $2
`

type ListUserInvitationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Offset int32     `json:"offset"`
	Limit  int32     `json:"limit"`
}

type ListUserInvitationsRow struct {
	ID                uuid.UUID               `json:"id"`
	ContestID         uuid.UUID               `json:"contest_id"`
	UserID            uuid.UUID               `json:"user_id"`
	InvitedBy         uuid.UUID               `json:"invited_by"`
	Status            ContestInvitationStatus `json:"status"`
	CreatedAt         time.Time               `json:"created_at"`
	UpdatedAt         time.Time               `json:"updated_at"`
	ContestTitle      *string                 `json:"contest_title"`
	InvitedByUsername *string                 `json:"invited_by_username"`
}

func (q *Queries) ListUserInvitations(ctx context.Context, arg ListUserInvitationsParams) ([]ListUserInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listUserInvitations, arg.UserID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserInvitationsRow{}
	for rows.Next() {
		var i ListUserInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContestID,
			&i.UserID,
			&i.InvitedBy,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContestTitle,
			&i.InvitedByUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkshopContests = `-- name: ListWorkshopContests :many

SELECT c.id,
       c.title,
       c.description,
       c.visibility,
       c.monitor_scope,
       c.submissions_list_scope,
       c.submissions_review_scope,
       c.created_by,
       c.start_time,
       c.end_time,
       c.scoring_mode,
       c.created_at,
       c.updated_at
FROM contests c
INNER JOIN contest_members cm ON cm.contest_id = c.id
WHERE cm.user_id = $1::uuid
  AND cm.role IN ('owner', 'moderator')
  AND (
    $2::text IS NULL
        OR $2 = ''
        OR (
        CASE
            WHEN LENGTH($2) < 3 THEN c.title ILIKE '%' || $2 || '%'
            ELSE word_similarity(c.title, $2) > 0.1
            END
        )
    )
ORDER BY CASE
             WHEN $2::text IS NOT NULL
                 AND $2 != ''
                 AND LENGTH($2) >= 3 THEN word_similarity(c.title, $2)
             END DESC NULLS LAST,
         CASE
             WHEN $3::text = 'created_at' AND $4::text = 'desc' THEN c.created_at
             END DESC,
         CASE
             WHEN $3::text = 'created_at' AND $4::text = 'asc' THEN c.created_at
             END,
         CASE
             WHEN $3::text = 'updated_at' AND $4::text = 'desc' THEN c.updated_at
             END DESC,
         CASE
             WHEN $3::text = 'updated_at' AND $4::text = 'asc' THEN c.updated_at
             END,
         CASE
             WHEN $3::text = 'title' AND $4::text = 'desc' THEN c.title
             END DESC,
         CASE
             WHEN $3::text = 'title' AND $4::text = 'asc' THEN c.title
             END,
         CASE
             WHEN $3::text IS NULL OR $3 = '' THEN c.created_at
             END DESC
LIMIT $6 OFFSET $5
`

type ListWorkshopContestsParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Search    *string   `json:"search"`
	SortBy    *string   `json:"sort_by"`
	SortOrder *string   `json:"sort_order"`
	Offset    int32     `json:"offset"`
	Limit     int32     `json:"limit"`
}

type ListWorkshopContestsRow struct {
	ID                     uuid.UUID          `json:"id"`
	Title                  string             `json:"title"`
	Description            string             `json:"description"`
	Visibility             ContestVisibility  `json:"visibility"`
	MonitorScope           ContestRole        `json:"monitor_scope"`
	SubmissionsListScope   ContestRole        `json:"submissions_list_scope"`
	SubmissionsReviewScope ContestRole        `json:"submissions_review_scope"`
	CreatedBy              pgtype.UUID        `json:"created_by"`
	StartTime              pgtype.Timestamptz `json:"start_time"`
	EndTime                pgtype.Timestamptz `json:"end_time"`
	ScoringMode            ContestScoringMode `json:"scoring_mode"`
	CreatedAt              time.Time          `json:"created_at"`
	UpdatedAt              time.Time          `json:"updated_at"`
}

// Workshop contests listing
func (q *Queries) ListWorkshopContests(ctx context.Context, arg ListWorkshopContestsParams) ([]ListWorkshopContestsRow, error) {
	rows, err := q.db.Query(ctx, listWorkshopContests,
		arg.UserID,
		arg.Search,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkshopContestsRow{}
	for rows.Next() {
		var i ListWorkshopContestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Visibility,
			&i.MonitorScope,
			&i.SubmissionsListScope,
			&i.SubmissionsReviewScope,
			&i.CreatedBy,
			&i.StartTime,
			&i.EndTime,
			&i.ScoringMode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderContestProblemsAfterDelete = `-- name: ReorderContestProblemsAfterDelete :exec
UPDATE contest_problem
SET position = position - 1
WHERE contest_id = $1::uuid
  AND position > $2
`

type ReorderContestProblemsAfterDeleteParams struct {
	ContestID       uuid.UUID `json:"contest_id"`
	DeletedPosition int32     `json:"deleted_position"`
}

func (q *Queries) ReorderContestProblemsAfterDelete(ctx context.Context, arg ReorderContestProblemsAfterDeleteParams) error {
	_, err := q.db.Exec(ctx, reorderContestProblemsAfterDelete, arg.ContestID, arg.DeletedPosition)
	return err
}

const updateAccessRequestStatus = `-- name: UpdateAccessRequestStatus :exec
UPDATE contest_access_requests
SET status = $1
WHERE id = $2::uuid
`

type UpdateAccessRequestStatusParams struct {
	Status ContestAccessRequestStatus `json:"status"`
	ID     uuid.UUID                  `json:"id"`
}

func (q *Queries) UpdateAccessRequestStatus(ctx context.Context, arg UpdateAccessRequestStatusParams) error {
	_, err := q.db.Exec(ctx, updateAccessRequestStatus, arg.Status, arg.ID)
	return err
}

const updateContest = `-- name: UpdateContest :exec
UPDATE contests
SET title                    = COALESCE($1, title),
    description              = COALESCE($2, description),
    visibility               = COALESCE($3, visibility),
    monitor_scope            = COALESCE($4, monitor_scope),
    submissions_list_scope   = COALESCE($5, submissions_list_scope),
    submissions_review_scope = COALESCE($6, submissions_review_scope),
    start_time               = COALESCE($7, start_time),
    end_time                 = COALESCE($8, end_time),
    scoring_mode             = COALESCE($9, scoring_mode)
WHERE id = $10::uuid
`

type UpdateContestParams struct {
	Title                  *string                `json:"title"`
	Description            *string                `json:"description"`
	Visibility             NullContestVisibility  `json:"visibility"`
	MonitorScope           NullContestRole        `json:"monitor_scope"`
	SubmissionsListScope   NullContestRole        `json:"submissions_list_scope"`
	SubmissionsReviewScope NullContestRole        `json:"submissions_review_scope"`
	StartTime              pgtype.Timestamptz     `json:"start_time"`
	EndTime                pgtype.Timestamptz     `json:"end_time"`
	ScoringMode            NullContestScoringMode `json:"scoring_mode"`
	ID                     uuid.UUID              `json:"id"`
}

func (q *Queries) UpdateContest(ctx context.Context, arg UpdateContestParams) error {
	_, err := q.db.Exec(ctx, updateContest,
		arg.Title,
		arg.Description,
		arg.Visibility,
		arg.MonitorScope,
		arg.SubmissionsListScope,
		arg.SubmissionsReviewScope,
		arg.StartTime,
		arg.EndTime,
		arg.ScoringMode,
		arg.ID,
	)
	return err
}

const updateContestMember = `-- name: UpdateContestMember :exec
UPDATE contest_members
SET role = $1
WHERE contest_id = $2::uuid
  AND user_id = $3::uuid
`

type UpdateContestMemberParams struct {
	Role      ContestRole `json:"role"`
	ContestID uuid.UUID   `json:"contest_id"`
	UserID    uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateContestMember(ctx context.Context, arg UpdateContestMemberParams) error {
	_, err := q.db.Exec(ctx, updateContestMember, arg.Role, arg.ContestID, arg.UserID)
	return err
}

const updateContestProblemPosition = `-- name: UpdateContestProblemPosition :exec

UPDATE contest_problem
SET position = $1
WHERE contest_id = $2::uuid
  AND problem_id = $3::uuid
`

type UpdateContestProblemPositionParams struct {
	Position  int32     `json:"position"`
	ContestID uuid.UUID `json:"contest_id"`
	ProblemID uuid.UUID `json:"problem_id"`
}

// Problem Position Management
func (q *Queries) UpdateContestProblemPosition(ctx context.Context, arg UpdateContestProblemPositionParams) error {
	_, err := q.db.Exec(ctx, updateContestProblemPosition, arg.Position, arg.ContestID, arg.ProblemID)
	return err
}

const updateInvitationStatus = `-- name: UpdateInvitationStatus :exec
UPDATE contest_invitations
SET status = $1
WHERE id = $2::uuid
`

type UpdateInvitationStatusParams struct {
	Status ContestInvitationStatus `json:"status"`
	ID     uuid.UUID               `json:"id"`
}

func (q *Queries) UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) error {
	_, err := q.db.Exec(ctx, updateInvitationStatus, arg.Status, arg.ID)
	return err
}
