name: Deploy Production

on:
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      domain_name: steins.ru
      deploy_dir: ~/gate/deploy/prod
    secrets: inherit
